// @generated by protoc-gen-connect-es v1.6.1
// @generated from file proto/decide/v1alpha1/decide.proto (package proto.decide.v1alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DecideRequest, DecideResponse, ReportRequest, ReportResponse } from "./decide_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.decide.v1alpha1.DecideService
 */
export const DecideService = {
  typeName: "proto.decide.v1alpha1.DecideService",
  methods: {
    /**
     * @generated from rpc proto.decide.v1alpha1.DecideService.Decide
     */
    decide: {
      name: "Decide",
      I: DecideRequest,
      O: DecideResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.decide.v1alpha1.DecideService.Report
     */
    report: {
      name: "Report",
      I: ReportRequest,
      O: ReportResponse,
      kind: MethodKind.Unary,
    },
  }
};

