// @generated by protoc-gen-es v2.2.0
// @generated from file proto/guard/policy/v2/policy.proto (package proto.guard.policy.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/guard/policy/v2/policy.proto.
 */
export declare const file_proto_guard_policy_v2_policy: GenFile;

/**
 * GuardPolicyBundle is one immutable, versioned tenant policy snapshot as
 * published to D1 and KV.
 *
 * The bundle carries compiled artifacts, never source. Policy source, tests, and
 * builder specifications stay in PostgreSQL: publishing them would put author
 * text and server-only configuration on the edge for no runtime benefit.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyBundle
 */
export declare type GuardPolicyBundle = Message<"proto.guard.policy.v2.GuardPolicyBundle"> & {
  /**
   * Strict policy-language version. This message is version 2.
   *
   * @generated from field: uint32 language_version = 1;
   */
  languageVersion: number;

  /**
   * Opaque revision shared by the control plane, runtime mirrors, and SDKs.
   *
   * @generated from field: string revision = 2;
   */
  revision: string;

  /**
   * Policies keyed by exact label. The compiler rejects duplicate labels.
   *
   * @generated from field: repeated proto.guard.policy.v2.GuardPolicy policies = 10;
   */
  policies: GuardPolicy[];
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyBundle.
 * Use `create(GuardPolicyBundleSchema)` to create a new message.
 */
export declare const GuardPolicyBundleSchema: GenMessage<GuardPolicyBundle>;

/**
 * GuardPolicy is the single runtime policy for one exact Guard label.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicy
 */
export declare type GuardPolicy = Message<"proto.guard.policy.v2.GuardPolicy"> & {
  /**
   * Stable control-plane policy identity.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Exact GuardRequest.label matched by this policy.
   *
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * Whether a non-empty top-level GuardRequest.actor is required. Actor is an
   * opaque, stable principal identity asserted by trusted application code
   * from authenticated server-side state, never request, model, or tool input.
   *
   * @generated from field: bool requires_actor = 3;
   */
  requiresActor: boolean;

  /**
   * Named input contract. Names must be unique within the policy.
   *
   * @generated from field: repeated proto.guard.policy.v2.GuardPolicyInputRequirement inputs = 4;
   */
  inputs: GuardPolicyInputRequirement[];

  /**
   * Native detectors this policy needs. Detector IDs must be unique within
   * the policy. decide-service runs these and exposes their results to Rego.
   *
   * @generated from field: repeated proto.guard.policy.v2.GuardPolicyDetector detectors = 5;
   */
  detectors: GuardPolicyDetector[];

  /**
   * Stable rule identities. Rule IDs must be unique within the policy, and
   * Rego may emit only IDs declared here.
   *
   * @generated from field: repeated proto.guard.policy.v2.GuardPolicyRuleDeclaration rules = 6;
   */
  rules: GuardPolicyRuleDeclaration[];

  /**
   * The compiled runtime artifact as canonical JSON, produced by the pinned
   * OPA compiler in arcjet-decide/internal/regoc. Opaque to the control plane
   * after compilation: publication copies these exact bytes, and a retry never
   * recompiles.
   *
   * Absent when every rule is detector-backed and no expression is needed.
   *
   * @generated from field: string artifact = 7;
   */
  artifact: string;
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicy.
 * Use `create(GuardPolicySchema)` to create a new message.
 */
export declare const GuardPolicySchema: GenMessage<GuardPolicy>;

/**
 * GuardPolicyInputRequirement declares one named typed input. Unchanged from v1.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyInputRequirement
 */
export declare type GuardPolicyInputRequirement = Message<"proto.guard.policy.v2.GuardPolicyInputRequirement"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: proto.guard.policy.v2.GuardPolicyInputKind kind = 2;
   */
  kind: GuardPolicyInputKind;

  /**
   * @generated from field: proto.guard.policy.v2.GuardPolicyInputExposure exposure = 3;
   */
  exposure: GuardPolicyInputExposure;

  /**
   * @generated from field: bool required = 4;
   */
  required: boolean;
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyInputRequirement.
 * Use `create(GuardPolicyInputRequirementSchema)` to create a new message.
 */
export declare const GuardPolicyInputRequirementSchema: GenMessage<GuardPolicyInputRequirement>;

/**
 * GuardPolicyDetector declares one native detector run for this policy.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyDetector
 */
export declare type GuardPolicyDetector = Message<"proto.guard.policy.v2.GuardPolicyDetector"> & {
  /**
   * Stable identity, unique within the policy. Rego reads the detector's
   * result at input.signals.<kind>.<id>.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: proto.guard.policy.v2.GuardPolicyDetectorKind kind = 2;
   */
  kind: GuardPolicyDetectorKind;

  /**
   * The declared input this detector reads. Its kind must be STRING, and its
   * exposure must match the detector: SERVER for prompt injection, LOCAL for
   * sensitive information.
   *
   * @generated from field: string input_name = 3;
   */
  inputName: string;

  /**
   * Detector-specific configuration.
   *
   * @generated from oneof proto.guard.policy.v2.GuardPolicyDetector.config
   */
  config: {
    /**
     * @generated from field: proto.guard.policy.v2.GuardPolicySensitiveInfoConfig sensitive_info = 10;
     */
    value: GuardPolicySensitiveInfoConfig;
    case: "sensitiveInfo";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyDetector.
 * Use `create(GuardPolicyDetectorSchema)` to create a new message.
 */
export declare const GuardPolicyDetectorSchema: GenMessage<GuardPolicyDetector>;

/**
 * GuardPolicySensitiveInfoConfig filters which detected entity types matter.
 *
 * entities_allow exempts the listed types and denies other detected types;
 * entities_deny denies the listed types and allows other detected types. An
 * absent filter uses the evaluator default. A present empty allow list denies
 * every detected type; a present empty deny list allows every type. This
 * mirrors v1 exactly so the SDK projection is unchanged.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicySensitiveInfoConfig
 */
export declare type GuardPolicySensitiveInfoConfig = Message<"proto.guard.policy.v2.GuardPolicySensitiveInfoConfig"> & {
  /**
   * @generated from oneof proto.guard.policy.v2.GuardPolicySensitiveInfoConfig.entity_filter
   */
  entityFilter: {
    /**
     * @generated from field: proto.guard.policy.v2.GuardPolicyEntityList entities_allow = 1;
     */
    value: GuardPolicyEntityList;
    case: "entitiesAllow";
  } | {
    /**
     * @generated from field: proto.guard.policy.v2.GuardPolicyEntityList entities_deny = 2;
     */
    value: GuardPolicyEntityList;
    case: "entitiesDeny";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicySensitiveInfoConfig.
 * Use `create(GuardPolicySensitiveInfoConfigSchema)` to create a new message.
 */
export declare const GuardPolicySensitiveInfoConfigSchema: GenMessage<GuardPolicySensitiveInfoConfig>;

/**
 * GuardPolicyEntityList wraps sensitive-information entity names.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyEntityList
 */
export declare type GuardPolicyEntityList = Message<"proto.guard.policy.v2.GuardPolicyEntityList"> & {
  /**
   * @generated from field: repeated string entities = 1;
   */
  entities: string[];
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyEntityList.
 * Use `create(GuardPolicyEntityListSchema)` to create a new message.
 */
export declare const GuardPolicyEntityListSchema: GenMessage<GuardPolicyEntityList>;

/**
 * GuardPolicyRuleDeclaration is a stable rule identity and how it is decided.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyRuleDeclaration
 */
export declare type GuardPolicyRuleDeclaration = Message<"proto.guard.policy.v2.GuardPolicyRuleDeclaration"> & {
  /**
   * Stable rule identity. Appears in the Guard response and in evidence.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: proto.guard.policy.v2.GuardPolicyRuleMode mode = 2;
   */
  mode: GuardPolicyRuleMode;

  /**
   * @generated from field: proto.guard.policy.v2.GuardPolicyRuleExecution execution = 3;
   */
  execution: GuardPolicyRuleExecution;

  /**
   * @generated from field: proto.guard.policy.v2.GuardPolicyRuleKind kind = 4;
   */
  kind: GuardPolicyRuleKind;

  /**
   * Author-supplied text explaining the rule. Untrusted: bounded in length,
   * and excluded from logs, metrics, traces, and trusted LLM-facing fields.
   *
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * For a DETECTOR rule, the detector whose result decides it directly. Must
   * be empty for an EXPRESSION rule.
   *
   * @generated from field: string detector_id = 6;
   */
  detectorId: string;
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyRuleDeclaration.
 * Use `create(GuardPolicyRuleDeclarationSchema)` to create a new message.
 */
export declare const GuardPolicyRuleDeclarationSchema: GenMessage<GuardPolicyRuleDeclaration>;

/**
 * GuardPolicyDefinition is the editable authoring document held in PostgreSQL.
 *
 * It is never published to the edge and never sent to an SDK. The control plane
 * compiles it into a GuardPolicyBundle.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyDefinition
 */
export declare type GuardPolicyDefinition = Message<"proto.guard.policy.v2.GuardPolicyDefinition"> & {
  /**
   * @generated from field: uint32 language_version = 1;
   */
  languageVersion: number;

  /**
   * @generated from field: repeated proto.guard.policy.v2.GuardPolicyDefinitionEntry policies = 10;
   */
  policies: GuardPolicyDefinitionEntry[];
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyDefinition.
 * Use `create(GuardPolicyDefinitionSchema)` to create a new message.
 */
export declare const GuardPolicyDefinitionSchema: GenMessage<GuardPolicyDefinition>;

/**
 * GuardPolicyDefinitionEntry is one authored policy: its runtime contract plus
 * the source and tests that produced it.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyDefinitionEntry
 */
export declare type GuardPolicyDefinitionEntry = Message<"proto.guard.policy.v2.GuardPolicyDefinitionEntry"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * @generated from field: bool requires_actor = 3;
   */
  requiresActor: boolean;

  /**
   * @generated from field: repeated proto.guard.policy.v2.GuardPolicyInputRequirement inputs = 4;
   */
  inputs: GuardPolicyInputRequirement[];

  /**
   * @generated from field: repeated proto.guard.policy.v2.GuardPolicyDetector detectors = 5;
   */
  detectors: GuardPolicyDetector[];

  /**
   * @generated from field: repeated proto.guard.policy.v2.GuardPolicyRuleDeclaration rules = 6;
   */
  rules: GuardPolicyRuleDeclaration[];

  /**
   * The editable source of truth for this policy's expression.
   *
   * @generated from field: proto.guard.policy.v2.GuardPolicySource source = 7;
   */
  source?: GuardPolicySource;

  /**
   * Author-supplied and generated test cases, versioned with the revision.
   *
   * @generated from field: repeated proto.guard.policy.v2.GuardPolicyTest tests = 8;
   */
  tests: GuardPolicyTest[];
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyDefinitionEntry.
 * Use `create(GuardPolicyDefinitionEntrySchema)` to create a new message.
 */
export declare const GuardPolicyDefinitionEntrySchema: GenMessage<GuardPolicyDefinitionEntry>;

/**
 * GuardPolicySource is the editable expression source.
 *
 * Editing generated Rego drops the builder specification. That conversion is
 * one way: reconstructing a builder specification from arbitrary Rego is not
 * supported.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicySource
 */
export declare type GuardPolicySource = Message<"proto.guard.policy.v2.GuardPolicySource"> & {
  /**
   * @generated from oneof proto.guard.policy.v2.GuardPolicySource.source
   */
  source: {
    /**
     * Rego v1 text within the Arcjet profile.
     *
     * @generated from field: string rego = 1;
     */
    value: string;
    case: "rego";
  } | {
    /**
     * Structured specification the control plane renders to Rego.
     *
     * @generated from field: proto.guard.policy.v2.GuardPolicyBuilderSpec builder = 2;
     */
    value: GuardPolicyBuilderSpec;
    case: "builder";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicySource.
 * Use `create(GuardPolicySourceSchema)` to create a new message.
 */
export declare const GuardPolicySourceSchema: GenMessage<GuardPolicySource>;

/**
 * GuardPolicyBuilderSpec is the structured form the visual builder edits.
 *
 * The control plane renders it to Rego deterministically, then compiles that
 * Rego through the same pipeline an authored policy uses. There is no separate
 * builder evaluator.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyBuilderSpec
 */
export declare type GuardPolicyBuilderSpec = Message<"proto.guard.policy.v2.GuardPolicyBuilderSpec"> & {
  /**
   * Conditions that select each declared rule. One group per rule.
   *
   * @generated from field: repeated proto.guard.policy.v2.GuardPolicyBuilderRule rules = 1;
   */
  rules: GuardPolicyBuilderRule[];
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyBuilderSpec.
 * Use `create(GuardPolicyBuilderSpecSchema)` to create a new message.
 */
export declare const GuardPolicyBuilderSpecSchema: GenMessage<GuardPolicyBuilderSpec>;

/**
 * GuardPolicyBuilderRule binds one declared rule ID to a condition group.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyBuilderRule
 */
export declare type GuardPolicyBuilderRule = Message<"proto.guard.policy.v2.GuardPolicyBuilderRule"> & {
  /**
   * @generated from field: string rule_id = 1;
   */
  ruleId: string;

  /**
   * @generated from field: proto.guard.policy.v2.GuardPolicyBuilderGroup condition = 2;
   */
  condition?: GuardPolicyBuilderGroup;
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyBuilderRule.
 * Use `create(GuardPolicyBuilderRuleSchema)` to create a new message.
 */
export declare const GuardPolicyBuilderRuleSchema: GenMessage<GuardPolicyBuilderRule>;

/**
 * GuardPolicyBuilderGroup is a boolean combination of conditions.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyBuilderGroup
 */
export declare type GuardPolicyBuilderGroup = Message<"proto.guard.policy.v2.GuardPolicyBuilderGroup"> & {
  /**
   * @generated from field: proto.guard.policy.v2.GuardPolicyBuilderOperator operator = 1;
   */
  operator: GuardPolicyBuilderOperator;

  /**
   * Negates the whole group.
   *
   * @generated from field: bool negated = 2;
   */
  negated: boolean;

  /**
   * @generated from field: repeated proto.guard.policy.v2.GuardPolicyBuilderCondition conditions = 3;
   */
  conditions: GuardPolicyBuilderCondition[];

  /**
   * @generated from field: repeated proto.guard.policy.v2.GuardPolicyBuilderGroup groups = 4;
   */
  groups: GuardPolicyBuilderGroup[];
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyBuilderGroup.
 * Use `create(GuardPolicyBuilderGroupSchema)` to create a new message.
 */
export declare const GuardPolicyBuilderGroupSchema: GenMessage<GuardPolicyBuilderGroup>;

/**
 * GuardPolicyBuilderCondition is one comparison over a declared input or
 * detector result.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyBuilderCondition
 */
export declare type GuardPolicyBuilderCondition = Message<"proto.guard.policy.v2.GuardPolicyBuilderCondition"> & {
  /**
   * @generated from field: proto.guard.policy.v2.GuardPolicyBuilderComparison comparison = 1;
   */
  comparison: GuardPolicyBuilderComparison;

  /**
   * What the condition reads. Exactly one must be set.
   *
   * @generated from oneof proto.guard.policy.v2.GuardPolicyBuilderCondition.subject
   */
  subject: {
    /**
     * A declared SERVER input name.
     *
     * @generated from field: string input_name = 2;
     */
    value: string;
    case: "inputName";
  } | {
    /**
     * A declared detector ID, for DETECTED comparisons.
     *
     * @generated from field: string detector_id = 3;
     */
    value: string;
    case: "detectorId";
  } | { case: undefined; value?: undefined };

  /**
   * Literal operand. Which field applies depends on the comparison.
   *
   * @generated from oneof proto.guard.policy.v2.GuardPolicyBuilderCondition.operand
   */
  operand: {
    /**
     * @generated from field: string string_value = 10;
     */
    value: string;
    case: "stringValue";
  } | {
    /**
     * @generated from field: bool boolean_value = 11;
     */
    value: boolean;
    case: "booleanValue";
  } | {
    /**
     * @generated from field: int64 integer_value = 12;
     */
    value: bigint;
    case: "integerValue";
  } | {
    /**
     * @generated from field: double number_value = 13;
     */
    value: number;
    case: "numberValue";
  } | {
    /**
     * @generated from field: proto.guard.policy.v2.GuardPolicyStringList string_list_value = 14;
     */
    value: GuardPolicyStringList;
    case: "stringListValue";
  } | {
    /**
     * Compare against another declared input rather than a literal.
     *
     * @generated from field: string other_input_name = 15;
     */
    value: string;
    case: "otherInputName";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyBuilderCondition.
 * Use `create(GuardPolicyBuilderConditionSchema)` to create a new message.
 */
export declare const GuardPolicyBuilderConditionSchema: GenMessage<GuardPolicyBuilderCondition>;

/**
 * GuardPolicyStringList wraps string values used by list comparisons.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyStringList
 */
export declare type GuardPolicyStringList = Message<"proto.guard.policy.v2.GuardPolicyStringList"> & {
  /**
   * @generated from field: repeated string values = 1;
   */
  values: string[];
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyStringList.
 * Use `create(GuardPolicyStringListSchema)` to create a new message.
 */
export declare const GuardPolicyStringListSchema: GenMessage<GuardPolicyStringList>;

/**
 * GuardPolicyTest is one stored test case.
 *
 * Tests are stored inside the policy document and versioned with its revision,
 * so a rollback restores the tests that justified the restored policy. They run
 * through the official OPA evaluator at publication, and through the Worker
 * interpreter in the publish-time parity gate.
 *
 * @generated from message proto.guard.policy.v2.GuardPolicyTest
 */
export declare type GuardPolicyTest = Message<"proto.guard.policy.v2.GuardPolicyTest"> & {
  /**
   * Author-facing name, unique within the policy.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The complete input document as canonical JSON, matching the runtime
   * input contract: label, optional actor, values, and signals.
   *
   * @generated from field: string input_json = 2;
   */
  inputJson: string;

  /**
   * The rule IDs this input must produce, in any order.
   *
   * @generated from field: repeated string expect_rule_ids = 3;
   */
  expectRuleIds: string[];
};

/**
 * Describes the message proto.guard.policy.v2.GuardPolicyTest.
 * Use `create(GuardPolicyTestSchema)` to create a new message.
 */
export declare const GuardPolicyTestSchema: GenMessage<GuardPolicyTest>;

/**
 * GuardPolicyInputKind is the declared scalar or collection type of a policy
 * input. Unchanged from v1.
 *
 * @generated from enum proto.guard.policy.v2.GuardPolicyInputKind
 */
export enum GuardPolicyInputKind {
  /**
   * @generated from enum value: GUARD_POLICY_INPUT_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GUARD_POLICY_INPUT_KIND_STRING = 1;
   */
  STRING = 1,

  /**
   * @generated from enum value: GUARD_POLICY_INPUT_KIND_BOOLEAN = 2;
   */
  BOOLEAN = 2,

  /**
   * @generated from enum value: GUARD_POLICY_INPUT_KIND_INTEGER = 3;
   */
  INTEGER = 3,

  /**
   * @generated from enum value: GUARD_POLICY_INPUT_KIND_NUMBER = 4;
   */
  NUMBER = 4,

  /**
   * @generated from enum value: GUARD_POLICY_INPUT_KIND_STRING_LIST = 5;
   */
  STRING_LIST = 5,
}

/**
 * Describes the enum proto.guard.policy.v2.GuardPolicyInputKind.
 */
export declare const GuardPolicyInputKindSchema: GenEnum<GuardPolicyInputKind>;

/**
 * GuardPolicyInputExposure controls whether the raw value is evaluated and
 * retained by Arcjet or remains in SDK memory. Unchanged from v1.
 *
 * @generated from enum proto.guard.policy.v2.GuardPolicyInputExposure
 */
export enum GuardPolicyInputExposure {
  /**
   * @generated from enum value: GUARD_POLICY_INPUT_EXPOSURE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GUARD_POLICY_INPUT_EXPOSURE_SERVER = 1;
   */
  SERVER = 1,

  /**
   * @generated from enum value: GUARD_POLICY_INPUT_EXPOSURE_LOCAL = 2;
   */
  LOCAL = 2,
}

/**
 * Describes the enum proto.guard.policy.v2.GuardPolicyInputExposure.
 */
export declare const GuardPolicyInputExposureSchema: GenEnum<GuardPolicyInputExposure>;

/**
 * GuardPolicyRuleMode controls whether a denial contributes to the aggregate
 * decision. Mode is a property of the rule declaration, never of the Rego that
 * selects it.
 *
 * @generated from enum proto.guard.policy.v2.GuardPolicyRuleMode
 */
export enum GuardPolicyRuleMode {
  /**
   * @generated from enum value: GUARD_POLICY_RULE_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GUARD_POLICY_RULE_MODE_LIVE = 1;
   */
  LIVE = 1,

  /**
   * @generated from enum value: GUARD_POLICY_RULE_MODE_DRY_RUN = 2;
   */
  DRY_RUN = 2,
}

/**
 * Describes the enum proto.guard.policy.v2.GuardPolicyRuleMode.
 */
export declare const GuardPolicyRuleModeSchema: GenEnum<GuardPolicyRuleMode>;

/**
 * GuardPolicyRuleExecution identifies where a rule is evaluated.
 *
 * SDK execution is reserved for rules whose raw input must not leave SDK
 * memory. Everything else, including every Rego expression rule, is SERVER.
 *
 * @generated from enum proto.guard.policy.v2.GuardPolicyRuleExecution
 */
export enum GuardPolicyRuleExecution {
  /**
   * @generated from enum value: GUARD_POLICY_RULE_EXECUTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GUARD_POLICY_RULE_EXECUTION_SDK = 1;
   */
  SDK = 1,

  /**
   * @generated from enum value: GUARD_POLICY_RULE_EXECUTION_SERVER = 2;
   */
  SERVER = 2,
}

/**
 * Describes the enum proto.guard.policy.v2.GuardPolicyRuleExecution.
 */
export declare const GuardPolicyRuleExecutionSchema: GenEnum<GuardPolicyRuleExecution>;

/**
 * GuardPolicyRuleKind identifies what produces a rule's result.
 *
 * Detector-backed rules reuse the existing typed Guard result variants, so
 * released SDKs keep full per-rule fidelity. EXPRESSION rules are decided by
 * Rego and use an additive result variant.
 *
 * @generated from enum proto.guard.policy.v2.GuardPolicyRuleKind
 */
export enum GuardPolicyRuleKind {
  /**
   * @generated from enum value: GUARD_POLICY_RULE_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Decided by the policy's Rego expression.
   *
   * @generated from enum value: GUARD_POLICY_RULE_KIND_EXPRESSION = 1;
   */
  EXPRESSION = 1,

  /**
   * Decided directly by a declared detector, without consulting Rego.
   *
   * @generated from enum value: GUARD_POLICY_RULE_KIND_DETECTOR = 2;
   */
  DETECTOR = 2,
}

/**
 * Describes the enum proto.guard.policy.v2.GuardPolicyRuleKind.
 */
export declare const GuardPolicyRuleKindSchema: GenEnum<GuardPolicyRuleKind>;

/**
 * GuardPolicyDetectorKind identifies a native Arcjet detector.
 *
 * Detectors are native runtime operations, not Rego built-ins. Rego cannot make
 * a network or model call; it only reads the bounded result a detector produced.
 *
 * @generated from enum proto.guard.policy.v2.GuardPolicyDetectorKind
 */
export enum GuardPolicyDetectorKind {
  /**
   * @generated from enum value: GUARD_POLICY_DETECTOR_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Server-side prompt-injection detection over a SERVER STRING input.
   *
   * @generated from enum value: GUARD_POLICY_DETECTOR_KIND_PROMPT_INJECTION = 1;
   */
  PROMPT_INJECTION = 1,

  /**
   * SDK-local sensitive-information detection over a LOCAL STRING input. The
   * raw value never leaves SDK memory; the SDK sends a domain-separated
   * digest and an attested result.
   *
   * @generated from enum value: GUARD_POLICY_DETECTOR_KIND_LOCAL_SENSITIVE_INFO = 2;
   */
  LOCAL_SENSITIVE_INFO = 2,
}

/**
 * Describes the enum proto.guard.policy.v2.GuardPolicyDetectorKind.
 */
export declare const GuardPolicyDetectorKindSchema: GenEnum<GuardPolicyDetectorKind>;

/**
 * GuardPolicyBuilderOperator combines the members of a condition group.
 *
 * @generated from enum proto.guard.policy.v2.GuardPolicyBuilderOperator
 */
export enum GuardPolicyBuilderOperator {
  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_OPERATOR_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_OPERATOR_AND = 1;
   */
  AND = 1,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_OPERATOR_OR = 2;
   */
  OR = 2,
}

/**
 * Describes the enum proto.guard.policy.v2.GuardPolicyBuilderOperator.
 */
export declare const GuardPolicyBuilderOperatorSchema: GenEnum<GuardPolicyBuilderOperator>;

/**
 * GuardPolicyBuilderComparison is how a condition compares its operands.
 *
 * @generated from enum proto.guard.policy.v2.GuardPolicyBuilderComparison
 */
export enum GuardPolicyBuilderComparison {
  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_EQUALS = 1;
   */
  EQUALS = 1,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_NOT_EQUALS = 2;
   */
  NOT_EQUALS = 2,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_IN = 3;
   */
  IN = 3,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_NOT_IN = 4;
   */
  NOT_IN = 4,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_CONTAINS = 5;
   */
  CONTAINS = 5,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_STARTS_WITH = 6;
   */
  STARTS_WITH = 6,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_ENDS_WITH = 7;
   */
  ENDS_WITH = 7,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_EMAIL_DOMAIN_IS = 8;
   */
  EMAIL_DOMAIN_IS = 8,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_LENGTH_AT_LEAST = 9;
   */
  LENGTH_AT_LEAST = 9,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_LENGTH_AT_MOST = 10;
   */
  LENGTH_AT_MOST = 10,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_GREATER_THAN = 11;
   */
  GREATER_THAN = 11,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_LESS_THAN = 12;
   */
  LESS_THAN = 12,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_DETECTED = 13;
   */
  DETECTED = 13,

  /**
   * Negated string comparisons, following NOT_EQUALS and NOT_IN above rather
   * than adding a second way to express negation.
   *
   * Without these the builder cannot say "the domain is not ours", which is
   * the most common shape a real policy takes, so the author would have to
   * drop to Rego for the very first rule they write.
   *
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_NOT_CONTAINS = 14;
   */
  NOT_CONTAINS = 14,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_NOT_STARTS_WITH = 15;
   */
  NOT_STARTS_WITH = 15,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_NOT_ENDS_WITH = 16;
   */
  NOT_ENDS_WITH = 16,

  /**
   * @generated from enum value: GUARD_POLICY_BUILDER_COMPARISON_EMAIL_DOMAIN_IS_NOT = 17;
   */
  EMAIL_DOMAIN_IS_NOT = 17,
}

/**
 * Describes the enum proto.guard.policy.v2.GuardPolicyBuilderComparison.
 */
export declare const GuardPolicyBuilderComparisonSchema: GenEnum<GuardPolicyBuilderComparison>;

