/** Automatically generated - DO NOT MANUALLY EDIT */

/** Identifiers for all Well Known Bots that Arcjet can detect */
export type ArcjetWellKnownBot =
  | "A6CORP_CRAWLER"
  | "ABOUNDEX_CRAWLER"
  | "ACAPBOT"
  | "ACOON_CRAWLER"
  | "ADBEAT_CRAWLER"
  | "ADDSEARCH_CRAWLER"
  | "ADDTHIS_CRAWLER"
  | "ADMANTX_CRAWLER"
  | "ADSCANNER_CRAWLER"
  | "ADSTXTCRAWLER"
  | "ADVBOT_CRAWLER"
  | "AHREFS_CRAWLER"
  | "AI_SEARCH_BOT"
  | "AI2_CRAWLER"
  | "AI2_CRAWLER_DOLMA"
  | "AIHIT_CRAWLER"
  | "ALEXANDRIA_CRAWLER"
  | "ALPHASEOBOT_CRAWLER"
  | "AMAZON_ALEXA_CRAWLER"
  | "AMAZON_CLOUDFRONT"
  | "AMAZON_CRAWLER"
  | "ANDERSPINK_CRAWLER"
  | "ANTHROPIC_CRAWLER"
  | "ANTIBOT"
  | "APERCITE_CRAWLER"
  | "APPLE_CRAWLER"
  | "APPLE_FEEDFETCHER"
  | "ARA_CRAWLER"
  | "ARATURKA_CRAWLER"
  | "ARCHIVEORG_ARCHIVER"
  | "AROCOM_CRAWLER"
  | "ASK_CRAWLER"
  | "ASPIEGEL_CRAWLER"
  | "AUDISTO_CRAWLER"
  | "AVIRA_CRAWLER"
  | "AWARIO_CRAWLER"
  | "AWARIO_CRAWLER_RSS"
  | "AWARIO_CRAWLER_SMART"
  | "AWESOMECRAWLER"
  | "AZURE_APP_INSIGHTS"
  | "B2BBOT"
  | "BACKLINKTEST_CRAWLER"
  | "BAIDU_CLOUD_WATCH"
  | "BAIDU_CRAWLER"
  | "BAZQUX_FEEDFETCHER"
  | "BETABOT"
  | "BETTERUPTIME_MONITOR"
  | "BIDSWITCH_CRAWLER"
  | "BIGDATACORP_CRAWLER"
  | "BIGLOTRON"
  | "BING_ADS"
  | "BING_CRAWLER"
  | "BING_OFFICE_STORE"
  | "BING_PREVIEW"
  | "BINLAR"
  | "BITLY_CRAWLER"
  | "BITSIGHT_CRAWLER"
  | "BLACKBOARD_CRAWLER"
  | "BLOGMURA_CRAWLER"
  | "BLOGTRAFFIC_FEEDFETCHER"
  | "BLP_BBOT"
  | "BNF_CRAWLER"
  | "BOMBORA_CRAWLER"
  | "BOTIFY_CRAWLER"
  | "BOXCAR_CRAWLER"
  | "BRAINOBOT"
  | "BRANDONMEDIA_CRAWLER"
  | "BRANDVERITY_CRAWLER"
  | "BRANDWATCH_CRAWLER"
  | "BRIGHTEDGE_CRAWLER"
  | "BUBLUP_CRAWLER"
  | "BUILTWITH_CRAWLER"
  | "BUZZSTREAM_CRAWLER"
  | "BYTEDANCE_CRAWLER"
  | "CAPSULINK_CRAWLER"
  | "CAREERX_CRAWLER"
  | "CENTURYBOT"
  | "CHANGEDETECTION_CRAWLER"
  | "CHECKMARKNETWORK_CRAWLER"
  | "CHLOOE_CRAWLER"
  | "CINCRAWDATA_CRAWLER"
  | "CISPA_CRAWLER"
  | "CITESEERX_CRAWLER"
  | "CLICKAGY_CRAWLER"
  | "CLIQZ_CRAWLER"
  | "CLOUDFLARE_ARCHIVER"
  | "CLOUDSYSTEMNETWORKS_CRAWLER"
  | "COCCOC_CRAWLER"
  | "COCOLYZE_CRAWLER"
  | "CODA_SERVER_FETCHER"
  | "CODEWISE_CRAWLER"
  | "COGNITIVESEO_CRAWLER"
  | "COHERE_CRAWLER"
  | "COMMONCRAWL_CRAWLER"
  | "COMPANYBOOK_CRAWLER"
  | "CONDUCTOR_CRAWLER"
  | "CONTENT_CRAWLER_SPIDER"
  | "CONTEXTAD_CRAWLER"
  | "CONTXBOT"
  | "CONVERA_CRAWLER"
  | "COOKIEBOT_CRAWLER"
  | "CREATIVECOMMONS_CRAWLER"
  | "CRITEO_CRAWLER"
  | "CRYSTALSEMANTICS_CRAWLER"
  | "CUREBOT_CRAWLER"
  | "CURL"
  | "CUTBOT_CRAWLER"
  | "CXENSE_CRAWLER"
  | "CYBERPATROL_CRAWLER"
  | "DAREBOOST_CRAWLER"
  | "DATADOG_MONITOR_SYNTHETICS"
  | "DATAFEEDWATCH_CRAWLER"
  | "DATAFORSEO_CRAWLER"
  | "DATAGNION_CRAWLER"
  | "DATANYZE_CRAWLER"
  | "DATAPROVIDER_CRAWLER"
  | "DATENBUTLER_CRAWLER"
  | "DAUM_CRAWLER"
  | "DCRAWL"
  | "DEADLINKCHECKER"
  | "DEEPNOC_CRAWLER"
  | "DEUSU_CRAWLER"
  | "DIFFBOT_CRAWLER"
  | "DIGG_CRAWLER"
  | "DIGINCORE_CRAWLER"
  | "DIGITALDRAGON_CRAWLER"
  | "DISCORD_CRAWLER"
  | "DISCOVERYENGINE_CRAWLER"
  | "DISQUS_CRAWLER"
  | "DNYZ_CRAWLER"
  | "DOMAINCRAWLER_CRAWLER"
  | "DOMAINREANIMATOR_CRAWLER"
  | "DOMAINSBOT_CRAWLER"
  | "DOMAINSPROJECT_CRAWLER"
  | "DOMAINSTATS_CRAWLER"
  | "DOMAINTOOLS_CRAWLER"
  | "DOTNETDOTCOM_CRAWLER"
  | "DRAGONMETRICS_CRAWLER"
  | "DRIFTNET_CRAWLER"
  | "DUBBOT_CRAWLER"
  | "DUCKDUCKGO_CRAWLER"
  | "DUCKDUCKGO_CRAWLER_FAVICONS"
  | "DUEDIL_CRAWLER"
  | "DYNATRACE_MONITOR"
  | "EC2LINKFINDER"
  | "EDISTER_CRAWLER"
  | "ELISABOT"
  | "EMBEDLY_CRAWLER"
  | "ENTIREWEB_CRAWLER"
  | "EPFL_CRAWLER"
  | "EPICTIONS_CRAWLER"
  | "ERIGHT_CRAWLER"
  | "EUROPARCHIVE_CRAWLER"
  | "EVENTURES_CRAWLER"
  | "EVENTURES_CRAWLER_BATCH"
  | "EVERYONESOCIAL_CRAWLER"
  | "EXENSA_CRAWLER"
  | "EXPERIBOT_CRAWLER"
  | "EXTLINKS_CRAWLER"
  | "EYEOTA_CRAWLER"
  | "EZID_CRAWLER"
  | "FACEBOOK_CRAWLER"
  | "FACEBOOK_SHARE_CRAWLER"
  | "FAST_CRAWLER"
  | "FAST_CRAWLER_ENTERPRISE"
  | "FEDORAPLANET_CRAWLER"
  | "FEEDAFEVER_CRAWLER"
  | "FEEDBIN_CRAWLER"
  | "FEEDLY_FEEDFETCHER"
  | "FEEDSPOT_FEEDFETCHER"
  | "FEMTOSEARCH_CRAWLER"
  | "FINDTHATFILE_CRAWLER"
  | "FLAMINGOSEARCH_CRAWLER"
  | "FLIPBOARD_PROXY"
  | "FLUFFY"
  | "FR_CRAWLER"
  | "FREEWEBMONITORING_MONITOR"
  | "FRESHRSS_FEEDFETCHER"
  | "FRESHWORKS_MONITOR"
  | "FRIENDLYCRAWLER"
  | "FUELBOT"
  | "FYREBOT"
  | "G00G1E_CRAWLER"
  | "G2READER_CRAWLER"
  | "G2WEBSERVICES_CRAWLER"
  | "GARLIK_CRAWLER"
  | "GEEDO_CRAWLER"
  | "GEEDO_CRAWLER_PRODUCTS"
  | "GENIEO_CRAWLER"
  | "GIGABLAST_CRAWLER"
  | "GIGABLAST_CRAWLER_OSS"
  | "GINGER_CRAWLER"
  | "GLUTENFREEPLEASURE_CRAWLER"
  | "GNAM_GNAM_SPIDER"
  | "GNOWIT_CRAWLER"
  | "GO_HTTP"
  | "GOO_CRAWLER"
  | "GOOGLE_ADSBOT"
  | "GOOGLE_ADSBOT_MOBILE"
  | "GOOGLE_ADSENSE"
  | "GOOGLE_ADSENSE_GOOGLEBOT"
  | "GOOGLE_ADWORDS"
  | "GOOGLE_APPENGINE"
  | "GOOGLE_CERTIFICATES_BRIDGE"
  | "GOOGLE_CRAWLER"
  | "GOOGLE_CRAWLER_CLOUDVERTEX"
  | "GOOGLE_CRAWLER_IMAGE"
  | "GOOGLE_CRAWLER_MOBILE"
  | "GOOGLE_CRAWLER_NEWS"
  | "GOOGLE_CRAWLER_OTHER"
  | "GOOGLE_CRAWLER_SAFETY"
  | "GOOGLE_CRAWLER_STORE"
  | "GOOGLE_CRAWLER_VIDEO"
  | "GOOGLE_FAVICON"
  | "GOOGLE_FEEDFETCHER"
  | "GOOGLE_INSPECTION_TOOL"
  | "GOOGLE_LIGHTHOUSE"
  | "GOOGLE_PHYSICAL_WEB"
  | "GOOGLE_PREVIEW"
  | "GOOGLE_PUSH_NOTIFICATIONS"
  | "GOOGLE_READ_ALOUD"
  | "GOOGLE_SITE_VERIFICATION"
  | "GOOGLE_STRUCTURED_DATA_TESTING_TOOL"
  | "GOOGLE_WEB_SNIPPET"
  | "GOOGLE_XRAWLER"
  | "GOWIKI_CRAWLER"
  | "GRAPESHOT_CRAWLER"
  | "GROB_CRAWLER"
  | "GROUPHIGH_CRAWLER"
  | "GROUPME_CRAWLER"
  | "GRUB"
  | "GSLFBOT"
  | "GWENE_CRAWLER"
  | "HAOSOU_CRAWLER"
  | "HATENA_CRAWLER"
  | "HEADLESS_CHROME"
  | "HEADLINE_CRAWLER"
  | "HOYER_CRAWLER"
  | "HTTP_GET"
  | "HTTRACK"
  | "HUBSPOT_CRAWLER"
  | "HYDROZEN_MONITOR"
  | "HYPEFACTORS_CRAWLER"
  | "HYPESTAT_CRAWLER"
  | "HYSCORE_CRAWLER"
  | "IA_ARCHIVER"
  | "IASK_CRAWLER"
  | "IDEASANDCODE_CRAWLER"
  | "IFRAMELY_PREVIEW"
  | "IMAGESIFT_CRAWLER"
  | "IMESSAGE_PREVIEW"
  | "IMG2DATASET"
  | "INDEED_CRAWLER"
  | "INETDEX_CRAWLER"
  | "INFEGY_CRAWLER"
  | "INFOO_CRAWLER"
  | "INOREADER_AGGREGATOR"
  | "INTEGRALADS_CRAWLER"
  | "INTEGROMEDB_CRAWLER"
  | "INTELIUM_CRAWLER"
  | "INTERNETARCHIVE_CRAWLER_OSS"
  | "IONOS_CRAWLER"
  | "IP_WEB_CRAWLER"
  | "IPIP_CRAWLER"
  | "IRC_ARCHIVEBOT"
  | "ISKANIE_CRAWLER"
  | "ISS_CRAWLER"
  | "IT2MEDIA_CRAWLER"
  | "ITINFLUENTIALS_CRAWLER"
  | "JAMIEMBROWN_CRAWLER"
  | "JAVA_APACHE_HTTPCLIENT"
  | "JAVA_ASYNCHTTPCLIENT"
  | "JAVA_CRAWLER4J"
  | "JAVA_HTTPUNIT"
  | "JAVA_JERSEY"
  | "JAVA_JETTY"
  | "JAVA_OKHTTP"
  | "JAVA_SNACKTORY"
  | "JAVASCRIPT_AXIOS"
  | "JAVASCRIPT_NODE_FETCH"
  | "JAVASCRIPT_PHANTOM"
  | "JETSLIDE_CRAWLER"
  | "JOBBOERSE_CRAWLER"
  | "JOOBLE_CRAWLER"
  | "JUSPROG_CRAWLER"
  | "JYXO_CRAWLER"
  | "K7COMPUTING_CRAWLER"
  | "KEMVI_CRAWLER"
  | "KOMODIA_CRAWLER"
  | "KOSMIO_CRAWLER"
  | "KUMA_MONITOR"
  | "L9EXPLORE"
  | "LANDAUMEDIA_CRAWLER"
  | "LASERLIKE_CRAWLER"
  | "LAW_UNIMI_CRAWLER"
  | "LB_SPIDER"
  | "LEADCRUNCH_CRAWLER"
  | "LEIKI_CRAWLER"
  | "LEIPZIG_FINDLINKS"
  | "LEIPZIG_LCC"
  | "LEMMY_CRAWLER"
  | "LIGHTSPEEDSYSTEMS_CRAWLER"
  | "LINE_CRAWLER"
  | "LINGUEE_CRAWLER"
  | "LINKAPEDIA_CRAWLER"
  | "LINKARCHIVER"
  | "LINKDEX_CRAWLER"
  | "LINKEDIN_CRAWLER"
  | "LINKFLUENCE_CRAWLER"
  | "LINKIS_CRAWLER"
  | "LIPPERHEY_CRAWLER"
  | "LIVELAP_CRAWLER"
  | "LOGLY_CRAWLER"
  | "LOOP_CRAWLER"
  | "LSSBOT"
  | "LSSBOT_ROCKET"
  | "LTX71_CRAWLER"
  | "LUMINATOR_CRAWLER"
  | "MACOCU_CRAWLER"
  | "MAILRU_CRAWLER"
  | "MAJESTIC_CRAWLER"
  | "MAPPYDATA_CRAWLER"
  | "MARGINALIA_CRAWLER"
  | "MASTODON_CRAWLER"
  | "MAUIBOT"
  | "MEDIATOOLKIT_CRAWLER"
  | "MEGAINDEX_CRAWLER"
  | "MELTWATER_CRAWLER"
  | "META_CRAWLER"
  | "META_CRAWLER_USER"
  | "METADATALABS_CRAWLER"
  | "METAJOB_CRAWLER"
  | "METAURI_CRAWLER"
  | "METRICSTOOLS_CRAWLER"
  | "MICROSOFT_PREVIEW"
  | "MICROSOFT_RESEARCH_CRAWLER"
  | "MIGNIFY_CRAWLER"
  | "MIGNIFY_IMRBOT"
  | "MINIFLUX_FEEDFETCHER"
  | "MIXNODE_CACHE"
  | "MOAT_CRAWLER"
  | "MOJEEK_CRAWLER"
  | "MONITORBACKLINKS_CRAWLER"
  | "MONSIDO_CRAWLER"
  | "MOODLE_CRAWLER"
  | "MOREOVER_CRAWLER"
  | "MOZ_CRAWLER"
  | "MOZ_SITE_AUDIT"
  | "MSN_CRAWLER"
  | "MUCKRACK_CRAWLER"
  | "MULTIVIEWBOT"
  | "NAGIOS_CHECK_HTTP"
  | "NAVER_CRAWLER"
  | "NAVER_CRAWLER_RSS"
  | "NEEVA_CRAWLER"
  | "NERDBYNATURE_CRAWLER"
  | "NERDYBOT_CRAWLER"
  | "NETCRAFT_CRAWLER"
  | "NETESTATE_CRAWLER"
  | "NETICLE_CRAWLER"
  | "NETSYSTEMSRESEARCH_CRAWLER"
  | "NETVIBES_CRAWLER"
  | "NEWSBLUR_AGGREGATOR"
  | "NEWSHARECOUNTS_CRAWLER"
  | "NEWSPAPER"
  | "NEXTCLOUD_CRAWLER"
  | "NICECRAWLER_ARCHIVE"
  | "NICT_CRAWLER"
  | "NIKI_BOT"
  | "NING_CRAWLER"
  | "NINJABOT"
  | "NIXSTATS_CRAWLER"
  | "NMAP"
  | "NTENT_CRAWLER"
  | "NUTCH"
  | "NUZZEL_CRAWLER"
  | "OCARINABOT"
  | "OKRU_CRAWLER"
  | "OMGILI_CRAWLER"
  | "OPENAI_CRAWLER"
  | "OPENAI_CRAWLER_SEARCH"
  | "OPENAI_CRAWLER_USER"
  | "OPENGRAPHCHECK_CRAWLER"
  | "OPENHOSE_CRAWLER"
  | "OPENINDEX_CRAWLER"
  | "ORANGE_CRAWLER"
  | "ORANGE_FTGROUP_CRAWLER"
  | "OUTBRAIN_LINK_CHECKER"
  | "OUTCLICKS_CRAWLER"
  | "PAGE_TO_RSS"
  | "PAGEPEEKER_CRAWLER"
  | "PAGETHING_CRAWLER"
  | "PALOALTONETWORKS_CRAWLER"
  | "PANSCIENT_CRAWLER"
  | "PAPERLI_CRAWLER"
  | "PERL_LIBWWW"
  | "PERL_PCORE"
  | "PERPLEXITY_CRAWLER"
  | "PETALSEARCH_CRAWLER"
  | "PHP_CURLCLASS"
  | "PHP_PHPCRAWL"
  | "PHP_SIMPLE_SCRAPER"
  | "PHP_SIMPLEPIE"
  | "PHXBOT"
  | "PICSEARCH_CRAWLER"
  | "PINGDOM_CRAWLER"
  | "PINTREST_CRAWLER"
  | "PIPL_CRAWLER"
  | "POCKET_CRAWLER"
  | "POSTMAN"
  | "POSTRANK_CRAWLER"
  | "PRCY_CRAWLER"
  | "PRIMAL_CRAWLER"
  | "PRIVACORE_CRAWLER"
  | "PRIVACYAWARE_CRAWLER"
  | "PROFOUND_CRAWLER"
  | "PROXIMIC_CRAWLER"
  | "PULSEPOINT_CRAWLER"
  | "PURE_CRAWLER"
  | "PYTHON_AIOHTTP"
  | "PYTHON_BITBOT"
  | "PYTHON_HTTPX"
  | "PYTHON_OPENGRAPH"
  | "PYTHON_REQUESTS"
  | "PYTHON_SCRAPY"
  | "PYTHON_URLLIB"
  | "QWANT_CRAWLER"
  | "RANKACTIVE_CRAWLER"
  | "REDDIT_CRAWLER"
  | "REFIND_CRAWLER"
  | "RETREVO_PAGE_ANALYZER"
  | "RIDDER_CRAWLER"
  | "RIVVA_CRAWLER"
  | "RSSBOT_FEEDFETCHER"
  | "RSSING_CRAWLER"
  | "RSSMICRO_FEEDFETCHER"
  | "RUBY_METAINSPECTOR"
  | "RYTE_CRAWLER"
  | "SAFEDNS_CRAWLER"
  | "SCAN_INTERFAX_CRAWLER"
  | "SCHMORP_CRAWLER"
  | "SCOUTJET_CRAWLER"
  | "SCREAMINGFROG_CRAWLER"
  | "SCRIBD_CRAWLER"
  | "SCRITCH_CRAWLER"
  | "SEARCHATLAS_CRAWLER"
  | "SEEKBOT_CRAWLER"
  | "SEEKPORT_CRAWLER"
  | "SEEWITHKIDS_CRAWLER"
  | "SEMANTICAUDIENCE_CRAWLER"
  | "SEMANTICSCHOLAR_CRAWLER"
  | "SEMPITECH_CRAWLER"
  | "SEMRUSH_CRAWLER"
  | "SENTIONE_CRAWLER"
  | "SENTRY_CRAWLER"
  | "SENUTO_CRAWLER"
  | "SEOBILITY_CRAWLER"
  | "SEOKICKS_CRAWLER"
  | "SEOLIZER_CRAWLER"
  | "SEOPROFILER_CRAWLER"
  | "SEOSCANNERS_CRAWLER"
  | "SEOSTAR_CRAWLER"
  | "SEOZOOM_CRAWLER"
  | "SERENDEPUTY_CRAWLER"
  | "SERPSTATBOT_CRAWLER"
  | "SEZNAM_CRAWLER"
  | "SIMILARTECH_CRAWLER"
  | "SIMPLE_CRAWLER"
  | "SISTRIX_007AC9_CRAWLER"
  | "SISTRIX_CRAWLER"
  | "SITEBOT_CRAWLER"
  | "SITECHECKER_CRAWLER"
  | "SITEEXPLORER_CRAWLER"
  | "SITEIMPROVE_CRAWLER"
  | "SKYPE_PREVIEW"
  | "SLACK_CRAWLER"
  | "SLACK_IMAGE_PROXY"
  | "SNAP_PREVIEW"
  | "SOCIALRANK_CRAWLER"
  | "SOFTBYTELABS_CRAWLER"
  | "SOGOU_CRAWLER"
  | "STARTME_CRAWLER"
  | "STEAM_PREVIEW"
  | "STORYGIZE_CRAWLER"
  | "STRACT_CRAWLER"
  | "STRIPE_WEBHOOK"
  | "STUTTGART_CRAWLER"
  | "SUMMALY_CRAWLER"
  | "SUMMIFY_CRAWLER"
  | "SUPERFEEDR_CRAWLER"
  | "SURLY_CRAWLER"
  | "SWIMGBOT"
  | "SYNAPSE_CRAWLER"
  | "SYSOMOS_CRAWLER"
  | "T3VERSIONS_CRAWLER"
  | "TABOOLA_CRAWLER"
  | "TAGOO_CRAWLER"
  | "TANGIBLEE_CRAWLER"
  | "TELEGRAM_CRAWLER"
  | "TESTOMATO_CRAWLER"
  | "THEOLDREADER_CRAWLER"
  | "THINKLAB_CRAWLER"
  | "TIGER_CRAWLER"
  | "TIKTOK_CRAWLER"
  | "TIMPI_CRAWLER"
  | "TINEYE_CRAWLER"
  | "TISCALI_CRAWLER"
  | "TOMBASCRAPER_CRAWLER"
  | "TOPLIST_CRAWLER"
  | "TORUS_CRAWLER"
  | "TOUTIAO_CRAWLER"
  | "TRAACKR_CRAWLER"
  | "TRACEMYFILE_CRAWLER"
  | "TRENDICTION_CRAWLER"
  | "TRENDSMAP_CRAWLER"
  | "TROVE_CRAWLER"
  | "TROVIT_CRAWLER"
  | "TTRSS_FEEDFETCHER"
  | "TURNITIN_CRAWLER"
  | "TWEETEDTIMES_CRAWLER"
  | "TWEETMEMEBOT"
  | "TWENGA_CRAWLER"
  | "TWINGLY_CRAWLER"
  | "TWITTER_CRAWLER"
  | "TWOIP_CRAWLER"
  | "TWOIP_CRAWLER_CMS"
  | "TWURLY_CRAWLER"
  | "UBERMETRICS_CRAWLER"
  | "UBT_CRAWLER"
  | "UPFLOW_CRAWLER"
  | "UPTIME_MONITOR"
  | "UPTIMEBOT_MONITOR"
  | "UPTIMEROBOT_MONITOR"
  | "URLCLASSIFICATION_CRAWLER"
  | "USINE_NOUVELLE_CRAWLER"
  | "UTEXAS_CRAWLER"
  | "UTORRENT_CRAWLER"
  | "VEBIDOO_CRAWLER"
  | "VELEN_CRAWLER"
  | "VEOOZ_CRAWLER"
  | "VERCEL_CRAWLER"
  | "VERCEL_MONITOR_PREVIEW"
  | "VERISIGN_IPS_AGENT"
  | "VIBER_CRAWLER"
  | "VIGIL_CRAWLER"
  | "VIPNYTT_CRAWLER"
  | "VIRUSTOTAL_CRAWLER"
  | "VKROBOT_CRAWLER"
  | "VKSHARE_CRAWLER"
  | "VUHUV_CRAWLER"
  | "W3C_VALIDATOR_CSS"
  | "W3C_VALIDATOR_FEED"
  | "W3C_VALIDATOR_HTML"
  | "W3C_VALIDATOR_HTML_NU"
  | "W3C_VALIDATOR_I18N"
  | "W3C_VALIDATOR_LINKS"
  | "W3C_VALIDATOR_MOBILE"
  | "W3C_VALIDATOR_UNIFIED"
  | "WAREBAY_CRAWLER"
  | "WEBARCHIVE_CRAWLER"
  | "WEBCEO_CRAWLER"
  | "WEBCOMPANY_CRAWLER"
  | "WEBDATASTATS_CRAWLER"
  | "WEBEAVER_CRAWLER"
  | "WEBMEUP_CRAWLER"
  | "WEBMON"
  | "WEBPAGETEST_CRAWLER"
  | "WEBZIO_CRAWLER"
  | "WEBZIO_CRAWLER_AI"
  | "WELLKNOWN_CRAWLER"
  | "WESEE_CRAWLER"
  | "WGET"
  | "WHATSAPP_CRAWLER"
  | "WOCODI_CRAWLER"
  | "WOORANK_CRAWLER"
  | "WOORANK_CRAWLER_REVIEW"
  | "WORDPRESS_CRAWLER"
  | "WORDPRESS_CRAWLER_RSS"
  | "WORDUP_CRAWLER"
  | "WORIO_CRAWLER"
  | "WOTBOX_CRAWLER"
  | "XENU_CRAWLER"
  | "XOVIBOT_CRAWLER"
  | "YACY_CRAWLER"
  | "YAHOO_CRAWLER"
  | "YAHOO_CRAWLER_JAPAN"
  | "YAHOO_PREVIEW"
  | "YAMANALAB_CRAWLER"
  | "YANDEX_CRAWLER"
  | "YANDEX_CRAWLER_JAVASCRIPT"
  | "YANGA_CRAWLER"
  | "YELLOWBP_CRAWLER"
  | "YISOU_CRAWLER"
  | "YOOZ_CRAWLER"
  | "YOU_CRAWLER"
  | "ZABBIX_MONITOR"
  | "ZGRAB"
  | "ZOOMINFO_CRAWLER"
  | "ZUM_CRAWLER"
  | "ZUPERLIST_CRAWLER";

export type ArcjetBotCategory =
  | "CATEGORY:ACADEMIC"
  | "CATEGORY:ADVERTISING"
  | "CATEGORY:AI"
  | "CATEGORY:AMAZON"
  | "CATEGORY:APPLE"
  | "CATEGORY:ARCHIVE"
  | "CATEGORY:FEEDFETCHER"
  | "CATEGORY:GOOGLE"
  | "CATEGORY:META"
  | "CATEGORY:MICROSOFT"
  | "CATEGORY:MONITOR"
  | "CATEGORY:OPTIMIZER"
  | "CATEGORY:PREVIEW"
  | "CATEGORY:PROGRAMMATIC"
  | "CATEGORY:SEARCH_ENGINE"
  | "CATEGORY:SLACK"
  | "CATEGORY:SOCIAL"
  | "CATEGORY:TOOL"
  | "CATEGORY:UNKNOWN"
  | "CATEGORY:VERCEL"
  | "CATEGORY:WEBHOOK"
  | "CATEGORY:YAHOO";

export const categories: Record<
  ArcjetBotCategory,
  readonly ArcjetWellKnownBot[]
> = Object.freeze({
  "CATEGORY:ACADEMIC": Object.freeze<ArcjetWellKnownBot[]>([
    "BLACKBOARD_CRAWLER",
    "CISPA_CRAWLER",
    "COMMONCRAWL_CRAWLER",
    "DOMAINSPROJECT_CRAWLER",
    "EPFL_CRAWLER",
    "EZID_CRAWLER",
    "LAW_UNIMI_CRAWLER",
    "LEIPZIG_FINDLINKS",
    "LEIPZIG_LCC",
    "MACOCU_CRAWLER",
    "NICT_CRAWLER",
    "SEMANTICSCHOLAR_CRAWLER",
    "TURNITIN_CRAWLER",
    "UTEXAS_CRAWLER",
    "YAMANALAB_CRAWLER",
  ]),
  "CATEGORY:ADVERTISING": Object.freeze<ArcjetWellKnownBot[]>([
    "BING_ADS",
    "GOOGLE_ADSBOT",
    "GOOGLE_ADSBOT_MOBILE",
    "GOOGLE_ADSENSE",
    "GOOGLE_ADSENSE_GOOGLEBOT",
    "GOOGLE_ADWORDS",
    "MOAT_CRAWLER",
    "MSN_CRAWLER",
  ]),
  "CATEGORY:AI": Object.freeze<ArcjetWellKnownBot[]>([
    "AI_SEARCH_BOT",
    "AI2_CRAWLER",
    "AI2_CRAWLER_DOLMA",
    "AIHIT_CRAWLER",
    "ANTHROPIC_CRAWLER",
    "BOTIFY_CRAWLER",
    "BYTEDANCE_CRAWLER",
    "COHERE_CRAWLER",
    "COMMONCRAWL_CRAWLER",
    "DIFFBOT_CRAWLER",
    "FACEBOOK_CRAWLER",
    "FACEBOOK_SHARE_CRAWLER",
    "FRIENDLYCRAWLER",
    "GLUTENFREEPLEASURE_CRAWLER",
    "GOOGLE_CRAWLER_CLOUDVERTEX",
    "IASK_CRAWLER",
    "IMAGESIFT_CRAWLER",
    "IMG2DATASET",
    "INFEGY_CRAWLER",
    "INTEGRALADS_CRAWLER",
    "LEADCRUNCH_CRAWLER",
    "MEDIATOOLKIT_CRAWLER",
    "META_CRAWLER",
    "META_CRAWLER_USER",
    "NICT_CRAWLER",
    "NTENT_CRAWLER",
    "OMGILI_CRAWLER",
    "OPENAI_CRAWLER",
    "OPENAI_CRAWLER_SEARCH",
    "OPENAI_CRAWLER_USER",
    "PERPLEXITY_CRAWLER",
    "PETALSEARCH_CRAWLER",
    "PRIMAL_CRAWLER",
    "PYTHON_SCRAPY",
    "SAFEDNS_CRAWLER",
    "SEARCHATLAS_CRAWLER",
    "SEMANTICSCHOLAR_CRAWLER",
    "SENTIONE_CRAWLER",
    "STORYGIZE_CRAWLER",
    "TIKTOK_CRAWLER",
    "TIMPI_CRAWLER",
    "TURNITIN_CRAWLER",
    "VELEN_CRAWLER",
    "WEBZIO_CRAWLER_AI",
    "YOU_CRAWLER",
  ]),
  "CATEGORY:AMAZON": Object.freeze<ArcjetWellKnownBot[]>([
    "AMAZON_ALEXA_CRAWLER",
    "AMAZON_CLOUDFRONT",
    "AMAZON_CRAWLER",
  ]),
  "CATEGORY:APPLE": Object.freeze<ArcjetWellKnownBot[]>([
    "APPLE_CRAWLER",
    "IMESSAGE_PREVIEW",
  ]),
  "CATEGORY:ARCHIVE": Object.freeze<ArcjetWellKnownBot[]>([
    "ARCHIVEORG_ARCHIVER",
    "CLOUDFLARE_ARCHIVER",
    "COMMONCRAWL_CRAWLER",
    "EZID_CRAWLER",
    "INTERNETARCHIVE_CRAWLER_OSS",
    "IRC_ARCHIVEBOT",
    "LINKARCHIVER",
    "NICECRAWLER_ARCHIVE",
    "TRENDSMAP_CRAWLER",
    "WEBARCHIVE_CRAWLER",
  ]),
  "CATEGORY:FEEDFETCHER": Object.freeze<ArcjetWellKnownBot[]>([
    "APPLE_FEEDFETCHER",
    "AWARIO_CRAWLER_RSS",
    "BAZQUX_FEEDFETCHER",
    "BLOGTRAFFIC_FEEDFETCHER",
    "FEEDBIN_CRAWLER",
    "FEEDLY_FEEDFETCHER",
    "FEEDSPOT_FEEDFETCHER",
    "FRESHRSS_FEEDFETCHER",
    "G2READER_CRAWLER",
    "GOOGLE_FEEDFETCHER",
    "INOREADER_AGGREGATOR",
    "MINIFLUX_FEEDFETCHER",
    "NAVER_CRAWLER_RSS",
    "NEWSBLUR_AGGREGATOR",
    "POCKET_CRAWLER",
    "REFIND_CRAWLER",
    "RSSBOT_FEEDFETCHER",
    "RSSING_CRAWLER",
    "RSSMICRO_FEEDFETCHER",
    "SERENDEPUTY_CRAWLER",
    "STARTME_CRAWLER",
    "SUPERFEEDR_CRAWLER",
    "THEOLDREADER_CRAWLER",
    "TTRSS_FEEDFETCHER",
    "WORDPRESS_CRAWLER_RSS",
  ]),
  "CATEGORY:GOOGLE": Object.freeze<ArcjetWellKnownBot[]>([
    "GOOGLE_ADSBOT",
    "GOOGLE_ADSBOT_MOBILE",
    "GOOGLE_ADSENSE",
    "GOOGLE_ADSENSE_GOOGLEBOT",
    "GOOGLE_ADWORDS",
    "GOOGLE_APPENGINE",
    "GOOGLE_CERTIFICATES_BRIDGE",
    "GOOGLE_CRAWLER",
    "GOOGLE_CRAWLER_CLOUDVERTEX",
    "GOOGLE_CRAWLER_IMAGE",
    "GOOGLE_CRAWLER_MOBILE",
    "GOOGLE_CRAWLER_NEWS",
    "GOOGLE_CRAWLER_OTHER",
    "GOOGLE_CRAWLER_SAFETY",
    "GOOGLE_CRAWLER_STORE",
    "GOOGLE_CRAWLER_VIDEO",
    "GOOGLE_FAVICON",
    "GOOGLE_FEEDFETCHER",
    "GOOGLE_INSPECTION_TOOL",
    "GOOGLE_LIGHTHOUSE",
    "GOOGLE_PHYSICAL_WEB",
    "GOOGLE_PREVIEW",
    "GOOGLE_PUSH_NOTIFICATIONS",
    "GOOGLE_READ_ALOUD",
    "GOOGLE_SITE_VERIFICATION",
    "GOOGLE_STRUCTURED_DATA_TESTING_TOOL",
    "GOOGLE_WEB_SNIPPET",
    "GOOGLE_XRAWLER",
  ]),
  "CATEGORY:META": Object.freeze<ArcjetWellKnownBot[]>([
    "FACEBOOK_CRAWLER",
    "FACEBOOK_SHARE_CRAWLER",
    "META_CRAWLER",
    "META_CRAWLER_USER",
    "WHATSAPP_CRAWLER",
  ]),
  "CATEGORY:MICROSOFT": Object.freeze<ArcjetWellKnownBot[]>([
    "AZURE_APP_INSIGHTS",
    "BING_ADS",
    "BING_CRAWLER",
    "BING_OFFICE_STORE",
    "BING_PREVIEW",
    "MICROSOFT_PREVIEW",
    "MICROSOFT_RESEARCH_CRAWLER",
    "MSN_CRAWLER",
    "SKYPE_PREVIEW",
  ]),
  "CATEGORY:MONITOR": Object.freeze<ArcjetWellKnownBot[]>([
    "AZURE_APP_INSIGHTS",
    "BETTERUPTIME_MONITOR",
    "BRANDVERITY_CRAWLER",
    "CHANGEDETECTION_CRAWLER",
    "DATADOG_MONITOR_SYNTHETICS",
    "DEADLINKCHECKER",
    "DISQUS_CRAWLER",
    "DUBBOT_CRAWLER",
    "DYNATRACE_MONITOR",
    "FLIPBOARD_PROXY",
    "FREEWEBMONITORING_MONITOR",
    "FRESHWORKS_MONITOR",
    "GOOGLE_CERTIFICATES_BRIDGE",
    "GOOGLE_SITE_VERIFICATION",
    "GOOGLE_STRUCTURED_DATA_TESTING_TOOL",
    "HUBSPOT_CRAWLER",
    "HYDROZEN_MONITOR",
    "KUMA_MONITOR",
    "MONITORBACKLINKS_CRAWLER",
    "NIXSTATS_CRAWLER",
    "OUTBRAIN_LINK_CHECKER",
    "PAGEPEEKER_CRAWLER",
    "PINGDOM_CRAWLER",
    "SAFEDNS_CRAWLER",
    "SENTRY_CRAWLER",
    "SURLY_CRAWLER",
    "TESTOMATO_CRAWLER",
    "UPTIME_MONITOR",
    "UPTIMEBOT_MONITOR",
    "UPTIMEROBOT_MONITOR",
    "VERCEL_MONITOR_PREVIEW",
    "W3C_VALIDATOR_CSS",
    "W3C_VALIDATOR_FEED",
    "W3C_VALIDATOR_HTML",
    "W3C_VALIDATOR_HTML_NU",
    "W3C_VALIDATOR_I18N",
    "W3C_VALIDATOR_LINKS",
    "W3C_VALIDATOR_MOBILE",
    "W3C_VALIDATOR_UNIFIED",
    "WEBPAGETEST_CRAWLER",
    "XENU_CRAWLER",
    "ZABBIX_MONITOR",
  ]),
  "CATEGORY:OPTIMIZER": Object.freeze<ArcjetWellKnownBot[]>([
    "CONDUCTOR_CRAWLER",
    "DAREBOOST_CRAWLER",
    "DUBBOT_CRAWLER",
    "GOOGLE_LIGHTHOUSE",
    "GOOGLE_STRUCTURED_DATA_TESTING_TOOL",
    "MONSIDO_CRAWLER",
    "MOZ_SITE_AUDIT",
    "SCREAMINGFROG_CRAWLER",
    "SISTRIX_CRAWLER",
    "TESTOMATO_CRAWLER",
    "WEBPAGETEST_CRAWLER",
  ]),
  "CATEGORY:PREVIEW": Object.freeze<ArcjetWellKnownBot[]>([
    "BING_PREVIEW",
    "BITLY_CRAWLER",
    "DISCORD_CRAWLER",
    "DUCKDUCKGO_CRAWLER_FAVICONS",
    "EMBEDLY_CRAWLER",
    "FACEBOOK_SHARE_CRAWLER",
    "FLIPBOARD_PROXY",
    "GOOGLE_FAVICON",
    "GOOGLE_PREVIEW",
    "GOOGLE_WEB_SNIPPET",
    "IFRAMELY_PREVIEW",
    "IMESSAGE_PREVIEW",
    "MASTODON_CRAWLER",
    "META_CRAWLER_USER",
    "MICROSOFT_PREVIEW",
    "PAGEPEEKER_CRAWLER",
    "SKYPE_PREVIEW",
    "SLACK_IMAGE_PROXY",
    "SNAP_PREVIEW",
    "STEAM_PREVIEW",
    "SYNAPSE_CRAWLER",
    "TELEGRAM_CRAWLER",
    "TWITTER_CRAWLER",
    "VERCEL_MONITOR_PREVIEW",
    "VIBER_CRAWLER",
    "WHATSAPP_CRAWLER",
    "YAHOO_PREVIEW",
  ]),
  "CATEGORY:PROGRAMMATIC": Object.freeze<ArcjetWellKnownBot[]>([
    "CODA_SERVER_FETCHER",
    "GIGABLAST_CRAWLER_OSS",
    "GO_HTTP",
    "GOOGLE_APPENGINE",
    "GOWIKI_CRAWLER",
    "HTTP_GET",
    "JAVA_APACHE_HTTPCLIENT",
    "JAVA_ASYNCHTTPCLIENT",
    "JAVA_CRAWLER4J",
    "JAVA_HTTPUNIT",
    "JAVA_JERSEY",
    "JAVA_JETTY",
    "JAVA_OKHTTP",
    "JAVA_SNACKTORY",
    "JAVASCRIPT_AXIOS",
    "JAVASCRIPT_NODE_FETCH",
    "JAVASCRIPT_PHANTOM",
    "PERL_LIBWWW",
    "PERL_PCORE",
    "PHP_CURLCLASS",
    "PHP_PHPCRAWL",
    "PHP_SIMPLE_SCRAPER",
    "PHP_SIMPLEPIE",
    "PYTHON_AIOHTTP",
    "PYTHON_BITBOT",
    "PYTHON_HTTPX",
    "PYTHON_OPENGRAPH",
    "PYTHON_REQUESTS",
    "PYTHON_SCRAPY",
    "PYTHON_URLLIB",
    "RUBY_METAINSPECTOR",
  ]),
  "CATEGORY:SEARCH_ENGINE": Object.freeze<ArcjetWellKnownBot[]>([
    "ADDSEARCH_CRAWLER",
    "AHREFS_CRAWLER",
    "ALEXANDRIA_CRAWLER",
    "APPLE_CRAWLER",
    "ASK_CRAWLER",
    "AVIRA_CRAWLER",
    "BING_CRAWLER",
    "BING_OFFICE_STORE",
    "DUCKDUCKGO_CRAWLER",
    "DUCKDUCKGO_CRAWLER_FAVICONS",
    "ENTIREWEB_CRAWLER",
    "GEEDO_CRAWLER",
    "GEEDO_CRAWLER_PRODUCTS",
    "GOOGLE_CRAWLER",
    "GOOGLE_CRAWLER_IMAGE",
    "GOOGLE_CRAWLER_MOBILE",
    "GOOGLE_CRAWLER_NEWS",
    "GOOGLE_CRAWLER_OTHER",
    "GOOGLE_CRAWLER_STORE",
    "GOOGLE_CRAWLER_VIDEO",
    "GOOGLE_INSPECTION_TOOL",
    "IASK_CRAWLER",
    "LINGUEE_CRAWLER",
    "MAJESTIC_CRAWLER",
    "MARGINALIA_CRAWLER",
    "MOJEEK_CRAWLER",
    "NETESTATE_CRAWLER",
    "OPENAI_CRAWLER_SEARCH",
    "PETALSEARCH_CRAWLER",
    "PIPL_CRAWLER",
    "QWANT_CRAWLER",
    "SEEKPORT_CRAWLER",
    "STRACT_CRAWLER",
    "WEBZIO_CRAWLER",
    "WELLKNOWN_CRAWLER",
    "YACY_CRAWLER",
    "YAHOO_CRAWLER",
    "YANDEX_CRAWLER",
    "YANDEX_CRAWLER_JAVASCRIPT",
  ]),
  "CATEGORY:SLACK": Object.freeze<ArcjetWellKnownBot[]>([
    "SLACK_CRAWLER",
    "SLACK_IMAGE_PROXY",
  ]),
  "CATEGORY:SOCIAL": Object.freeze<ArcjetWellKnownBot[]>([
    "DIGG_CRAWLER",
    "DISCORD_CRAWLER",
    "EVERYONESOCIAL_CRAWLER",
    "FACEBOOK_CRAWLER",
    "FACEBOOK_SHARE_CRAWLER",
    "GOOGLE_PREVIEW",
    "GOOGLE_WEB_SNIPPET",
    "GROUPME_CRAWLER",
    "IFRAMELY_PREVIEW",
    "IMESSAGE_PREVIEW",
    "IRC_ARCHIVEBOT",
    "LEMMY_CRAWLER",
    "LINKARCHIVER",
    "LINKEDIN_CRAWLER",
    "MASTODON_CRAWLER",
    "NETICLE_CRAWLER",
    "PINTREST_CRAWLER",
    "REDDIT_CRAWLER",
    "SNAP_PREVIEW",
    "STEAM_PREVIEW",
    "SYNAPSE_CRAWLER",
    "TELEGRAM_CRAWLER",
    "TIKTOK_CRAWLER",
    "TRENDSMAP_CRAWLER",
    "TWEETEDTIMES_CRAWLER",
    "TWITTER_CRAWLER",
    "VIBER_CRAWLER",
    "WHATSAPP_CRAWLER",
  ]),
  "CATEGORY:TOOL": Object.freeze<ArcjetWellKnownBot[]>([
    "CURL",
    "DCRAWL",
    "DOMAINSPROJECT_CRAWLER",
    "GIGABLAST_CRAWLER_OSS",
    "HEADLESS_CHROME",
    "IMG2DATASET",
    "INTERNETARCHIVE_CRAWLER_OSS",
    "IPIP_CRAWLER",
    "L9EXPLORE",
    "LAW_UNIMI_CRAWLER",
    "NAGIOS_CHECK_HTTP",
    "NMAP",
    "NUTCH",
    "POSTMAN",
    "SUMMALY_CRAWLER",
    "WGET",
    "XENU_CRAWLER",
    "ZGRAB",
  ]),
  "CATEGORY:UNKNOWN": Object.freeze<ArcjetWellKnownBot[]>([
    "A6CORP_CRAWLER",
    "ABOUNDEX_CRAWLER",
    "ACAPBOT",
    "ACOON_CRAWLER",
    "ADBEAT_CRAWLER",
    "ADDTHIS_CRAWLER",
    "ADMANTX_CRAWLER",
    "ADSCANNER_CRAWLER",
    "ADSTXTCRAWLER",
    "ADVBOT_CRAWLER",
    "ALPHASEOBOT_CRAWLER",
    "ANDERSPINK_CRAWLER",
    "ANTIBOT",
    "APERCITE_CRAWLER",
    "ARA_CRAWLER",
    "ARATURKA_CRAWLER",
    "AROCOM_CRAWLER",
    "ASPIEGEL_CRAWLER",
    "AUDISTO_CRAWLER",
    "AWARIO_CRAWLER",
    "AWARIO_CRAWLER_SMART",
    "AWESOMECRAWLER",
    "B2BBOT",
    "BACKLINKTEST_CRAWLER",
    "BAIDU_CLOUD_WATCH",
    "BAIDU_CRAWLER",
    "BETABOT",
    "BIDSWITCH_CRAWLER",
    "BIGDATACORP_CRAWLER",
    "BIGLOTRON",
    "BINLAR",
    "BITSIGHT_CRAWLER",
    "BLOGMURA_CRAWLER",
    "BLP_BBOT",
    "BNF_CRAWLER",
    "BOMBORA_CRAWLER",
    "BOXCAR_CRAWLER",
    "BRAINOBOT",
    "BRANDONMEDIA_CRAWLER",
    "BRANDWATCH_CRAWLER",
    "BRIGHTEDGE_CRAWLER",
    "BUBLUP_CRAWLER",
    "BUILTWITH_CRAWLER",
    "BUZZSTREAM_CRAWLER",
    "CAPSULINK_CRAWLER",
    "CAREERX_CRAWLER",
    "CENTURYBOT",
    "CHECKMARKNETWORK_CRAWLER",
    "CHLOOE_CRAWLER",
    "CINCRAWDATA_CRAWLER",
    "CITESEERX_CRAWLER",
    "CLICKAGY_CRAWLER",
    "CLIQZ_CRAWLER",
    "CLOUDSYSTEMNETWORKS_CRAWLER",
    "COCCOC_CRAWLER",
    "COCOLYZE_CRAWLER",
    "CODEWISE_CRAWLER",
    "COGNITIVESEO_CRAWLER",
    "COMPANYBOOK_CRAWLER",
    "CONTENT_CRAWLER_SPIDER",
    "CONTEXTAD_CRAWLER",
    "CONTXBOT",
    "CONVERA_CRAWLER",
    "COOKIEBOT_CRAWLER",
    "CREATIVECOMMONS_CRAWLER",
    "CRITEO_CRAWLER",
    "CRYSTALSEMANTICS_CRAWLER",
    "CUREBOT_CRAWLER",
    "CUTBOT_CRAWLER",
    "CXENSE_CRAWLER",
    "CYBERPATROL_CRAWLER",
    "DATAFEEDWATCH_CRAWLER",
    "DATAFORSEO_CRAWLER",
    "DATAGNION_CRAWLER",
    "DATANYZE_CRAWLER",
    "DATAPROVIDER_CRAWLER",
    "DATENBUTLER_CRAWLER",
    "DAUM_CRAWLER",
    "DEEPNOC_CRAWLER",
    "DEUSU_CRAWLER",
    "DIGINCORE_CRAWLER",
    "DIGITALDRAGON_CRAWLER",
    "DISCOVERYENGINE_CRAWLER",
    "DNYZ_CRAWLER",
    "DOMAINCRAWLER_CRAWLER",
    "DOMAINREANIMATOR_CRAWLER",
    "DOMAINSBOT_CRAWLER",
    "DOMAINSTATS_CRAWLER",
    "DOMAINTOOLS_CRAWLER",
    "DOTNETDOTCOM_CRAWLER",
    "DRAGONMETRICS_CRAWLER",
    "DRIFTNET_CRAWLER",
    "DUEDIL_CRAWLER",
    "EC2LINKFINDER",
    "EDISTER_CRAWLER",
    "ELISABOT",
    "EPICTIONS_CRAWLER",
    "ERIGHT_CRAWLER",
    "EUROPARCHIVE_CRAWLER",
    "EVENTURES_CRAWLER",
    "EVENTURES_CRAWLER_BATCH",
    "EXENSA_CRAWLER",
    "EXPERIBOT_CRAWLER",
    "EXTLINKS_CRAWLER",
    "EYEOTA_CRAWLER",
    "FAST_CRAWLER",
    "FAST_CRAWLER_ENTERPRISE",
    "FEDORAPLANET_CRAWLER",
    "FEEDAFEVER_CRAWLER",
    "FEMTOSEARCH_CRAWLER",
    "FINDTHATFILE_CRAWLER",
    "FLAMINGOSEARCH_CRAWLER",
    "FLUFFY",
    "FR_CRAWLER",
    "FUELBOT",
    "FYREBOT",
    "G00G1E_CRAWLER",
    "G2WEBSERVICES_CRAWLER",
    "GARLIK_CRAWLER",
    "GENIEO_CRAWLER",
    "GIGABLAST_CRAWLER",
    "GINGER_CRAWLER",
    "GNAM_GNAM_SPIDER",
    "GNOWIT_CRAWLER",
    "GOO_CRAWLER",
    "GRAPESHOT_CRAWLER",
    "GROB_CRAWLER",
    "GROUPHIGH_CRAWLER",
    "GRUB",
    "GSLFBOT",
    "GWENE_CRAWLER",
    "HAOSOU_CRAWLER",
    "HATENA_CRAWLER",
    "HEADLINE_CRAWLER",
    "HOYER_CRAWLER",
    "HTTRACK",
    "HYPEFACTORS_CRAWLER",
    "HYPESTAT_CRAWLER",
    "HYSCORE_CRAWLER",
    "IA_ARCHIVER",
    "IDEASANDCODE_CRAWLER",
    "INDEED_CRAWLER",
    "INETDEX_CRAWLER",
    "INFOO_CRAWLER",
    "INTEGROMEDB_CRAWLER",
    "INTELIUM_CRAWLER",
    "IONOS_CRAWLER",
    "IP_WEB_CRAWLER",
    "ISKANIE_CRAWLER",
    "ISS_CRAWLER",
    "IT2MEDIA_CRAWLER",
    "ITINFLUENTIALS_CRAWLER",
    "JAMIEMBROWN_CRAWLER",
    "JETSLIDE_CRAWLER",
    "JOBBOERSE_CRAWLER",
    "JOOBLE_CRAWLER",
    "JUSPROG_CRAWLER",
    "JYXO_CRAWLER",
    "K7COMPUTING_CRAWLER",
    "KEMVI_CRAWLER",
    "KOMODIA_CRAWLER",
    "KOSMIO_CRAWLER",
    "LANDAUMEDIA_CRAWLER",
    "LASERLIKE_CRAWLER",
    "LB_SPIDER",
    "LEIKI_CRAWLER",
    "LIGHTSPEEDSYSTEMS_CRAWLER",
    "LINE_CRAWLER",
    "LINKAPEDIA_CRAWLER",
    "LINKDEX_CRAWLER",
    "LINKFLUENCE_CRAWLER",
    "LINKIS_CRAWLER",
    "LIPPERHEY_CRAWLER",
    "LIVELAP_CRAWLER",
    "LOGLY_CRAWLER",
    "LOOP_CRAWLER",
    "LSSBOT",
    "LSSBOT_ROCKET",
    "LTX71_CRAWLER",
    "LUMINATOR_CRAWLER",
    "MAILRU_CRAWLER",
    "MAPPYDATA_CRAWLER",
    "MAUIBOT",
    "MEGAINDEX_CRAWLER",
    "MELTWATER_CRAWLER",
    "METADATALABS_CRAWLER",
    "METAJOB_CRAWLER",
    "METAURI_CRAWLER",
    "METRICSTOOLS_CRAWLER",
    "MIGNIFY_CRAWLER",
    "MIGNIFY_IMRBOT",
    "MIXNODE_CACHE",
    "MOODLE_CRAWLER",
    "MOREOVER_CRAWLER",
    "MOZ_CRAWLER",
    "MUCKRACK_CRAWLER",
    "MULTIVIEWBOT",
    "NAVER_CRAWLER",
    "NEEVA_CRAWLER",
    "NERDBYNATURE_CRAWLER",
    "NERDYBOT_CRAWLER",
    "NETCRAFT_CRAWLER",
    "NETSYSTEMSRESEARCH_CRAWLER",
    "NETVIBES_CRAWLER",
    "NEWSHARECOUNTS_CRAWLER",
    "NEWSPAPER",
    "NEXTCLOUD_CRAWLER",
    "NIKI_BOT",
    "NING_CRAWLER",
    "NINJABOT",
    "NUZZEL_CRAWLER",
    "OCARINABOT",
    "OKRU_CRAWLER",
    "OPENGRAPHCHECK_CRAWLER",
    "OPENHOSE_CRAWLER",
    "OPENINDEX_CRAWLER",
    "ORANGE_CRAWLER",
    "ORANGE_FTGROUP_CRAWLER",
    "OUTCLICKS_CRAWLER",
    "PAGE_TO_RSS",
    "PAGETHING_CRAWLER",
    "PALOALTONETWORKS_CRAWLER",
    "PANSCIENT_CRAWLER",
    "PAPERLI_CRAWLER",
    "PHXBOT",
    "PICSEARCH_CRAWLER",
    "POSTRANK_CRAWLER",
    "PRCY_CRAWLER",
    "PRIVACORE_CRAWLER",
    "PRIVACYAWARE_CRAWLER",
    "PROFOUND_CRAWLER",
    "PROXIMIC_CRAWLER",
    "PULSEPOINT_CRAWLER",
    "PURE_CRAWLER",
    "RANKACTIVE_CRAWLER",
    "RETREVO_PAGE_ANALYZER",
    "RIDDER_CRAWLER",
    "RIVVA_CRAWLER",
    "RYTE_CRAWLER",
    "SCAN_INTERFAX_CRAWLER",
    "SCHMORP_CRAWLER",
    "SCOUTJET_CRAWLER",
    "SCRIBD_CRAWLER",
    "SCRITCH_CRAWLER",
    "SEEKBOT_CRAWLER",
    "SEEWITHKIDS_CRAWLER",
    "SEMANTICAUDIENCE_CRAWLER",
    "SEMPITECH_CRAWLER",
    "SEMRUSH_CRAWLER",
    "SENUTO_CRAWLER",
    "SEOBILITY_CRAWLER",
    "SEOKICKS_CRAWLER",
    "SEOLIZER_CRAWLER",
    "SEOPROFILER_CRAWLER",
    "SEOSCANNERS_CRAWLER",
    "SEOSTAR_CRAWLER",
    "SEOZOOM_CRAWLER",
    "SERPSTATBOT_CRAWLER",
    "SEZNAM_CRAWLER",
    "SIMILARTECH_CRAWLER",
    "SIMPLE_CRAWLER",
    "SISTRIX_007AC9_CRAWLER",
    "SITEBOT_CRAWLER",
    "SITECHECKER_CRAWLER",
    "SITEEXPLORER_CRAWLER",
    "SITEIMPROVE_CRAWLER",
    "SOCIALRANK_CRAWLER",
    "SOFTBYTELABS_CRAWLER",
    "SOGOU_CRAWLER",
    "STUTTGART_CRAWLER",
    "SUMMIFY_CRAWLER",
    "SWIMGBOT",
    "SYSOMOS_CRAWLER",
    "T3VERSIONS_CRAWLER",
    "TABOOLA_CRAWLER",
    "TAGOO_CRAWLER",
    "TANGIBLEE_CRAWLER",
    "THINKLAB_CRAWLER",
    "TIGER_CRAWLER",
    "TINEYE_CRAWLER",
    "TISCALI_CRAWLER",
    "TOMBASCRAPER_CRAWLER",
    "TOPLIST_CRAWLER",
    "TORUS_CRAWLER",
    "TOUTIAO_CRAWLER",
    "TRAACKR_CRAWLER",
    "TRACEMYFILE_CRAWLER",
    "TRENDICTION_CRAWLER",
    "TROVE_CRAWLER",
    "TROVIT_CRAWLER",
    "TWEETMEMEBOT",
    "TWENGA_CRAWLER",
    "TWINGLY_CRAWLER",
    "TWOIP_CRAWLER",
    "TWOIP_CRAWLER_CMS",
    "TWURLY_CRAWLER",
    "UBERMETRICS_CRAWLER",
    "UBT_CRAWLER",
    "UPFLOW_CRAWLER",
    "URLCLASSIFICATION_CRAWLER",
    "USINE_NOUVELLE_CRAWLER",
    "UTORRENT_CRAWLER",
    "VEBIDOO_CRAWLER",
    "VEOOZ_CRAWLER",
    "VERISIGN_IPS_AGENT",
    "VIGIL_CRAWLER",
    "VIPNYTT_CRAWLER",
    "VIRUSTOTAL_CRAWLER",
    "VKROBOT_CRAWLER",
    "VKSHARE_CRAWLER",
    "VUHUV_CRAWLER",
    "WAREBAY_CRAWLER",
    "WEBCEO_CRAWLER",
    "WEBCOMPANY_CRAWLER",
    "WEBDATASTATS_CRAWLER",
    "WEBEAVER_CRAWLER",
    "WEBMEUP_CRAWLER",
    "WEBMON",
    "WESEE_CRAWLER",
    "WOCODI_CRAWLER",
    "WOORANK_CRAWLER",
    "WOORANK_CRAWLER_REVIEW",
    "WORDPRESS_CRAWLER",
    "WORDUP_CRAWLER",
    "WORIO_CRAWLER",
    "WOTBOX_CRAWLER",
    "XOVIBOT_CRAWLER",
    "YANGA_CRAWLER",
    "YELLOWBP_CRAWLER",
    "YISOU_CRAWLER",
    "YOOZ_CRAWLER",
    "ZOOMINFO_CRAWLER",
    "ZUM_CRAWLER",
    "ZUPERLIST_CRAWLER",
  ]),
  "CATEGORY:VERCEL": Object.freeze<ArcjetWellKnownBot[]>([
    "VERCEL_CRAWLER",
    "VERCEL_MONITOR_PREVIEW",
  ]),
  "CATEGORY:WEBHOOK": Object.freeze<ArcjetWellKnownBot[]>([
    "STRIPE_WEBHOOK",
  ]),
  "CATEGORY:YAHOO": Object.freeze<ArcjetWellKnownBot[]>([
    "YAHOO_CRAWLER",
    "YAHOO_CRAWLER_JAPAN",
    "YAHOO_PREVIEW",
  ]),
});
