import fs from "node:fs";
import { globSync, readFileSync } from "node:fs";
import { isBuiltin } from "node:module";

import { defineConfig } from "rolldown";
import { dts } from "rolldown-plugin-dts";

import pkg from "./package.json" with { type: "json" };

const dependencies = Object.keys(pkg.dependencies ?? {});
const devDependencies = Object.keys(pkg.devDependencies ?? {});
const peerDependencies = Object.keys(pkg.peerDependencies ?? {});

function generateJs(wasm: Buffer): string {
  const disclaimer = `
/**
 * This file contains an Arcjet Wasm binary inlined as a base64
 * [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs)
 * with the application/wasm MIME type.
 *
 * This was chosen to save on storage space over inlining the file directly as
 * a Uint8Array, which would take up ~3x the space of the Wasm file. See
 * https://blobfolio.com/2019/better-binary-batter-mixing-base64-and-uint8array/
 * for more details.
 *
 * It is then decoded into an ArrayBuffer to be used directly via WebAssembly's
 * \`compile()\` function in our entry point file.
 *
 * This is all done to avoid trying to read or bundle the Wasm asset in various
 * ways based on the platform or bundler a user is targeting. One example being
 * that Next.js requires special \`asyncWebAssembly\` webpack config to load our
 * Wasm file if we don't do this.
 *
 * In the future, we hope to do away with this workaround when all bundlers
 * properly support consistent asset bundling techniques.
 */
`;

  return `// @generated by wasm2module - DO NOT EDIT
/* eslint-disable */
// @ts-nocheck
${disclaimer}
const wasmBase64 = "data:application/wasm;base64,${wasm.toString("base64")}";
/**
 * Returns a WebAssembly.Module for an Arcjet Wasm binary, decoded from a base64
 * Data URL.
 */
// TODO: Switch back to top-level await when our platforms all support it
export async function wasm() {
  // This uses fetch to decode the wasm data url, but disabling cache so files
  // larger than 2mb don't fail to parse in the Next.js App Router
  const wasmDecode = await fetch(wasmBase64, { cache: "no-store" });
  const buf = await wasmDecode.arrayBuffer();
  // And then we return it as a WebAssembly.Module
  return WebAssembly.compile(buf);
}
`;
}

function wasmToModule(): import("rolldown").Plugin {
  const idToWasmPath = new Map<string, string>();
  return {
    name: "base64-wasm",
    resolveId(source) {
      if (source.endsWith(".wasm?js")) {
        const filepath = source.slice(0, -3);
        const id = `\0${filepath.replace(/\.wasm$/, ".js")}`;
        idToWasmPath.set(id, filepath);
        return id;
      }
      return null;
    },
    async load(id) {
      const wasmPath = idToWasmPath.get(id);
      if (wasmPath) {
        const wasm = await fs.promises.readFile(wasmPath);
        return generateJs(wasm);
      }
      return null;
    },
  };
}

const input = [
  ...globSync("*.ts", { exclude: ["*.d.ts", "*.config.ts"] }),
  ...globSync("test/**/*.ts"),
];

export default defineConfig({
  input,
  plugins: [
    {
      name: "externalize-wasm",
      resolveId(id) {
        if (id.endsWith(".wasm") || id.endsWith(".wasm?module")) {
          return { id, external: true };
        }
        // Externalize jco-generated component files to prevent dts plugin
        // from overwriting the jco-generated .d.ts declarations
        if (id.includes("/wasm/") && id.endsWith(".js")) {
          return { id, external: true };
        }
        return null;
      },
    },
    wasmToModule(),
    dts(),
  ],
  output: {
    dir: ".",
    format: "esm",
    preserveModules: true,
  },
  platform: "neutral",
  tsconfig: "./tsconfig.json",
  external(id: string): boolean {
    return (
      isBuiltin(id) ||
      dependencies.some((dep) => id.startsWith(dep)) ||
      devDependencies.some((dep) => id.startsWith(dep)) ||
      peerDependencies.some((dep) => id.startsWith(dep))
    );
  },
});
