/** Automatically generated - DO NOT MANUALLY EDIT */

/** Identifiers for all Well Known Bots that Arcjet can detect */
export type ArcjetWellKnownBot =
  | "A6CORP_CRAWLER"
  | "AASA_BOT"
  | "ABEVAL_BOT"
  | "ABOUNDEX_CRAWLER"
  | "ACADEMICBOT_RTU"
  | "ACAPBOT"
  | "ACOON_CRAWLER"
  | "ADAGIO_CRAWLER"
  | "ADBEAT_CRAWLER"
  | "ADDSEARCH_CRAWLER"
  | "ADDTHIS_CRAWLER"
  | "ADMANTX_CRAWLER"
  | "ADSCANNER_CRAWLER"
  | "ADSTXTCRAWLER"
  | "ADVBOT_CRAWLER"
  | "ADYEN_WEBHOOK"
  | "AGENTTESLA_BOTNET"
  | "AHREFS_CRAWLER"
  | "AHREFS_SITE_AUDIT"
  | "AI_SEARCH_BOT"
  | "AI2_CRAWLER"
  | "AI2_CRAWLER_DOLMA"
  | "AIHIT_CRAWLER"
  | "ALERTSITE_MONITOR"
  | "ALEXANDRIA_CRAWLER"
  | "ALGOLIA_CRAWLER"
  | "ALPHASEOBOT_CRAWLER"
  | "AMADEY_BOTNET"
  | "AMAZON_ADBOT"
  | "AMAZON_ALEXA_CRAWLER"
  | "AMAZON_BEDROCK_AGENTCORE_BROWSER"
  | "AMAZON_CLOUDFRONT"
  | "AMAZON_CRAWLER"
  | "AMAZON_PRODUCT_DISCOVERY"
  | "AMAZON_ROUTE53_HEALTH_CHECK"
  | "AMAZON_SEARCHBOT"
  | "AMAZON_SELLER_INITIATED_LISTING"
  | "AMAZON_USER"
  | "ANDERSPINK_CRAWLER"
  | "ANOMURA_CRAWLER"
  | "ANTHROPIC_AI"
  | "ANTHROPIC_CRAWLER"
  | "ANTHROPIC_CRAWLER_SEARCH"
  | "ANTHROPIC_CRAWLER_USER"
  | "ANTIBOT"
  | "APERCITE_CRAWLER"
  | "APIFY_BOT"
  | "APPLE_CRAWLER"
  | "APPLE_FEEDFETCHER"
  | "ARA_CRAWLER"
  | "ARANEA_CRAWLER"
  | "ARATURKA_CRAWLER"
  | "ARCHIVE_IT"
  | "ARCHIVEBOX"
  | "ARCHIVEORG_ARCHIVER"
  | "AROCOM_CRAWLER"
  | "ARTEMIS_WEB_READER"
  | "ASK_CRAWLER"
  | "ASPIEGEL_CRAWLER"
  | "ATLASSIAN_BOT"
  | "AUDIGENT_ADBOT"
  | "AUDISTO_CRAWLER"
  | "AVIRA_CRAWLER"
  | "AWARIO_CRAWLER"
  | "AWARIO_CRAWLER_RSS"
  | "AWARIO_CRAWLER_SMART"
  | "AWESOMECRAWLER"
  | "AZURE_AI_SEARCHBOT"
  | "AZURE_APP_INSIGHTS"
  | "B2BBOT"
  | "BACKLINKTEST_CRAWLER"
  | "BAIDU_CLOUD_WATCH"
  | "BAIDU_CRAWLER"
  | "BANKER_BOTNET"
  | "BAZQUX_FEEDFETCHER"
  | "BETABOT"
  | "BETTERSTACK_MONITOR"
  | "BETTERUPTIME_MONITOR"
  | "BIDSWITCH_CRAWLER"
  | "BIGDATACORP_CRAWLER"
  | "BIGLOTRON"
  | "BING_ADS"
  | "BING_CRAWLER"
  | "BING_OFFICE_STORE"
  | "BING_PREVIEW"
  | "BINLAR"
  | "BITLY_CRAWLER"
  | "BITSIGHT_CRAWLER"
  | "BLACK_BOTNET"
  | "BLACKBOARD_CRAWLER"
  | "BLOGMURA_CRAWLER"
  | "BLOGTRAFFIC_FEEDFETCHER"
  | "BLP_BBOT"
  | "BLUESKY_PREVIEW"
  | "BNF_CRAWLER"
  | "BOMBORA_CRAWLER"
  | "BOTIFY_CRAWLER"
  | "BOXCAR_CRAWLER"
  | "BRAINOBOT"
  | "BRANDONMEDIA_CRAWLER"
  | "BRANDVERITY_CRAWLER"
  | "BRANDWATCH_CRAWLER"
  | "BRIGHTBOT"
  | "BRIGHTEDGE_CRAWLER"
  | "BUBLUP_CRAWLER"
  | "BUFFER_LINK_PREVIEW"
  | "BUILTWITH_CRAWLER"
  | "BUZZSTREAM_CRAWLER"
  | "BYOB_BOTNET"
  | "BYTEDANCE_CRAWLER"
  | "CAPSULINK_CRAWLER"
  | "CARBON_UMBRELLA_BOT"
  | "CAREERX_CRAWLER"
  | "CCBOT_CRAWLER"
  | "CENSYS_INSPECT"
  | "CENTURYBOT"
  | "CHANGEDETECTION_CRAWLER"
  | "CHANNEL3_BOT"
  | "CHECKLY_MONITOR"
  | "CHECKMARKNETWORK_CRAWLER"
  | "CHLOOE_CRAWLER"
  | "CINCRAWDATA_CRAWLER"
  | "CISPA_CRAWLER"
  | "CITESEERX_CRAWLER"
  | "CLARITY_BOT"
  | "CLASSLA_WEB_CRAWLER"
  | "CLICKAGY_CRAWLER"
  | "CLIQZ_CRAWLER"
  | "CLOUDFLARE_AI_SEARCH"
  | "CLOUDFLARE_ARCHIVER"
  | "CLOUDFLARE_HEALTHCHECKS"
  | "CLOUDFLARE_PREFETCH"
  | "CLOUDFLARE_SECURITY_CENTER"
  | "CLOUDFLARE_SSL_DETECTOR"
  | "CLOUDFLARE_TRAFFIC_MANAGER"
  | "CLOUDSYSTEMNETWORKS_CRAWLER"
  | "COCCOC_CRAWLER"
  | "COCOLYZE_CRAWLER"
  | "CODA_SERVER_FETCHER"
  | "CODEWISE_CRAWLER"
  | "COGNITIVESEO_CRAWLER"
  | "COHERE_CRAWLER"
  | "COMMONCRAWL_CRAWLER"
  | "COMPANYBOOK_CRAWLER"
  | "CONDUCTOR_CRAWLER"
  | "CONTENT_CRAWLER_SPIDER"
  | "CONTEXTAD_CRAWLER"
  | "CONTXBOT"
  | "CONVERA_CRAWLER"
  | "COOKIEBOT_CRAWLER"
  | "COOKIEHUB_SCAN"
  | "COTOYOGI_CRAWLER"
  | "CRAWL4AI"
  | "CRAWLSPACE"
  | "CREATIVECOMMONS_CRAWLER"
  | "CRITEO_CRAWLER"
  | "CRUSTY_CRAWLER"
  | "CRYSTALSEMANTICS_CRAWLER"
  | "CUREBOT_CRAWLER"
  | "CURL"
  | "CUTBOT_CRAWLER"
  | "CXENSE_CRAWLER"
  | "CYBAA_BOT"
  | "CYBERPATROL_CRAWLER"
  | "CYPRESS"
  | "DAREBOOST_CRAWLER"
  | "DATADOG_MONITOR_SYNTHETICS"
  | "DATAFEEDWATCH_CRAWLER"
  | "DATAFORSEO_CRAWLER"
  | "DATAGNION_CRAWLER"
  | "DATANYZE_CRAWLER"
  | "DATAPROVIDER_CRAWLER"
  | "DATENBUTLER_CRAWLER"
  | "DAUM_CRAWLER"
  | "DAZZLE_BLUESKY_BOT"
  | "DCRAWL"
  | "DEADLINKCHECKER"
  | "DEEPNOC_CRAWLER"
  | "DESKYO_BOT"
  | "DEUSU_CRAWLER"
  | "DIFFBOT_CRAWLER"
  | "DIGG_CRAWLER"
  | "DIGINCORE_CRAWLER"
  | "DIGITALDRAGON_CRAWLER"
  | "DISCORD_CRAWLER"
  | "DISCOURSE_ONEBOX"
  | "DISCOVERYENGINE_CRAWLER"
  | "DISQUS_CRAWLER"
  | "DNYZ_CRAWLER"
  | "DOMAINCRAWLER_CRAWLER"
  | "DOMAINREANIMATOR_CRAWLER"
  | "DOMAINSBOT_CRAWLER"
  | "DOMAINSPROJECT_CRAWLER"
  | "DOMAINSTATS_CRAWLER"
  | "DOMAINTOOLS_CRAWLER"
  | "DOMCOP_BOT"
  | "DONUTMATE_BOTNET"
  | "DOTNETDOTCOM_CRAWLER"
  | "DRAGONMETRICS_CRAWLER"
  | "DRIFTNET_CRAWLER"
  | "DUBBOT_CRAWLER"
  | "DUCKASSIST_BOT"
  | "DUCKDUCKGO_CRAWLER"
  | "DUCKDUCKGO_CRAWLER_FAVICONS"
  | "DUEDIL_CRAWLER"
  | "DYNATRACE_MONITOR"
  | "EASYCRON_MONITOR"
  | "EC2LINKFINDER"
  | "EDGEWATCH_MONITOR"
  | "EDISTER_CRAWLER"
  | "ELISABOT"
  | "EMBEDLY_CRAWLER"
  | "ENTIREWEB_CRAWLER"
  | "EPFL_CRAWLER"
  | "EPICTIONS_CRAWLER"
  | "EREPUBLIK_TOOLS_CRAWLER"
  | "ERIGHT_CRAWLER"
  | "EUROPARCHIVE_CRAWLER"
  | "EVENTURES_CRAWLER"
  | "EVENTURES_CRAWLER_BATCH"
  | "EVERYONESOCIAL_CRAWLER"
  | "EXA_SEARCHBOT"
  | "EXENSA_CRAWLER"
  | "EXODUS_MOVEMENT_CRAWLER"
  | "EXPERIBOT_CRAWLER"
  | "EXTLINKS_CRAWLER"
  | "EYEOTA_CRAWLER"
  | "EZID_CRAWLER"
  | "EZOIC_BOT"
  | "FACEBOOK_CATALOG"
  | "FACEBOOK_CRAWLER"
  | "FACEBOOK_SHARE_CRAWLER"
  | "FAST_CRAWLER"
  | "FAST_CRAWLER_ENTERPRISE"
  | "FASTMAIL_PREVIEW"
  | "FEDICA_BOT"
  | "FEDISTATS_CRAWLER"
  | "FEDORAPLANET_CRAWLER"
  | "FEDREPORTER_BOT"
  | "FEEDAFEVER_CRAWLER"
  | "FEEDBIN_CRAWLER"
  | "FEEDBURNER"
  | "FEEDER_CO"
  | "FEEDLY_FEEDFETCHER"
  | "FEEDSPOT_FEEDFETCHER"
  | "FEEDWIND"
  | "FEMTOSEARCH_CRAWLER"
  | "FINDFILES_CRAWLER"
  | "FINDTHATFILE_CRAWLER"
  | "FIRECRAWL_AGENT"
  | "FLAMINGOSEARCH_CRAWLER"
  | "FLEEBS_BOT"
  | "FLIPBOARD_PROXY"
  | "FLUFFY"
  | "FLYRIVER_BOT"
  | "FR_CRAWLER"
  | "FREESPOKE_CRAWLER"
  | "FREEWEBMONITORING_MONITOR"
  | "FRESHRSS_FEEDFETCHER"
  | "FRESHWORKS_MONITOR"
  | "FRIENDLYCRAWLER"
  | "FUELBOT"
  | "FYREBOT"
  | "G00G1E_CRAWLER"
  | "G2READER_CRAWLER"
  | "G2WEBSERVICES_CRAWLER"
  | "GAFGYT_BOTNET"
  | "GARLIK_CRAWLER"
  | "GEEDO_CRAWLER"
  | "GEEDO_CRAWLER_PRODUCTS"
  | "GEEDO_CRAWLER_SHOP"
  | "GENIEO_CRAWLER"
  | "GHOST_INSPECTOR"
  | "GIGABLAST_CRAWLER"
  | "GIGABLAST_CRAWLER_OSS"
  | "GINGER_CRAWLER"
  | "GITHUB_CAMO"
  | "GLUTENFREEPLEASURE_CRAWLER"
  | "GNAM_GNAM_SPIDER"
  | "GNOWIT_CRAWLER"
  | "GO_HTTP"
  | "GOO_CRAWLER"
  | "GOOGLE_ADS_CONVERSIONS"
  | "GOOGLE_ADSBOT"
  | "GOOGLE_ADSBOT_MOBILE"
  | "GOOGLE_ADSENSE"
  | "GOOGLE_ADSENSE_GOOGLEBOT"
  | "GOOGLE_ADWORDS"
  | "GOOGLE_AGENT"
  | "GOOGLE_APPENGINE"
  | "GOOGLE_APPS_SCRIPT"
  | "GOOGLE_ASSOCIATION_SERVICE"
  | "GOOGLE_CERTIFICATES_BRIDGE"
  | "GOOGLE_CRAWLER"
  | "GOOGLE_CRAWLER_CLOUDVERTEX"
  | "GOOGLE_CRAWLER_IMAGE"
  | "GOOGLE_CRAWLER_MOBILE"
  | "GOOGLE_CRAWLER_NEWS"
  | "GOOGLE_CRAWLER_OTHER"
  | "GOOGLE_CRAWLER_SAFETY"
  | "GOOGLE_CRAWLER_STORE"
  | "GOOGLE_CRAWLER_VIDEO"
  | "GOOGLE_CWS"
  | "GOOGLE_FAVICON"
  | "GOOGLE_FEEDFETCHER"
  | "GOOGLE_GEMINI_DEEP_RESEARCH"
  | "GOOGLE_GEMINI_NOTEBOOK"
  | "GOOGLE_IMAGE_PROXY"
  | "GOOGLE_INSPECTION_TOOL"
  | "GOOGLE_LIGHTHOUSE"
  | "GOOGLE_MESSAGES"
  | "GOOGLE_PHYSICAL_WEB"
  | "GOOGLE_PINPOINT"
  | "GOOGLE_PREVIEW"
  | "GOOGLE_PRODUCER"
  | "GOOGLE_PUSH_NOTIFICATIONS"
  | "GOOGLE_READ_ALOUD"
  | "GOOGLE_SITE_VERIFICATION"
  | "GOOGLE_STACKDRIVER_MONITORING"
  | "GOOGLE_STRUCTURED_DATA_TESTING_TOOL"
  | "GOOGLE_WEB_SNIPPET"
  | "GOOGLE_XRAWLER"
  | "GOPARSER_BOT"
  | "GOT"
  | "GOWIKI_CRAWLER"
  | "GRAFANA_SYNTHETIC_MONITORING_AGENT"
  | "GRAPESHOT_CRAWLER"
  | "GROB_CRAWLER"
  | "GROUPHIGH_CRAWLER"
  | "GROUPME_CRAWLER"
  | "GRUB"
  | "GSLFBOT"
  | "GTMETRIX_MONITOR"
  | "GULOADER_BOTNET"
  | "GWENE_CRAWLER"
  | "HAJIME_BOTNET"
  | "HANALEI_BOT"
  | "HAOSOU_CRAWLER"
  | "HATENA_CRAWLER"
  | "HCARD_VALIDATOR"
  | "HEADLESS_CHROME"
  | "HEADLINE_CRAWLER"
  | "HETRIXTOOLS_MONITOR"
  | "HLIDAM_ROBOT"
  | "HONEYBADGER_BOT"
  | "HOYER_CRAWLER"
  | "HTTP_GET"
  | "HTTPIE"
  | "HTTRACK"
  | "HUBSPOT_CRAWLER"
  | "HYDROZEN_MONITOR"
  | "HYPEFACTORS_CRAWLER"
  | "HYPESTAT_CRAWLER"
  | "HYSCORE_CRAWLER"
  | "IA_ARCHIVER"
  | "IASK_CRAWLER"
  | "IBOU_BOT"
  | "IDEASANDCODE_CRAWLER"
  | "IFRAMELY_PREVIEW"
  | "IMAGESIFT_CRAWLER"
  | "IMAGESPIDER"
  | "IMESSAGE_PREVIEW"
  | "IMG2DATASET"
  | "INDEED_CRAWLER"
  | "INETDEX_CRAWLER"
  | "INFEGY_CRAWLER"
  | "INFOO_CRAWLER"
  | "INNGUMA_FETCHER"
  | "INOREADER_AGGREGATOR"
  | "INSTAPAPER"
  | "INTEGRALADS_CRAWLER"
  | "INTEGROMEDB_CRAWLER"
  | "INTELIUM_CRAWLER"
  | "INTERNETARCHIVE_CRAWLER_OSS"
  | "IONOS_CRAWLER"
  | "IP_WEB_CRAWLER"
  | "IPIP_CRAWLER"
  | "IRC_ARCHIVEBOT"
  | "ISKANIE_CRAWLER"
  | "ISS_CRAWLER"
  | "IT2MEDIA_CRAWLER"
  | "ITINFLUENTIALS_CRAWLER"
  | "JAMIEMBROWN_CRAWLER"
  | "JAVA_APACHE_HTTPCLIENT"
  | "JAVA_ASYNCHTTPCLIENT"
  | "JAVA_CRAWLER4J"
  | "JAVA_HTTPUNIT"
  | "JAVA_JERSEY"
  | "JAVA_JETTY"
  | "JAVA_OKHTTP"
  | "JAVA_SNACKTORY"
  | "JAVASCRIPT_AXIOS"
  | "JAVASCRIPT_NODE_FETCH"
  | "JAVASCRIPT_PHANTOM"
  | "JETPACK_MONITOR"
  | "JETSLIDE_CRAWLER"
  | "JOBBOERSE_CRAWLER"
  | "JOBSWITHGPT_BOT"
  | "JOOBLE_CRAWLER"
  | "JUSPROG_CRAWLER"
  | "JYXO_CRAWLER"
  | "K7COMPUTING_CRAWLER"
  | "KAGI_CRAWLER"
  | "KAGI_FETCHER"
  | "KEMVI_CRAWLER"
  | "KEYBASE_BOT"
  | "KIMI_BOT"
  | "KIMI_SEARCHBOT"
  | "KIMI_USER"
  | "KINSING_BOTNET"
  | "KOMODIA_CRAWLER"
  | "KOSMIO_CRAWLER"
  | "KUMA_MONITOR"
  | "L9EXPLORE"
  | "LAION_HUGGINGFACE_PROCESSOR"
  | "LANDAUMEDIA_CRAWLER"
  | "LASERLIKE_CRAWLER"
  | "LAW_UNIMI_CRAWLER"
  | "LB_SPIDER"
  | "LEADCRUNCH_CRAWLER"
  | "LEIKI_CRAWLER"
  | "LEIPZIG_FINDLINKS"
  | "LEIPZIG_LCC"
  | "LEMMY_CRAWLER"
  | "LIGHTSPEEDSYSTEMS_CRAWLER"
  | "LINE_CRAWLER"
  | "LINGUEE_CRAWLER"
  | "LINKAPEDIA_CRAWLER"
  | "LINKARCHIVER"
  | "LINKCHECKER_PRO"
  | "LINKDEX_CRAWLER"
  | "LINKEDIN_CRAWLER"
  | "LINKFLUENCE_CRAWLER"
  | "LINKIS_CRAWLER"
  | "LINKSINDEXER_BOT"
  | "LINKUP_BOT"
  | "LIPPERHEY_CRAWLER"
  | "LISTGEM_BOT"
  | "LIVELAP_CRAWLER"
  | "LOGLY_CRAWLER"
  | "LOOP_CRAWLER"
  | "LSSBOT"
  | "LSSBOT_ROCKET"
  | "LTX71_CRAWLER"
  | "LUMINATOR_CRAWLER"
  | "LYONL_CRAWLER"
  | "MACOCU_CRAWLER"
  | "MADB_BOT"
  | "MAGNET_ME_CRAWLER"
  | "MAILRU_CRAWLER"
  | "MAJESTIC_CRAWLER"
  | "MAPPYDATA_CRAWLER"
  | "MARGINALIA_CRAWLER"
  | "MASTODON_CRAWLER"
  | "MAUIBOT"
  | "MCONTEXTUAL_BOT"
  | "MEDIA_MONITORING_BOT"
  | "MEDIATOOLKIT_CRAWLER"
  | "MEGAINDEX_CRAWLER"
  | "MELTWATER_CRAWLER"
  | "META_CRAWLER"
  | "META_CRAWLER_USER"
  | "META_EXTERNALADS"
  | "META_EXTERNALHIT"
  | "META_WEBINDEXER"
  | "METADATALABS_CRAWLER"
  | "METAJOB_CRAWLER"
  | "METAURI_CRAWLER"
  | "METRICSTOOLS_CRAWLER"
  | "MICROSOFT_PREVIEW"
  | "MICROSOFT_RESEARCH_CRAWLER"
  | "MIGNIFY_CRAWLER"
  | "MIGNIFY_IMRBOT"
  | "MINIFLUX_FEEDFETCHER"
  | "MIRAI_BOTNET"
  | "MISTRAL_AI_INDEX"
  | "MISTRAL_AI_TRAINING"
  | "MISTRAL_AI_USER"
  | "MIXNODE_CACHE"
  | "MIXRANK_BOT"
  | "MOAT_CRAWLER"
  | "MOJEEK_CRAWLER"
  | "MONITORBACKLINKS_CRAWLER"
  | "MONSIDO_CRAWLER"
  | "MONTASTIC_MONITOR"
  | "MOOBOT_BOTNET"
  | "MOODLE_CRAWLER"
  | "MOREOVER_CRAWLER"
  | "MOTOMINER_BOT"
  | "MOZ_CRAWLER"
  | "MOZ_SITE_AUDIT"
  | "MOZI_BOTNET"
  | "MOZILLA_TABSTACK"
  | "MSN_CRAWLER"
  | "MUCKRACK_CRAWLER"
  | "MULTIVIEWBOT"
  | "NAGIOS_CHECK_HTTP"
  | "NANOINTERACTIVE_CRAWLER"
  | "NAVER_BOT"
  | "NAVER_CRAWLER"
  | "NAVER_CRAWLER_RSS"
  | "NEEVA_CRAWLER"
  | "NERDBYNATURE_CRAWLER"
  | "NERDYBOT_CRAWLER"
  | "NESTDADDY_BOT"
  | "NETCRAFT_CRAWLER"
  | "NETESTATE_CRAWLER"
  | "NETICLE_CRAWLER"
  | "NETSEER_CRAWLER"
  | "NETSYSTEMSRESEARCH_CRAWLER"
  | "NETVIBES_CRAWLER"
  | "NEWRELIC_MONITOR"
  | "NEWSAI"
  | "NEWSBLUR_AGGREGATOR"
  | "NEWSHARECOUNTS_CRAWLER"
  | "NEWSPAPER"
  | "NEXTCLOUD_CRAWLER"
  | "NICECRAWLER_ARCHIVE"
  | "NICT_CRAWLER"
  | "NIKI_BOT"
  | "NING_CRAWLER"
  | "NINJABOT"
  | "NITRO_BOT"
  | "NIXSTATS_CRAWLER"
  | "NMAP"
  | "NOAH_BOT"
  | "NTENT_CRAWLER"
  | "NUTCH"
  | "NUZZEL_CRAWLER"
  | "OBSERVEPOINT_MONITOR"
  | "OCARINABOT"
  | "OKRU_CRAWLER"
  | "OMGILI_CRAWLER"
  | "ONCRAWL"
  | "OPENAI_CRAWLER"
  | "OPENAI_CRAWLER_SEARCH"
  | "OPENAI_CRAWLER_USER"
  | "OPENGRAPHCHECK_CRAWLER"
  | "OPENHOSE_CRAWLER"
  | "OPENINDEX_CRAWLER"
  | "OPENTHEBOX_BOT"
  | "ORANGE_CRAWLER"
  | "ORANGE_FTGROUP_CRAWLER"
  | "OUTBRAIN_LINK_CHECKER"
  | "OUTCLICKS_CRAWLER"
  | "PAGE_TO_RSS"
  | "PAGEPEEKER_CRAWLER"
  | "PAGETHING_CRAWLER"
  | "PALOALTONETWORKS_CRAWLER"
  | "PANSCIENT_CRAWLER"
  | "PAPERLI_CRAWLER"
  | "PAQLE_BOT"
  | "PERL_LIBWWW"
  | "PERL_PCORE"
  | "PERPLEXITY_CRAWLER"
  | "PERPLEXITY_USER"
  | "PETALSEARCH_CRAWLER"
  | "PHIND_BOT"
  | "PHP_CURLCLASS"
  | "PHP_PHPCRAWL"
  | "PHP_SIMPLE_SCRAPER"
  | "PHP_SIMPLEPIE"
  | "PHXBOT"
  | "PICSEARCH_CRAWLER"
  | "PINGDOM_CRAWLER"
  | "PINTEREST_CRAWLER"
  | "PINTREST_CRAWLER"
  | "PIPL_CRAWLER"
  | "PLAGAWARE_BOT"
  | "POCKET_CRAWLER"
  | "PODUPTIME"
  | "POMOTHY_BOT"
  | "POSTMAN"
  | "POSTRANK_CRAWLER"
  | "PRCY_CRAWLER"
  | "PRIMAL_CRAWLER"
  | "PRIVACORE_CRAWLER"
  | "PRIVACYAWARE_CRAWLER"
  | "PRODUCTSUP_CRAWLER"
  | "PROFOUND_CRAWLER"
  | "PROXIMIC_CRAWLER"
  | "PRTG_MONITOR"
  | "PULSEPOINT_CRAWLER"
  | "PURE_CRAWLER"
  | "PYTHON_AIOHTTP"
  | "PYTHON_BITBOT"
  | "PYTHON_HTTPX"
  | "PYTHON_OPENGRAPH"
  | "PYTHON_REQUESTS"
  | "PYTHON_SCRAPY"
  | "PYTHON_URLLIB"
  | "QUALIFIED_BOT"
  | "QUANTCAST_CRAWLER"
  | "QWANT_CRAWLER"
  | "RAKUTEN_USA_IMAGE_BOT"
  | "RANKACTIVE_CRAWLER"
  | "REDDIT_CRAWLER"
  | "REFIND_CRAWLER"
  | "REMCOSRAT_BOTNET"
  | "REPO_LOOKOUT_BOT"
  | "RETREVO_PAGE_ANALYZER"
  | "RETROLISTE_CRAWLER"
  | "RIDDER_CRAWLER"
  | "RIVVA_CRAWLER"
  | "RSSBOT_FEEDFETCHER"
  | "RSSING_CRAWLER"
  | "RSSMICRO_FEEDFETCHER"
  | "RUBY_METAINSPECTOR"
  | "RYTE_CRAWLER"
  | "SAFEDNS_CRAWLER"
  | "SBINTUITIONS_BOT"
  | "SCAN_INTERFAX_CRAWLER"
  | "SCHMORP_CRAWLER"
  | "SCOPE3_CRAWLER"
  | "SCOUR_RSS_BOT"
  | "SCOUTJET_CRAWLER"
  | "SCREAMINGFROG_CRAWLER"
  | "SCRIBD_CRAWLER"
  | "SCRITCH_CRAWLER"
  | "SCRUNCH_BOT"
  | "SEARCHATLAS_CRAWLER"
  | "SEEKBOT_CRAWLER"
  | "SEEKPORT_CRAWLER"
  | "SEEWITHKIDS_CRAWLER"
  | "SEMANTICAUDIENCE_CRAWLER"
  | "SEMANTICSCHOLAR_CRAWLER"
  | "SEMPITECH_CRAWLER"
  | "SEMRUSH_CRAWLER"
  | "SENTIONE_CRAWLER"
  | "SENTRY_CRAWLER"
  | "SENTRY_UPTIME_MONITOR"
  | "SENUTO_CRAWLER"
  | "SEOBILITY_CRAWLER"
  | "SEOKICKS_CRAWLER"
  | "SEOLIZER_CRAWLER"
  | "SEOPROFILER_CRAWLER"
  | "SEOSCANNERS_CRAWLER"
  | "SEOSTAR_CRAWLER"
  | "SEOZOOM_CRAWLER"
  | "SERENDEPUTY_CRAWLER"
  | "SERPSTATBOT_CRAWLER"
  | "SEZNAM_CRAWLER"
  | "SHAPBOT"
  | "SIMILARTECH_CRAWLER"
  | "SIMPLE_CRAWLER"
  | "SIRDATA_BOT"
  | "SISTRIX_007AC9_CRAWLER"
  | "SISTRIX_CRAWLER"
  | "SITEBOT_CRAWLER"
  | "SITEBULB"
  | "SITECHECKER_CRAWLER"
  | "SITEEXPLORER_CRAWLER"
  | "SITEIMPROVE_CRAWLER"
  | "SKYPE_PREVIEW"
  | "SLACK_CRAWLER"
  | "SLACK_IMAGE_PROXY"
  | "SMARTOLOGY_BOT"
  | "SNAP_PREVIEW"
  | "SNAPCHAT_ADSBOT"
  | "SOCIALRANK_CRAWLER"
  | "SOFTBYTELABS_CRAWLER"
  | "SOGOU_CRAWLER"
  | "SPECTATE_MONITOR"
  | "STARTME_CRAWLER"
  | "STATUSCAKE_MONITOR"
  | "STATUSNEST_CRAWLER"
  | "STEALC_BOTNET"
  | "STEAM_PREVIEW"
  | "STEPSTONE_CRAWLER"
  | "STORYGIZE_CRAWLER"
  | "STRACT_CRAWLER"
  | "STRIPE_CRAWLER"
  | "STRIPE_WEBHOOK"
  | "STUTTGART_CRAWLER"
  | "SUMMALY_CRAWLER"
  | "SUMMIFY_CRAWLER"
  | "SUPERFEEDR_CRAWLER"
  | "SURLY_CRAWLER"
  | "SWIFTBOT"
  | "SWIMGBOT"
  | "SYNAPSE_CRAWLER"
  | "SYNTHESI_BOT"
  | "SYSOMOS_CRAWLER"
  | "T3VERSIONS_CRAWLER"
  | "TABOOLA_CRAWLER"
  | "TAGOO_CRAWLER"
  | "TANGIBLEE_CRAWLER"
  | "TAVILY_BOT"
  | "TELEGRAM_CRAWLER"
  | "TESTOMATO_CRAWLER"
  | "THEOLDREADER_CRAWLER"
  | "THINKLAB_CRAWLER"
  | "TIGER_CRAWLER"
  | "TIKTOK_CRAWLER"
  | "TIMPI_CRAWLER"
  | "TINEYE_CRAWLER"
  | "TISCALI_CRAWLER"
  | "TOMBASCRAPER_CRAWLER"
  | "TOPLIST_CRAWLER"
  | "TORUS_CRAWLER"
  | "TOUTIAO_CRAWLER"
  | "TRAACKR_CRAWLER"
  | "TRACEMYFILE_CRAWLER"
  | "TRAFILATURA"
  | "TRENDICTION_CRAWLER"
  | "TRENDSMAP_CRAWLER"
  | "TROVE_CRAWLER"
  | "TROVIT_CRAWLER"
  | "TSM_BOT"
  | "TTD_CONTENT"
  | "TTRSS_FEEDFETCHER"
  | "TURNITIN_CRAWLER"
  | "TWEETEDTIMES_CRAWLER"
  | "TWEETMEMEBOT"
  | "TWENGA_CRAWLER"
  | "TWINGLY_CRAWLER"
  | "TWITTER_CRAWLER"
  | "TWOIP_CRAWLER"
  | "TWOIP_CRAWLER_CMS"
  | "TWURLY_CRAWLER"
  | "UAS_LINK_CHECKER"
  | "UBERMETRICS_CRAWLER"
  | "UBT_CRAWLER"
  | "UIP_BOT"
  | "UPFLOW_CRAWLER"
  | "UPTIME_MONITOR"
  | "UPTIMEBOT_MONITOR"
  | "UPTIMEROBOT_MONITOR"
  | "URLCLASSIFICATION_CRAWLER"
  | "URLSUMA_CRAWLER"
  | "USINE_NOUVELLE_CRAWLER"
  | "UTEXAS_CRAWLER"
  | "UTORRENT_CRAWLER"
  | "VEBIDOO_CRAWLER"
  | "VELEN_CRAWLER"
  | "VEOOZ_CRAWLER"
  | "VERCEL_CRAWLER"
  | "VERCEL_MONITOR_PREVIEW"
  | "VERISIGN_IPS_AGENT"
  | "VIBER_CRAWLER"
  | "VIGIL_CRAWLER"
  | "VIPNYTT_CRAWLER"
  | "VIRUSTOTAL_CRAWLER"
  | "VKROBOT_CRAWLER"
  | "VKSHARE_CRAWLER"
  | "VUHUV_CRAWLER"
  | "W3C_VALIDATOR_CSS"
  | "W3C_VALIDATOR_FEED"
  | "W3C_VALIDATOR_HTML"
  | "W3C_VALIDATOR_HTML_NU"
  | "W3C_VALIDATOR_I18N"
  | "W3C_VALIDATOR_LINKS"
  | "W3C_VALIDATOR_MOBILE"
  | "W3C_VALIDATOR_UNIFIED"
  | "WARD_BOT"
  | "WAREBAY_CRAWLER"
  | "WATCHFOR_BOT"
  | "WEBARCHIVE_CRAWLER"
  | "WEBCEO_CRAWLER"
  | "WEBCOMPANY_CRAWLER"
  | "WEBDATASTATS_CRAWLER"
  | "WEBEAVER_CRAWLER"
  | "WEBMEUP_CRAWLER"
  | "WEBMON"
  | "WEBPAGETEST_CRAWLER"
  | "WEBSITE_INFO_ROBOT"
  | "WEBZIO_CRAWLER"
  | "WEBZIO_CRAWLER_AI"
  | "WELLKNOWN_CRAWLER"
  | "WEPCH_CRAWLER"
  | "WESEE_CRAWLER"
  | "WGET"
  | "WHATSAPP_CRAWLER"
  | "WOCODI_CRAWLER"
  | "WOORANK_CRAWLER"
  | "WOORANK_CRAWLER_REVIEW"
  | "WORDPRESS_CRAWLER"
  | "WORDPRESS_CRAWLER_RSS"
  | "WORDUP_CRAWLER"
  | "WORIO_CRAWLER"
  | "WOTBOX_CRAWLER"
  | "XENU_CRAWLER"
  | "XOVIBOT_CRAWLER"
  | "XY_ARCHIVE_COMPLIANCE"
  | "YACY_CRAWLER"
  | "YAHOO_AD_MONITORING"
  | "YAHOO_CRAWLER"
  | "YAHOO_CRAWLER_JAPAN"
  | "YAHOO_MAIL_PROXY"
  | "YAHOO_PREVIEW"
  | "YAMANALAB_CRAWLER"
  | "YANDEX_CRAWLER"
  | "YANDEX_CRAWLER_JAVASCRIPT"
  | "YANDORI_RSS_BOT"
  | "YANGA_CRAWLER"
  | "YELLOWBP_CRAWLER"
  | "YEXT_BOT"
  | "YISOU_CRAWLER"
  | "YOOZ_CRAWLER"
  | "YOU_CRAWLER"
  | "ZABBIX_MONITOR"
  | "ZANISTA_BOT"
  | "ZEAL_BOT"
  | "ZGRAB"
  | "ZGRAT_BOTNET"
  | "ZOMBIE_BOT"
  | "ZOOMINFO_CRAWLER"
  | "ZUM_CRAWLER"
  | "ZUPERLIST_CRAWLER"
  | "ARCJET_SIGNALS";

export type ArcjetBotCategory =
  | "CATEGORY:ACADEMIC"
  | "CATEGORY:ADVERTISING"
  | "CATEGORY:AI"
  | "CATEGORY:AMAZON"
  | "CATEGORY:APPLE"
  | "CATEGORY:ARCHIVE"
  | "CATEGORY:BOTNET"
  | "CATEGORY:FEEDFETCHER"
  | "CATEGORY:GOOGLE"
  | "CATEGORY:META"
  | "CATEGORY:MICROSOFT"
  | "CATEGORY:MONITOR"
  | "CATEGORY:OPTIMIZER"
  | "CATEGORY:PREVIEW"
  | "CATEGORY:PROGRAMMATIC"
  | "CATEGORY:SEARCH_ENGINE"
  | "CATEGORY:SLACK"
  | "CATEGORY:SOCIAL"
  | "CATEGORY:TOOL"
  | "CATEGORY:UNKNOWN"
  | "CATEGORY:VERCEL"
  | "CATEGORY:WEBHOOK"
  | "CATEGORY:YAHOO";

export const categories: Record<ArcjetBotCategory, readonly ArcjetWellKnownBot[]> = Object.freeze({
  "CATEGORY:ACADEMIC": Object.freeze<ArcjetWellKnownBot[]>([
    "ACADEMICBOT_RTU",
    "ARANEA_CRAWLER",
    "BLACKBOARD_CRAWLER",
    "CISPA_CRAWLER",
    "CLASSLA_WEB_CRAWLER",
    "COMMONCRAWL_CRAWLER",
    "DOMAINSPROJECT_CRAWLER",
    "EPFL_CRAWLER",
    "EZID_CRAWLER",
    "LAW_UNIMI_CRAWLER",
    "LEIPZIG_FINDLINKS",
    "LEIPZIG_LCC",
    "MACOCU_CRAWLER",
    "NICT_CRAWLER",
    "SEMANTICSCHOLAR_CRAWLER",
    "TURNITIN_CRAWLER",
    "UTEXAS_CRAWLER",
    "YAMANALAB_CRAWLER",
  ]),
  "CATEGORY:ADVERTISING": Object.freeze<ArcjetWellKnownBot[]>([
    "ADAGIO_CRAWLER",
    "AHREFS_SITE_AUDIT",
    "AMAZON_ADBOT",
    "AUDIGENT_ADBOT",
    "BING_ADS",
    "CYBAA_BOT",
    "EZOIC_BOT",
    "GOOGLE_ADS_CONVERSIONS",
    "GOOGLE_ADSBOT",
    "GOOGLE_ADSBOT_MOBILE",
    "GOOGLE_ADSENSE",
    "GOOGLE_ADSENSE_GOOGLEBOT",
    "GOOGLE_ADWORDS",
    "MCONTEXTUAL_BOT",
    "META_EXTERNALADS",
    "MIXRANK_BOT",
    "MOAT_CRAWLER",
    "MSN_CRAWLER",
    "NANOINTERACTIVE_CRAWLER",
    "NETSEER_CRAWLER",
    "PRODUCTSUP_CRAWLER",
    "QUANTCAST_CRAWLER",
    "SCOPE3_CRAWLER",
    "SIRDATA_BOT",
    "SMARTOLOGY_BOT",
    "SNAPCHAT_ADSBOT",
    "TTD_CONTENT",
    "UIP_BOT",
    "YAHOO_AD_MONITORING",
  ]),
  "CATEGORY:AI": Object.freeze<ArcjetWellKnownBot[]>([
    "AI_SEARCH_BOT",
    "AI2_CRAWLER",
    "AI2_CRAWLER_DOLMA",
    "AIHIT_CRAWLER",
    "AMAZON_BEDROCK_AGENTCORE_BROWSER",
    "AMAZON_SEARCHBOT",
    "AMAZON_USER",
    "ANOMURA_CRAWLER",
    "ANTHROPIC_AI",
    "ANTHROPIC_CRAWLER",
    "ANTHROPIC_CRAWLER_SEARCH",
    "ANTHROPIC_CRAWLER_USER",
    "APIFY_BOT",
    "ATLASSIAN_BOT",
    "AZURE_AI_SEARCHBOT",
    "BOTIFY_CRAWLER",
    "BRIGHTBOT",
    "BYTEDANCE_CRAWLER",
    "CHANNEL3_BOT",
    "CLOUDFLARE_AI_SEARCH",
    "COHERE_CRAWLER",
    "COMMONCRAWL_CRAWLER",
    "CRAWL4AI",
    "CRAWLSPACE",
    "DIFFBOT_CRAWLER",
    "DUCKASSIST_BOT",
    "EXA_SEARCHBOT",
    "FACEBOOK_CRAWLER",
    "FACEBOOK_SHARE_CRAWLER",
    "FIRECRAWL_AGENT",
    "FLYRIVER_BOT",
    "FRIENDLYCRAWLER",
    "GLUTENFREEPLEASURE_CRAWLER",
    "GOOGLE_AGENT",
    "GOOGLE_CRAWLER_CLOUDVERTEX",
    "GOOGLE_GEMINI_DEEP_RESEARCH",
    "GOOGLE_GEMINI_NOTEBOOK",
    "IASK_CRAWLER",
    "IMAGESIFT_CRAWLER",
    "IMAGESPIDER",
    "IMG2DATASET",
    "INFEGY_CRAWLER",
    "INTEGRALADS_CRAWLER",
    "KAGI_FETCHER",
    "KIMI_BOT",
    "KIMI_SEARCHBOT",
    "KIMI_USER",
    "LAION_HUGGINGFACE_PROCESSOR",
    "LEADCRUNCH_CRAWLER",
    "LINKUP_BOT",
    "MEDIATOOLKIT_CRAWLER",
    "META_CRAWLER",
    "META_CRAWLER_USER",
    "MISTRAL_AI_INDEX",
    "MISTRAL_AI_TRAINING",
    "MISTRAL_AI_USER",
    "MOZILLA_TABSTACK",
    "NEWSAI",
    "NICT_CRAWLER",
    "NTENT_CRAWLER",
    "OMGILI_CRAWLER",
    "OPENAI_CRAWLER",
    "OPENAI_CRAWLER_SEARCH",
    "OPENAI_CRAWLER_USER",
    "PERPLEXITY_CRAWLER",
    "PERPLEXITY_USER",
    "PETALSEARCH_CRAWLER",
    "PHIND_BOT",
    "PRIMAL_CRAWLER",
    "PYTHON_SCRAPY",
    "SAFEDNS_CRAWLER",
    "SBINTUITIONS_BOT",
    "SEARCHATLAS_CRAWLER",
    "SEMANTICSCHOLAR_CRAWLER",
    "SENTIONE_CRAWLER",
    "SHAPBOT",
    "STORYGIZE_CRAWLER",
    "TAVILY_BOT",
    "TIKTOK_CRAWLER",
    "TIMPI_CRAWLER",
    "TURNITIN_CRAWLER",
    "VELEN_CRAWLER",
    "WEBZIO_CRAWLER_AI",
    "YOU_CRAWLER",
    "ZANISTA_BOT",
  ]),
  "CATEGORY:AMAZON": Object.freeze<ArcjetWellKnownBot[]>([
    "AMAZON_ADBOT",
    "AMAZON_ALEXA_CRAWLER",
    "AMAZON_BEDROCK_AGENTCORE_BROWSER",
    "AMAZON_CLOUDFRONT",
    "AMAZON_CRAWLER",
    "AMAZON_PRODUCT_DISCOVERY",
    "AMAZON_ROUTE53_HEALTH_CHECK",
    "AMAZON_SEARCHBOT",
    "AMAZON_SELLER_INITIATED_LISTING",
    "AMAZON_USER",
  ]),
  "CATEGORY:APPLE": Object.freeze<ArcjetWellKnownBot[]>([
    "AASA_BOT",
    "APPLE_CRAWLER",
    "IMESSAGE_PREVIEW",
  ]),
  "CATEGORY:ARCHIVE": Object.freeze<ArcjetWellKnownBot[]>([
    "ARCHIVE_IT",
    "ARCHIVEBOX",
    "ARCHIVEORG_ARCHIVER",
    "CCBOT_CRAWLER",
    "CLOUDFLARE_ARCHIVER",
    "COMMONCRAWL_CRAWLER",
    "EZID_CRAWLER",
    "INTERNETARCHIVE_CRAWLER_OSS",
    "IRC_ARCHIVEBOT",
    "LINKARCHIVER",
    "NICECRAWLER_ARCHIVE",
    "TRENDSMAP_CRAWLER",
    "WEBARCHIVE_CRAWLER",
    "XY_ARCHIVE_COMPLIANCE",
  ]),
  "CATEGORY:BOTNET": Object.freeze<ArcjetWellKnownBot[]>([
    "AGENTTESLA_BOTNET",
    "AMADEY_BOTNET",
    "BANKER_BOTNET",
    "BLACK_BOTNET",
    "BYOB_BOTNET",
    "DONUTMATE_BOTNET",
    "GAFGYT_BOTNET",
    "GULOADER_BOTNET",
    "HAJIME_BOTNET",
    "KINSING_BOTNET",
    "MIRAI_BOTNET",
    "MOOBOT_BOTNET",
    "MOZI_BOTNET",
    "REMCOSRAT_BOTNET",
    "STEALC_BOTNET",
    "ZGRAT_BOTNET",
  ]),
  "CATEGORY:FEEDFETCHER": Object.freeze<ArcjetWellKnownBot[]>([
    "APPLE_FEEDFETCHER",
    "ARTEMIS_WEB_READER",
    "AWARIO_CRAWLER_RSS",
    "BAZQUX_FEEDFETCHER",
    "BLOGTRAFFIC_FEEDFETCHER",
    "FEEDBIN_CRAWLER",
    "FEEDBURNER",
    "FEEDER_CO",
    "FEEDLY_FEEDFETCHER",
    "FEEDSPOT_FEEDFETCHER",
    "FEEDWIND",
    "FRESHRSS_FEEDFETCHER",
    "G2READER_CRAWLER",
    "GOOGLE_FEEDFETCHER",
    "GOOGLE_PRODUCER",
    "INOREADER_AGGREGATOR",
    "MINIFLUX_FEEDFETCHER",
    "NAVER_CRAWLER_RSS",
    "NEWSAI",
    "NEWSBLUR_AGGREGATOR",
    "POCKET_CRAWLER",
    "REFIND_CRAWLER",
    "RSSBOT_FEEDFETCHER",
    "RSSING_CRAWLER",
    "RSSMICRO_FEEDFETCHER",
    "SCOUR_RSS_BOT",
    "SERENDEPUTY_CRAWLER",
    "STARTME_CRAWLER",
    "SUPERFEEDR_CRAWLER",
    "THEOLDREADER_CRAWLER",
    "TTRSS_FEEDFETCHER",
    "WORDPRESS_CRAWLER_RSS",
    "YANDORI_RSS_BOT",
  ]),
  "CATEGORY:GOOGLE": Object.freeze<ArcjetWellKnownBot[]>([
    "GOOGLE_ADS_CONVERSIONS",
    "GOOGLE_ADSBOT",
    "GOOGLE_ADSBOT_MOBILE",
    "GOOGLE_ADSENSE",
    "GOOGLE_ADSENSE_GOOGLEBOT",
    "GOOGLE_ADWORDS",
    "GOOGLE_AGENT",
    "GOOGLE_APPENGINE",
    "GOOGLE_ASSOCIATION_SERVICE",
    "GOOGLE_CERTIFICATES_BRIDGE",
    "GOOGLE_CRAWLER",
    "GOOGLE_CRAWLER_CLOUDVERTEX",
    "GOOGLE_CRAWLER_IMAGE",
    "GOOGLE_CRAWLER_MOBILE",
    "GOOGLE_CRAWLER_NEWS",
    "GOOGLE_CRAWLER_OTHER",
    "GOOGLE_CRAWLER_SAFETY",
    "GOOGLE_CRAWLER_STORE",
    "GOOGLE_CRAWLER_VIDEO",
    "GOOGLE_CWS",
    "GOOGLE_FAVICON",
    "GOOGLE_FEEDFETCHER",
    "GOOGLE_GEMINI_DEEP_RESEARCH",
    "GOOGLE_GEMINI_NOTEBOOK",
    "GOOGLE_IMAGE_PROXY",
    "GOOGLE_INSPECTION_TOOL",
    "GOOGLE_LIGHTHOUSE",
    "GOOGLE_MESSAGES",
    "GOOGLE_PHYSICAL_WEB",
    "GOOGLE_PINPOINT",
    "GOOGLE_PREVIEW",
    "GOOGLE_PRODUCER",
    "GOOGLE_PUSH_NOTIFICATIONS",
    "GOOGLE_READ_ALOUD",
    "GOOGLE_SITE_VERIFICATION",
    "GOOGLE_STACKDRIVER_MONITORING",
    "GOOGLE_STRUCTURED_DATA_TESTING_TOOL",
    "GOOGLE_WEB_SNIPPET",
    "GOOGLE_XRAWLER",
  ]),
  "CATEGORY:META": Object.freeze<ArcjetWellKnownBot[]>([
    "FACEBOOK_CATALOG",
    "FACEBOOK_CRAWLER",
    "FACEBOOK_SHARE_CRAWLER",
    "META_CRAWLER",
    "META_CRAWLER_USER",
    "META_EXTERNALADS",
    "META_EXTERNALHIT",
    "META_WEBINDEXER",
    "WHATSAPP_CRAWLER",
  ]),
  "CATEGORY:MICROSOFT": Object.freeze<ArcjetWellKnownBot[]>([
    "AZURE_AI_SEARCHBOT",
    "AZURE_APP_INSIGHTS",
    "BING_ADS",
    "BING_CRAWLER",
    "BING_OFFICE_STORE",
    "BING_PREVIEW",
    "MICROSOFT_PREVIEW",
    "MICROSOFT_RESEARCH_CRAWLER",
    "MSN_CRAWLER",
    "SKYPE_PREVIEW",
  ]),
  "CATEGORY:MONITOR": Object.freeze<ArcjetWellKnownBot[]>([
    "ABEVAL_BOT",
    "ALERTSITE_MONITOR",
    "AMAZON_ROUTE53_HEALTH_CHECK",
    "AZURE_APP_INSIGHTS",
    "BETTERSTACK_MONITOR",
    "BETTERUPTIME_MONITOR",
    "BRANDVERITY_CRAWLER",
    "CARBON_UMBRELLA_BOT",
    "CENSYS_INSPECT",
    "CHANGEDETECTION_CRAWLER",
    "CHECKLY_MONITOR",
    "CLOUDFLARE_HEALTHCHECKS",
    "CLOUDFLARE_SECURITY_CENTER",
    "CLOUDFLARE_SSL_DETECTOR",
    "CLOUDFLARE_TRAFFIC_MANAGER",
    "DATADOG_MONITOR_SYNTHETICS",
    "DEADLINKCHECKER",
    "DISQUS_CRAWLER",
    "DUBBOT_CRAWLER",
    "DYNATRACE_MONITOR",
    "EASYCRON_MONITOR",
    "EDGEWATCH_MONITOR",
    "FEDISTATS_CRAWLER",
    "FLIPBOARD_PROXY",
    "FREEWEBMONITORING_MONITOR",
    "FRESHWORKS_MONITOR",
    "GOOGLE_CERTIFICATES_BRIDGE",
    "GOOGLE_SITE_VERIFICATION",
    "GOOGLE_STACKDRIVER_MONITORING",
    "GOOGLE_STRUCTURED_DATA_TESTING_TOOL",
    "GRAFANA_SYNTHETIC_MONITORING_AGENT",
    "GTMETRIX_MONITOR",
    "HANALEI_BOT",
    "HETRIXTOOLS_MONITOR",
    "HONEYBADGER_BOT",
    "HUBSPOT_CRAWLER",
    "HYDROZEN_MONITOR",
    "JETPACK_MONITOR",
    "KUMA_MONITOR",
    "MONITORBACKLINKS_CRAWLER",
    "MONTASTIC_MONITOR",
    "NEWRELIC_MONITOR",
    "NIXSTATS_CRAWLER",
    "NOAH_BOT",
    "OBSERVEPOINT_MONITOR",
    "OUTBRAIN_LINK_CHECKER",
    "PAGEPEEKER_CRAWLER",
    "PINGDOM_CRAWLER",
    "PLAGAWARE_BOT",
    "PODUPTIME",
    "POMOTHY_BOT",
    "PRTG_MONITOR",
    "SAFEDNS_CRAWLER",
    "SCRUNCH_BOT",
    "SENTRY_CRAWLER",
    "SENTRY_UPTIME_MONITOR",
    "SPECTATE_MONITOR",
    "STATUSCAKE_MONITOR",
    "SURLY_CRAWLER",
    "SYNTHESI_BOT",
    "TESTOMATO_CRAWLER",
    "TSM_BOT",
    "UPTIME_MONITOR",
    "UPTIMEBOT_MONITOR",
    "UPTIMEROBOT_MONITOR",
    "URLSUMA_CRAWLER",
    "VERCEL_MONITOR_PREVIEW",
    "W3C_VALIDATOR_CSS",
    "W3C_VALIDATOR_FEED",
    "W3C_VALIDATOR_HTML",
    "W3C_VALIDATOR_HTML_NU",
    "W3C_VALIDATOR_I18N",
    "W3C_VALIDATOR_LINKS",
    "W3C_VALIDATOR_MOBILE",
    "W3C_VALIDATOR_UNIFIED",
    "WATCHFOR_BOT",
    "WEBPAGETEST_CRAWLER",
    "XENU_CRAWLER",
    "ZABBIX_MONITOR",
  ]),
  "CATEGORY:OPTIMIZER": Object.freeze<ArcjetWellKnownBot[]>([
    "CLARITY_BOT",
    "CLOUDFLARE_PREFETCH",
    "CONDUCTOR_CRAWLER",
    "COTOYOGI_CRAWLER",
    "CRUSTY_CRAWLER",
    "DAREBOOST_CRAWLER",
    "DESKYO_BOT",
    "DOMCOP_BOT",
    "DUBBOT_CRAWLER",
    "EREPUBLIK_TOOLS_CRAWLER",
    "EXODUS_MOVEMENT_CRAWLER",
    "FEDICA_BOT",
    "FEDREPORTER_BOT",
    "GOOGLE_APPS_SCRIPT",
    "GOOGLE_LIGHTHOUSE",
    "GOOGLE_STRUCTURED_DATA_TESTING_TOOL",
    "HCARD_VALIDATOR",
    "HLIDAM_ROBOT",
    "INNGUMA_FETCHER",
    "INSTAPAPER",
    "LINKSINDEXER_BOT",
    "MADB_BOT",
    "MAGNET_ME_CRAWLER",
    "MEDIA_MONITORING_BOT",
    "MONSIDO_CRAWLER",
    "MOTOMINER_BOT",
    "MOZ_SITE_AUDIT",
    "NITRO_BOT",
    "ONCRAWL",
    "PAQLE_BOT",
    "QUALIFIED_BOT",
    "RAKUTEN_USA_IMAGE_BOT",
    "REPO_LOOKOUT_BOT",
    "RETROLISTE_CRAWLER",
    "SCREAMINGFROG_CRAWLER",
    "SISTRIX_CRAWLER",
    "SITEBULB",
    "STATUSNEST_CRAWLER",
    "TESTOMATO_CRAWLER",
    "UAS_LINK_CHECKER",
    "WARD_BOT",
    "WEBPAGETEST_CRAWLER",
    "WEBSITE_INFO_ROBOT",
    "ZOMBIE_BOT",
  ]),
  "CATEGORY:PREVIEW": Object.freeze<ArcjetWellKnownBot[]>([
    "BING_PREVIEW",
    "BITLY_CRAWLER",
    "BLUESKY_PREVIEW",
    "BUFFER_LINK_PREVIEW",
    "DAZZLE_BLUESKY_BOT",
    "DISCORD_CRAWLER",
    "DISCOURSE_ONEBOX",
    "DUCKDUCKGO_CRAWLER_FAVICONS",
    "EMBEDLY_CRAWLER",
    "FACEBOOK_SHARE_CRAWLER",
    "FASTMAIL_PREVIEW",
    "FLIPBOARD_PROXY",
    "GITHUB_CAMO",
    "GOOGLE_FAVICON",
    "GOOGLE_IMAGE_PROXY",
    "GOOGLE_MESSAGES",
    "GOOGLE_PREVIEW",
    "GOOGLE_WEB_SNIPPET",
    "IFRAMELY_PREVIEW",
    "IMESSAGE_PREVIEW",
    "KEYBASE_BOT",
    "LISTGEM_BOT",
    "MASTODON_CRAWLER",
    "META_CRAWLER_USER",
    "META_EXTERNALHIT",
    "MICROSOFT_PREVIEW",
    "PAGEPEEKER_CRAWLER",
    "SKYPE_PREVIEW",
    "SLACK_IMAGE_PROXY",
    "SNAP_PREVIEW",
    "STEAM_PREVIEW",
    "SYNAPSE_CRAWLER",
    "TELEGRAM_CRAWLER",
    "TWITTER_CRAWLER",
    "VERCEL_MONITOR_PREVIEW",
    "VIBER_CRAWLER",
    "WHATSAPP_CRAWLER",
    "YAHOO_MAIL_PROXY",
    "YAHOO_PREVIEW",
  ]),
  "CATEGORY:PROGRAMMATIC": Object.freeze<ArcjetWellKnownBot[]>([
    "CODA_SERVER_FETCHER",
    "GIGABLAST_CRAWLER_OSS",
    "GO_HTTP",
    "GOOGLE_APPENGINE",
    "GOWIKI_CRAWLER",
    "HTTP_GET",
    "JAVA_APACHE_HTTPCLIENT",
    "JAVA_ASYNCHTTPCLIENT",
    "JAVA_CRAWLER4J",
    "JAVA_HTTPUNIT",
    "JAVA_JERSEY",
    "JAVA_JETTY",
    "JAVA_OKHTTP",
    "JAVA_SNACKTORY",
    "JAVASCRIPT_AXIOS",
    "JAVASCRIPT_NODE_FETCH",
    "JAVASCRIPT_PHANTOM",
    "PERL_LIBWWW",
    "PERL_PCORE",
    "PHP_CURLCLASS",
    "PHP_PHPCRAWL",
    "PHP_SIMPLE_SCRAPER",
    "PHP_SIMPLEPIE",
    "PYTHON_AIOHTTP",
    "PYTHON_BITBOT",
    "PYTHON_HTTPX",
    "PYTHON_OPENGRAPH",
    "PYTHON_REQUESTS",
    "PYTHON_SCRAPY",
    "PYTHON_URLLIB",
    "RUBY_METAINSPECTOR",
    "STRIPE_CRAWLER",
  ]),
  "CATEGORY:SEARCH_ENGINE": Object.freeze<ArcjetWellKnownBot[]>([
    "ADDSEARCH_CRAWLER",
    "AHREFS_CRAWLER",
    "ALEXANDRIA_CRAWLER",
    "ALGOLIA_CRAWLER",
    "AMAZON_PRODUCT_DISCOVERY",
    "AMAZON_SEARCHBOT",
    "AMAZON_SELLER_INITIATED_LISTING",
    "APPLE_CRAWLER",
    "ASK_CRAWLER",
    "AVIRA_CRAWLER",
    "AZURE_AI_SEARCHBOT",
    "BING_CRAWLER",
    "BING_OFFICE_STORE",
    "DUCKASSIST_BOT",
    "DUCKDUCKGO_CRAWLER",
    "DUCKDUCKGO_CRAWLER_FAVICONS",
    "ENTIREWEB_CRAWLER",
    "EXA_SEARCHBOT",
    "FINDFILES_CRAWLER",
    "FLEEBS_BOT",
    "FREESPOKE_CRAWLER",
    "GEEDO_CRAWLER",
    "GEEDO_CRAWLER_PRODUCTS",
    "GEEDO_CRAWLER_SHOP",
    "GOOGLE_CRAWLER",
    "GOOGLE_CRAWLER_IMAGE",
    "GOOGLE_CRAWLER_MOBILE",
    "GOOGLE_CRAWLER_NEWS",
    "GOOGLE_CRAWLER_OTHER",
    "GOOGLE_CRAWLER_STORE",
    "GOOGLE_CRAWLER_VIDEO",
    "GOOGLE_INSPECTION_TOOL",
    "IASK_CRAWLER",
    "IBOU_BOT",
    "JOBSWITHGPT_BOT",
    "KAGI_CRAWLER",
    "KAGI_FETCHER",
    "KIMI_SEARCHBOT",
    "LINGUEE_CRAWLER",
    "LYONL_CRAWLER",
    "MAJESTIC_CRAWLER",
    "MARGINALIA_CRAWLER",
    "META_WEBINDEXER",
    "MISTRAL_AI_INDEX",
    "MOJEEK_CRAWLER",
    "NAVER_BOT",
    "NESTDADDY_BOT",
    "NETESTATE_CRAWLER",
    "OPENAI_CRAWLER_SEARCH",
    "OPENTHEBOX_BOT",
    "PETALSEARCH_CRAWLER",
    "PIPL_CRAWLER",
    "QWANT_CRAWLER",
    "SEEKPORT_CRAWLER",
    "STEPSTONE_CRAWLER",
    "STRACT_CRAWLER",
    "SWIFTBOT",
    "WEBZIO_CRAWLER",
    "WELLKNOWN_CRAWLER",
    "WEPCH_CRAWLER",
    "YACY_CRAWLER",
    "YAHOO_CRAWLER",
    "YANDEX_CRAWLER",
    "YANDEX_CRAWLER_JAVASCRIPT",
    "ZANISTA_BOT",
    "ZEAL_BOT",
  ]),
  "CATEGORY:SLACK": Object.freeze<ArcjetWellKnownBot[]>(["SLACK_CRAWLER", "SLACK_IMAGE_PROXY"]),
  "CATEGORY:SOCIAL": Object.freeze<ArcjetWellKnownBot[]>([
    "BLUESKY_PREVIEW",
    "BUFFER_LINK_PREVIEW",
    "DAZZLE_BLUESKY_BOT",
    "DIGG_CRAWLER",
    "DISCORD_CRAWLER",
    "DISCOURSE_ONEBOX",
    "EVERYONESOCIAL_CRAWLER",
    "FACEBOOK_CATALOG",
    "FACEBOOK_CRAWLER",
    "FACEBOOK_SHARE_CRAWLER",
    "FASTMAIL_PREVIEW",
    "GOOGLE_PREVIEW",
    "GOOGLE_WEB_SNIPPET",
    "GROUPME_CRAWLER",
    "IFRAMELY_PREVIEW",
    "IMESSAGE_PREVIEW",
    "IRC_ARCHIVEBOT",
    "KEYBASE_BOT",
    "LEMMY_CRAWLER",
    "LINKARCHIVER",
    "LINKEDIN_CRAWLER",
    "LISTGEM_BOT",
    "MASTODON_CRAWLER",
    "META_EXTERNALHIT",
    "NETICLE_CRAWLER",
    "PINTEREST_CRAWLER",
    "PINTREST_CRAWLER",
    "REDDIT_CRAWLER",
    "SNAP_PREVIEW",
    "STEAM_PREVIEW",
    "SYNAPSE_CRAWLER",
    "TELEGRAM_CRAWLER",
    "TIKTOK_CRAWLER",
    "TRENDSMAP_CRAWLER",
    "TWEETEDTIMES_CRAWLER",
    "TWITTER_CRAWLER",
    "VIBER_CRAWLER",
    "WHATSAPP_CRAWLER",
  ]),
  "CATEGORY:TOOL": Object.freeze<ArcjetWellKnownBot[]>([
    "AMAZON_BEDROCK_AGENTCORE_BROWSER",
    "COOKIEHUB_SCAN",
    "CRAWLSPACE",
    "CURL",
    "CYPRESS",
    "DCRAWL",
    "DOMAINSPROJECT_CRAWLER",
    "FIRECRAWL_AGENT",
    "GHOST_INSPECTOR",
    "GIGABLAST_CRAWLER_OSS",
    "GOPARSER_BOT",
    "GOT",
    "HEADLESS_CHROME",
    "HTTPIE",
    "IMG2DATASET",
    "INTERNETARCHIVE_CRAWLER_OSS",
    "IPIP_CRAWLER",
    "L9EXPLORE",
    "LAW_UNIMI_CRAWLER",
    "LINKCHECKER_PRO",
    "NAGIOS_CHECK_HTTP",
    "NMAP",
    "NUTCH",
    "ONCRAWL",
    "POSTMAN",
    "SITEBULB",
    "SUMMALY_CRAWLER",
    "TRAFILATURA",
    "WGET",
    "XENU_CRAWLER",
    "YEXT_BOT",
    "ZGRAB",
  ]),
  "CATEGORY:UNKNOWN": Object.freeze<ArcjetWellKnownBot[]>([
    "A6CORP_CRAWLER",
    "ABOUNDEX_CRAWLER",
    "ACAPBOT",
    "ACOON_CRAWLER",
    "ADBEAT_CRAWLER",
    "ADDTHIS_CRAWLER",
    "ADMANTX_CRAWLER",
    "ADSCANNER_CRAWLER",
    "ADSTXTCRAWLER",
    "ADVBOT_CRAWLER",
    "ALPHASEOBOT_CRAWLER",
    "ANDERSPINK_CRAWLER",
    "ANTIBOT",
    "APERCITE_CRAWLER",
    "ARA_CRAWLER",
    "ARATURKA_CRAWLER",
    "AROCOM_CRAWLER",
    "ASPIEGEL_CRAWLER",
    "AUDISTO_CRAWLER",
    "AWARIO_CRAWLER",
    "AWARIO_CRAWLER_SMART",
    "AWESOMECRAWLER",
    "B2BBOT",
    "BACKLINKTEST_CRAWLER",
    "BAIDU_CLOUD_WATCH",
    "BAIDU_CRAWLER",
    "BETABOT",
    "BIDSWITCH_CRAWLER",
    "BIGDATACORP_CRAWLER",
    "BIGLOTRON",
    "BINLAR",
    "BITSIGHT_CRAWLER",
    "BLOGMURA_CRAWLER",
    "BLP_BBOT",
    "BNF_CRAWLER",
    "BOMBORA_CRAWLER",
    "BOXCAR_CRAWLER",
    "BRAINOBOT",
    "BRANDONMEDIA_CRAWLER",
    "BRANDWATCH_CRAWLER",
    "BRIGHTEDGE_CRAWLER",
    "BUBLUP_CRAWLER",
    "BUILTWITH_CRAWLER",
    "BUZZSTREAM_CRAWLER",
    "CAPSULINK_CRAWLER",
    "CAREERX_CRAWLER",
    "CENTURYBOT",
    "CHECKMARKNETWORK_CRAWLER",
    "CHLOOE_CRAWLER",
    "CINCRAWDATA_CRAWLER",
    "CITESEERX_CRAWLER",
    "CLICKAGY_CRAWLER",
    "CLIQZ_CRAWLER",
    "CLOUDSYSTEMNETWORKS_CRAWLER",
    "COCCOC_CRAWLER",
    "COCOLYZE_CRAWLER",
    "CODEWISE_CRAWLER",
    "COGNITIVESEO_CRAWLER",
    "COMPANYBOOK_CRAWLER",
    "CONTENT_CRAWLER_SPIDER",
    "CONTEXTAD_CRAWLER",
    "CONTXBOT",
    "CONVERA_CRAWLER",
    "COOKIEBOT_CRAWLER",
    "CREATIVECOMMONS_CRAWLER",
    "CRITEO_CRAWLER",
    "CRYSTALSEMANTICS_CRAWLER",
    "CUREBOT_CRAWLER",
    "CUTBOT_CRAWLER",
    "CXENSE_CRAWLER",
    "CYBERPATROL_CRAWLER",
    "DATAFEEDWATCH_CRAWLER",
    "DATAFORSEO_CRAWLER",
    "DATAGNION_CRAWLER",
    "DATANYZE_CRAWLER",
    "DATAPROVIDER_CRAWLER",
    "DATENBUTLER_CRAWLER",
    "DAUM_CRAWLER",
    "DEEPNOC_CRAWLER",
    "DEUSU_CRAWLER",
    "DIGINCORE_CRAWLER",
    "DIGITALDRAGON_CRAWLER",
    "DISCOVERYENGINE_CRAWLER",
    "DNYZ_CRAWLER",
    "DOMAINCRAWLER_CRAWLER",
    "DOMAINREANIMATOR_CRAWLER",
    "DOMAINSBOT_CRAWLER",
    "DOMAINSTATS_CRAWLER",
    "DOMAINTOOLS_CRAWLER",
    "DOTNETDOTCOM_CRAWLER",
    "DRAGONMETRICS_CRAWLER",
    "DRIFTNET_CRAWLER",
    "DUEDIL_CRAWLER",
    "EC2LINKFINDER",
    "EDISTER_CRAWLER",
    "ELISABOT",
    "EPICTIONS_CRAWLER",
    "ERIGHT_CRAWLER",
    "EUROPARCHIVE_CRAWLER",
    "EVENTURES_CRAWLER",
    "EVENTURES_CRAWLER_BATCH",
    "EXENSA_CRAWLER",
    "EXPERIBOT_CRAWLER",
    "EXTLINKS_CRAWLER",
    "EYEOTA_CRAWLER",
    "FAST_CRAWLER",
    "FAST_CRAWLER_ENTERPRISE",
    "FEDORAPLANET_CRAWLER",
    "FEEDAFEVER_CRAWLER",
    "FEMTOSEARCH_CRAWLER",
    "FINDTHATFILE_CRAWLER",
    "FLAMINGOSEARCH_CRAWLER",
    "FLUFFY",
    "FR_CRAWLER",
    "FUELBOT",
    "FYREBOT",
    "G00G1E_CRAWLER",
    "G2WEBSERVICES_CRAWLER",
    "GARLIK_CRAWLER",
    "GENIEO_CRAWLER",
    "GIGABLAST_CRAWLER",
    "GINGER_CRAWLER",
    "GNAM_GNAM_SPIDER",
    "GNOWIT_CRAWLER",
    "GOO_CRAWLER",
    "GRAPESHOT_CRAWLER",
    "GROB_CRAWLER",
    "GROUPHIGH_CRAWLER",
    "GRUB",
    "GSLFBOT",
    "GWENE_CRAWLER",
    "HAOSOU_CRAWLER",
    "HATENA_CRAWLER",
    "HEADLINE_CRAWLER",
    "HOYER_CRAWLER",
    "HTTRACK",
    "HYPEFACTORS_CRAWLER",
    "HYPESTAT_CRAWLER",
    "HYSCORE_CRAWLER",
    "IA_ARCHIVER",
    "IDEASANDCODE_CRAWLER",
    "INDEED_CRAWLER",
    "INETDEX_CRAWLER",
    "INFOO_CRAWLER",
    "INTEGROMEDB_CRAWLER",
    "INTELIUM_CRAWLER",
    "IONOS_CRAWLER",
    "IP_WEB_CRAWLER",
    "ISKANIE_CRAWLER",
    "ISS_CRAWLER",
    "IT2MEDIA_CRAWLER",
    "ITINFLUENTIALS_CRAWLER",
    "JAMIEMBROWN_CRAWLER",
    "JETSLIDE_CRAWLER",
    "JOBBOERSE_CRAWLER",
    "JOOBLE_CRAWLER",
    "JUSPROG_CRAWLER",
    "JYXO_CRAWLER",
    "K7COMPUTING_CRAWLER",
    "KEMVI_CRAWLER",
    "KOMODIA_CRAWLER",
    "KOSMIO_CRAWLER",
    "LANDAUMEDIA_CRAWLER",
    "LASERLIKE_CRAWLER",
    "LB_SPIDER",
    "LEIKI_CRAWLER",
    "LIGHTSPEEDSYSTEMS_CRAWLER",
    "LINE_CRAWLER",
    "LINKAPEDIA_CRAWLER",
    "LINKDEX_CRAWLER",
    "LINKFLUENCE_CRAWLER",
    "LINKIS_CRAWLER",
    "LIPPERHEY_CRAWLER",
    "LIVELAP_CRAWLER",
    "LOGLY_CRAWLER",
    "LOOP_CRAWLER",
    "LSSBOT",
    "LSSBOT_ROCKET",
    "LTX71_CRAWLER",
    "LUMINATOR_CRAWLER",
    "MAILRU_CRAWLER",
    "MAPPYDATA_CRAWLER",
    "MAUIBOT",
    "MEGAINDEX_CRAWLER",
    "MELTWATER_CRAWLER",
    "METADATALABS_CRAWLER",
    "METAJOB_CRAWLER",
    "METAURI_CRAWLER",
    "METRICSTOOLS_CRAWLER",
    "MIGNIFY_CRAWLER",
    "MIGNIFY_IMRBOT",
    "MIXNODE_CACHE",
    "MOODLE_CRAWLER",
    "MOREOVER_CRAWLER",
    "MOZ_CRAWLER",
    "MUCKRACK_CRAWLER",
    "MULTIVIEWBOT",
    "NAVER_CRAWLER",
    "NEEVA_CRAWLER",
    "NERDBYNATURE_CRAWLER",
    "NERDYBOT_CRAWLER",
    "NETCRAFT_CRAWLER",
    "NETSYSTEMSRESEARCH_CRAWLER",
    "NETVIBES_CRAWLER",
    "NEWSHARECOUNTS_CRAWLER",
    "NEWSPAPER",
    "NEXTCLOUD_CRAWLER",
    "NIKI_BOT",
    "NING_CRAWLER",
    "NINJABOT",
    "NUZZEL_CRAWLER",
    "OCARINABOT",
    "OKRU_CRAWLER",
    "OPENGRAPHCHECK_CRAWLER",
    "OPENHOSE_CRAWLER",
    "OPENINDEX_CRAWLER",
    "ORANGE_CRAWLER",
    "ORANGE_FTGROUP_CRAWLER",
    "OUTCLICKS_CRAWLER",
    "PAGE_TO_RSS",
    "PAGETHING_CRAWLER",
    "PALOALTONETWORKS_CRAWLER",
    "PANSCIENT_CRAWLER",
    "PAPERLI_CRAWLER",
    "PHXBOT",
    "PICSEARCH_CRAWLER",
    "POSTRANK_CRAWLER",
    "PRCY_CRAWLER",
    "PRIVACORE_CRAWLER",
    "PRIVACYAWARE_CRAWLER",
    "PROFOUND_CRAWLER",
    "PROXIMIC_CRAWLER",
    "PULSEPOINT_CRAWLER",
    "PURE_CRAWLER",
    "RANKACTIVE_CRAWLER",
    "RETREVO_PAGE_ANALYZER",
    "RIDDER_CRAWLER",
    "RIVVA_CRAWLER",
    "RYTE_CRAWLER",
    "SCAN_INTERFAX_CRAWLER",
    "SCHMORP_CRAWLER",
    "SCOUTJET_CRAWLER",
    "SCRIBD_CRAWLER",
    "SCRITCH_CRAWLER",
    "SEEKBOT_CRAWLER",
    "SEEWITHKIDS_CRAWLER",
    "SEMANTICAUDIENCE_CRAWLER",
    "SEMPITECH_CRAWLER",
    "SEMRUSH_CRAWLER",
    "SENUTO_CRAWLER",
    "SEOBILITY_CRAWLER",
    "SEOKICKS_CRAWLER",
    "SEOLIZER_CRAWLER",
    "SEOPROFILER_CRAWLER",
    "SEOSCANNERS_CRAWLER",
    "SEOSTAR_CRAWLER",
    "SEOZOOM_CRAWLER",
    "SERPSTATBOT_CRAWLER",
    "SEZNAM_CRAWLER",
    "SIMILARTECH_CRAWLER",
    "SIMPLE_CRAWLER",
    "SISTRIX_007AC9_CRAWLER",
    "SITEBOT_CRAWLER",
    "SITECHECKER_CRAWLER",
    "SITEEXPLORER_CRAWLER",
    "SITEIMPROVE_CRAWLER",
    "SOCIALRANK_CRAWLER",
    "SOFTBYTELABS_CRAWLER",
    "SOGOU_CRAWLER",
    "STUTTGART_CRAWLER",
    "SUMMIFY_CRAWLER",
    "SWIMGBOT",
    "SYSOMOS_CRAWLER",
    "T3VERSIONS_CRAWLER",
    "TABOOLA_CRAWLER",
    "TAGOO_CRAWLER",
    "TANGIBLEE_CRAWLER",
    "THINKLAB_CRAWLER",
    "TIGER_CRAWLER",
    "TINEYE_CRAWLER",
    "TISCALI_CRAWLER",
    "TOMBASCRAPER_CRAWLER",
    "TOPLIST_CRAWLER",
    "TORUS_CRAWLER",
    "TOUTIAO_CRAWLER",
    "TRAACKR_CRAWLER",
    "TRACEMYFILE_CRAWLER",
    "TRENDICTION_CRAWLER",
    "TROVE_CRAWLER",
    "TROVIT_CRAWLER",
    "TWEETMEMEBOT",
    "TWENGA_CRAWLER",
    "TWINGLY_CRAWLER",
    "TWOIP_CRAWLER",
    "TWOIP_CRAWLER_CMS",
    "TWURLY_CRAWLER",
    "UBERMETRICS_CRAWLER",
    "UBT_CRAWLER",
    "UPFLOW_CRAWLER",
    "URLCLASSIFICATION_CRAWLER",
    "USINE_NOUVELLE_CRAWLER",
    "UTORRENT_CRAWLER",
    "VEBIDOO_CRAWLER",
    "VEOOZ_CRAWLER",
    "VERISIGN_IPS_AGENT",
    "VIGIL_CRAWLER",
    "VIPNYTT_CRAWLER",
    "VIRUSTOTAL_CRAWLER",
    "VKROBOT_CRAWLER",
    "VKSHARE_CRAWLER",
    "VUHUV_CRAWLER",
    "WAREBAY_CRAWLER",
    "WEBCEO_CRAWLER",
    "WEBCOMPANY_CRAWLER",
    "WEBDATASTATS_CRAWLER",
    "WEBEAVER_CRAWLER",
    "WEBMEUP_CRAWLER",
    "WEBMON",
    "WESEE_CRAWLER",
    "WOCODI_CRAWLER",
    "WOORANK_CRAWLER",
    "WOORANK_CRAWLER_REVIEW",
    "WORDPRESS_CRAWLER",
    "WORDUP_CRAWLER",
    "WORIO_CRAWLER",
    "WOTBOX_CRAWLER",
    "XOVIBOT_CRAWLER",
    "YANGA_CRAWLER",
    "YELLOWBP_CRAWLER",
    "YISOU_CRAWLER",
    "YOOZ_CRAWLER",
    "ZOOMINFO_CRAWLER",
    "ZUM_CRAWLER",
    "ZUPERLIST_CRAWLER",
  ]),
  "CATEGORY:VERCEL": Object.freeze<ArcjetWellKnownBot[]>([
    "VERCEL_CRAWLER",
    "VERCEL_MONITOR_PREVIEW",
  ]),
  "CATEGORY:WEBHOOK": Object.freeze<ArcjetWellKnownBot[]>(["ADYEN_WEBHOOK", "STRIPE_WEBHOOK"]),
  "CATEGORY:YAHOO": Object.freeze<ArcjetWellKnownBot[]>([
    "YAHOO_AD_MONITORING",
    "YAHOO_CRAWLER",
    "YAHOO_CRAWLER_JAPAN",
    "YAHOO_MAIL_PROXY",
    "YAHOO_PREVIEW",
  ]),
});
