// @generated by protoc-gen-es v2.2.0
// @generated from file proto/decide/v2/decide.proto (package proto.decide.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/decide/v2/decide.proto.
 */
export declare const file_proto_decide_v2_decide: GenFile;

/**
 * RuleTokenBucket is a token bucket rate limiting rule.
 *
 * @generated from message proto.decide.v2.RuleTokenBucket
 */
export declare type RuleTokenBucket = Message<"proto.decide.v2.RuleTokenBucket"> & {
  /**
   * Config: the number of tokens refilled per interval.
   *
   * @generated from field: uint32 config_refill_rate = 1;
   */
  configRefillRate: number;

  /**
   * Config: the refill interval in seconds.
   *
   * @generated from field: uint32 config_interval_seconds = 2;
   */
  configIntervalSeconds: number;

  /**
   * Config: the maximum number of tokens in the bucket.
   *
   * @generated from field: uint32 config_max_tokens = 3;
   */
  configMaxTokens: number;

  /**
   * Input: the key to track rate limits against (e.g. user ID).
   * Validated server-side: required, max 128 bytes, ASCII alphanumeric
   * plus dash and underscore ([a-zA-Z0-9_-]).
   *
   * @generated from field: string input_key = 10;
   */
  inputKey: string;

  /**
   * Input: the number of tokens requested.
   * A value of 0 is invalid and will produce an error result.
   * Omitting the field (proto3 default 0) is treated the same as 0.
   *
   * @generated from field: uint32 input_requested = 11;
   */
  inputRequested: number;
};

/**
 * Describes the message proto.decide.v2.RuleTokenBucket.
 * Use `create(RuleTokenBucketSchema)` to create a new message.
 */
export declare const RuleTokenBucketSchema: GenMessage<RuleTokenBucket>;

/**
 * RuleFixedWindow is a fixed window rate limiting rule.
 *
 * @generated from message proto.decide.v2.RuleFixedWindow
 */
export declare type RuleFixedWindow = Message<"proto.decide.v2.RuleFixedWindow"> & {
  /**
   * Config: the maximum number of requests allowed in the window.
   *
   * @generated from field: uint32 config_max_requests = 1;
   */
  configMaxRequests: number;

  /**
   * Config: the window duration in seconds.
   *
   * @generated from field: uint32 config_window_seconds = 2;
   */
  configWindowSeconds: number;

  /**
   * Input: the key to track rate limits against (e.g. user ID).
   * Validated server-side: required, max 128 bytes, ASCII alphanumeric
   * plus dash and underscore ([a-zA-Z0-9_-]).
   *
   * @generated from field: string input_key = 10;
   */
  inputKey: string;

  /**
   * Input: the number of requests to count.
   * A value of 0 is invalid and will produce an error result.
   * Omitting the field (proto3 default 0) is treated the same as 0.
   *
   * @generated from field: uint32 input_requested = 11;
   */
  inputRequested: number;
};

/**
 * Describes the message proto.decide.v2.RuleFixedWindow.
 * Use `create(RuleFixedWindowSchema)` to create a new message.
 */
export declare const RuleFixedWindowSchema: GenMessage<RuleFixedWindow>;

/**
 * RuleSlidingWindow is a sliding window rate limiting rule.
 *
 * @generated from message proto.decide.v2.RuleSlidingWindow
 */
export declare type RuleSlidingWindow = Message<"proto.decide.v2.RuleSlidingWindow"> & {
  /**
   * Config: the maximum number of requests allowed in the interval.
   *
   * @generated from field: uint32 config_max_requests = 1;
   */
  configMaxRequests: number;

  /**
   * Config: the sliding window interval in seconds.
   *
   * @generated from field: uint32 config_interval_seconds = 2;
   */
  configIntervalSeconds: number;

  /**
   * Input: the key to track rate limits against (e.g. user ID).
   * Validated server-side: required, max 128 bytes, ASCII alphanumeric
   * plus dash and underscore ([a-zA-Z0-9_-]).
   *
   * @generated from field: string input_key = 10;
   */
  inputKey: string;

  /**
   * Input: the number of requests to count.
   * A value of 0 is invalid and will produce an error result.
   * Omitting the field (proto3 default 0) is treated the same as 0.
   *
   * @generated from field: uint32 input_requested = 11;
   */
  inputRequested: number;
};

/**
 * Describes the message proto.decide.v2.RuleSlidingWindow.
 * Use `create(RuleSlidingWindowSchema)` to create a new message.
 */
export declare const RuleSlidingWindowSchema: GenMessage<RuleSlidingWindow>;

/**
 * RuleDetectPromptInjection is a prompt injection detection rule.
 *
 * @generated from message proto.decide.v2.RuleDetectPromptInjection
 */
export declare type RuleDetectPromptInjection = Message<"proto.decide.v2.RuleDetectPromptInjection"> & {
  /**
   * Input: the text to analyze for prompt injection.
   *
   * @generated from field: string input_text = 10;
   */
  inputText: string;
};

/**
 * Describes the message proto.decide.v2.RuleDetectPromptInjection.
 * Use `create(RuleDetectPromptInjectionSchema)` to create a new message.
 */
export declare const RuleDetectPromptInjectionSchema: GenMessage<RuleDetectPromptInjection>;

/**
 * RuleLocalSensitiveInfo is a local sensitive information detection rule —
 * evaluated locally by the SDK.
 *
 * @generated from message proto.decide.v2.RuleLocalSensitiveInfo
 */
export declare type RuleLocalSensitiveInfo = Message<"proto.decide.v2.RuleLocalSensitiveInfo"> & {
  /**
   * Config: entity types to allow (everything else is denied).
   * Mutually exclusive with config_entities_deny — only one may be set.
   * Validated server-side.
   * Values are entity type strings: "EMAIL", "PHONE_NUMBER",
   * "IP_ADDRESS", "CREDIT_CARD_NUMBER".
   *
   * @generated from field: repeated string config_entities_allow = 1;
   */
  configEntitiesAllow: string[];

  /**
   * Config: entity types to deny (everything else is allowed).
   * Mutually exclusive with config_entities_allow — only one may be set.
   * Validated server-side.
   *
   * @generated from field: repeated string config_entities_deny = 2;
   */
  configEntitiesDeny: string[];

  /**
   * Input: a hash of the analyzed text, for correlation and caching.
   * The actual text never leaves the SDK — only a hash is sent.
   *
   * @generated from field: string input_text_hash = 10;
   */
  inputTextHash: string;

  /**
   * The locally-computed result. Exactly one variant must be set:
   * - result_computed: the SDK successfully evaluated the rule.
   * - result_error: the SDK failed to evaluate (e.g. wasm load failure).
   * - result_not_run: the SDK did not attempt evaluation.
   *
   * @generated from oneof proto.decide.v2.RuleLocalSensitiveInfo.local_result
   */
  localResult: {
    /**
     * The SDK successfully evaluated the rule locally.
     *
     * @generated from field: proto.decide.v2.ResultLocalSensitiveInfo result_computed = 20;
     */
    value: ResultLocalSensitiveInfo;
    case: "resultComputed";
  } | {
    /**
     * The SDK failed to evaluate (e.g. wasm module failed to load).
     *
     * @generated from field: proto.decide.v2.ResultError result_error = 22;
     */
    value: ResultError;
    case: "resultError";
  } | {
    /**
     * The SDK did not attempt local evaluation.
     *
     * @generated from field: proto.decide.v2.ResultNotRun result_not_run = 23;
     */
    value: ResultNotRun;
    case: "resultNotRun";
  } | { case: undefined; value?: undefined };

  /**
   * Time spent computing the result, in milliseconds.
   * Optional so the server can distinguish "not measured" from 0 ms.
   *
   * @generated from field: optional uint64 result_computed_in_ms = 21;
   */
  resultComputedInMs?: bigint;
};

/**
 * Describes the message proto.decide.v2.RuleLocalSensitiveInfo.
 * Use `create(RuleLocalSensitiveInfoSchema)` to create a new message.
 */
export declare const RuleLocalSensitiveInfoSchema: GenMessage<RuleLocalSensitiveInfo>;

/**
 * RuleLocalCustom is a custom local rule — an arbitrary user-defined rule
 * evaluated locally by the SDK.
 *
 * @generated from message proto.decide.v2.RuleLocalCustom
 */
export declare type RuleLocalCustom = Message<"proto.decide.v2.RuleLocalCustom"> & {
  /**
   * Config: arbitrary key-value data defining the rule's configuration.
   *
   * @generated from field: map<string, string> config_data = 1;
   */
  configData: { [key: string]: string };

  /**
   * Input: arbitrary key-value data passed to the custom rule function.
   *
   * @generated from field: map<string, string> input_data = 10;
   */
  inputData: { [key: string]: string };

  /**
   * The locally-computed result. Exactly one variant must be set:
   * - result_computed: the SDK successfully evaluated the rule.
   * - result_error: the SDK failed to evaluate (e.g. custom rule threw).
   * - result_not_run: the SDK did not attempt evaluation.
   *
   * @generated from oneof proto.decide.v2.RuleLocalCustom.local_result
   */
  localResult: {
    /**
     * The SDK successfully evaluated the rule locally.
     *
     * @generated from field: proto.decide.v2.ResultLocalCustom result_computed = 20;
     */
    value: ResultLocalCustom;
    case: "resultComputed";
  } | {
    /**
     * The SDK failed to evaluate (e.g. custom rule function threw).
     *
     * @generated from field: proto.decide.v2.ResultError result_error = 22;
     */
    value: ResultError;
    case: "resultError";
  } | {
    /**
     * The SDK did not attempt local evaluation.
     *
     * @generated from field: proto.decide.v2.ResultNotRun result_not_run = 23;
     */
    value: ResultNotRun;
    case: "resultNotRun";
  } | { case: undefined; value?: undefined };

  /**
   * Time spent computing the result, in milliseconds.
   * Optional so the server can distinguish "not measured" from 0 ms.
   *
   * @generated from field: optional uint64 result_computed_in_ms = 21;
   */
  resultComputedInMs?: bigint;
};

/**
 * Describes the message proto.decide.v2.RuleLocalCustom.
 * Use `create(RuleLocalCustomSchema)` to create a new message.
 */
export declare const RuleLocalCustomSchema: GenMessage<RuleLocalCustom>;

/**
 * GuardRule wraps one of the supported rule types.
 *
 * @generated from message proto.decide.v2.GuardRule
 */
export declare type GuardRule = Message<"proto.decide.v2.GuardRule"> & {
  /**
   * The rule variant. Exactly one must be set.
   * Server-evaluated rules use fields 1–9, locally-evaluated rules use 10–19.
   *
   * Server-evaluated rules (1–9)
   *
   * @generated from oneof proto.decide.v2.GuardRule.rule
   */
  rule: {
    /**
     * Token bucket rate limiting rule.
     *
     * @generated from field: proto.decide.v2.RuleTokenBucket token_bucket = 1;
     */
    value: RuleTokenBucket;
    case: "tokenBucket";
  } | {
    /**
     * Fixed window rate limiting rule.
     *
     * @generated from field: proto.decide.v2.RuleFixedWindow fixed_window = 2;
     */
    value: RuleFixedWindow;
    case: "fixedWindow";
  } | {
    /**
     * Sliding window rate limiting rule.
     *
     * @generated from field: proto.decide.v2.RuleSlidingWindow sliding_window = 3;
     */
    value: RuleSlidingWindow;
    case: "slidingWindow";
  } | {
    /**
     * Prompt injection detection rule.
     *
     * @generated from field: proto.decide.v2.RuleDetectPromptInjection detect_prompt_injection = 4;
     */
    value: RuleDetectPromptInjection;
    case: "detectPromptInjection";
  } | {
    /**
     * Sensitive information detection rule (evaluated locally by the SDK).
     *
     * @generated from field: proto.decide.v2.RuleLocalSensitiveInfo local_sensitive_info = 10;
     */
    value: RuleLocalSensitiveInfo;
    case: "localSensitiveInfo";
  } | {
    /**
     * Custom local rule (evaluated locally by the SDK).
     *
     * @generated from field: proto.decide.v2.RuleLocalCustom local_custom = 11;
     */
    value: RuleLocalCustom;
    case: "localCustom";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message proto.decide.v2.GuardRule.
 * Use `create(GuardRuleSchema)` to create a new message.
 */
export declare const GuardRuleSchema: GenMessage<GuardRule>;

/**
 * GuardRuleSubmission wraps a configured rule with bound input and identity
 * metadata.
 *
 * Identity fields (1–9)
 *
 * @generated from message proto.decide.v2.GuardRuleSubmission
 */
export declare type GuardRuleSubmission = Message<"proto.decide.v2.GuardRuleSubmission"> & {
  /**
   * Opaque identifier for the RuleWithConfig instance in the SDK.
   * Shared across submissions from the same configured rule.
   * Echoed back in the corresponding GuardRuleResult for SDK-side
   * result correlation.
   *
   * @generated from field: string config_id = 1;
   */
  configId: string;

  /**
   * Opaque identifier for the RuleWithInput instance in the SDK.
   * Unique per submission — identifies the specific input binding.
   * Echoed back in the corresponding GuardRuleResult.
   *
   * @generated from field: string input_id = 2;
   */
  inputId: string;

  /**
   * An optional human-readable label for this rule submission.
   *
   * @generated from field: optional string label = 10;
   */
  label?: string;

  /**
   * Arbitrary key-value metadata attached to this rule submission.
   *
   * @generated from field: map<string, string> metadata = 11;
   */
  metadata: { [key: string]: string };

  /**
   * The rule to evaluate.
   *
   * @generated from field: proto.decide.v2.GuardRule rule = 20;
   */
  rule?: GuardRule;

  /**
   * The evaluation mode for this rule. Defaults to LIVE if not specified.
   * In DRY_RUN mode, the rule is evaluated and a conclusion is reported in
   * the result, but a DENY conclusion does not contribute to the aggregate
   * decision conclusion.
   *
   * @generated from field: proto.decide.v2.GuardRuleMode mode = 21;
   */
  mode: GuardRuleMode;
};

/**
 * Describes the message proto.decide.v2.GuardRuleSubmission.
 * Use `create(GuardRuleSubmissionSchema)` to create a new message.
 */
export declare const GuardRuleSubmissionSchema: GenMessage<GuardRuleSubmission>;

/**
 * ResultTokenBucket contains result details for a token bucket rate limit
 * evaluation.
 *
 * @generated from message proto.decide.v2.ResultTokenBucket
 */
export declare type ResultTokenBucket = Message<"proto.decide.v2.ResultTokenBucket"> & {
  /**
   * The conclusion for this rule (ALLOW or DENY).
   *
   * @generated from field: proto.decide.v2.GuardConclusion conclusion = 1;
   */
  conclusion: GuardConclusion;

  /**
   * The number of tokens remaining after this request.
   *
   * @generated from field: uint32 remaining_tokens = 2;
   */
  remainingTokens: number;

  /**
   * The maximum number of tokens in the bucket.
   *
   * @generated from field: uint32 max_tokens = 3;
   */
  maxTokens: number;

  /**
   * The number of seconds until the bucket is fully refilled.
   *
   * @generated from field: uint32 reset_seconds = 4;
   */
  resetSeconds: number;

  /**
   * The refill rate (tokens per interval).
   *
   * @generated from field: uint32 refill_rate = 5;
   */
  refillRate: number;

  /**
   * The refill interval in seconds.
   *
   * @generated from field: uint32 refill_interval_seconds = 6;
   */
  refillIntervalSeconds: number;
};

/**
 * Describes the message proto.decide.v2.ResultTokenBucket.
 * Use `create(ResultTokenBucketSchema)` to create a new message.
 */
export declare const ResultTokenBucketSchema: GenMessage<ResultTokenBucket>;

/**
 * ResultFixedWindow contains result details for a fixed window rate limit
 * evaluation.
 *
 * @generated from message proto.decide.v2.ResultFixedWindow
 */
export declare type ResultFixedWindow = Message<"proto.decide.v2.ResultFixedWindow"> & {
  /**
   * The conclusion for this rule (ALLOW or DENY).
   *
   * @generated from field: proto.decide.v2.GuardConclusion conclusion = 1;
   */
  conclusion: GuardConclusion;

  /**
   * The number of requests remaining in the current window.
   *
   * @generated from field: uint32 remaining_requests = 2;
   */
  remainingRequests: number;

  /**
   * The maximum number of requests allowed in the window.
   *
   * @generated from field: uint32 max_requests = 3;
   */
  maxRequests: number;

  /**
   * The number of seconds until the window resets.
   *
   * @generated from field: uint32 reset_seconds = 4;
   */
  resetSeconds: number;

  /**
   * The window duration in seconds.
   *
   * @generated from field: uint32 window_seconds = 5;
   */
  windowSeconds: number;
};

/**
 * Describes the message proto.decide.v2.ResultFixedWindow.
 * Use `create(ResultFixedWindowSchema)` to create a new message.
 */
export declare const ResultFixedWindowSchema: GenMessage<ResultFixedWindow>;

/**
 * ResultSlidingWindow contains result details for a sliding window rate limit
 * evaluation.
 *
 * @generated from message proto.decide.v2.ResultSlidingWindow
 */
export declare type ResultSlidingWindow = Message<"proto.decide.v2.ResultSlidingWindow"> & {
  /**
   * The conclusion for this rule (ALLOW or DENY).
   *
   * @generated from field: proto.decide.v2.GuardConclusion conclusion = 1;
   */
  conclusion: GuardConclusion;

  /**
   * The number of requests remaining in the current interval.
   *
   * @generated from field: uint32 remaining_requests = 2;
   */
  remainingRequests: number;

  /**
   * The maximum number of requests allowed in the interval.
   *
   * @generated from field: uint32 max_requests = 3;
   */
  maxRequests: number;

  /**
   * The number of seconds until the oldest request in the window expires.
   *
   * @generated from field: uint32 reset_seconds = 4;
   */
  resetSeconds: number;

  /**
   * The sliding window interval in seconds.
   *
   * @generated from field: uint32 interval_seconds = 5;
   */
  intervalSeconds: number;
};

/**
 * Describes the message proto.decide.v2.ResultSlidingWindow.
 * Use `create(ResultSlidingWindowSchema)` to create a new message.
 */
export declare const ResultSlidingWindowSchema: GenMessage<ResultSlidingWindow>;

/**
 * ResultPromptInjection contains result details for a prompt injection
 * detection evaluation.
 *
 * @generated from message proto.decide.v2.ResultPromptInjection
 */
export declare type ResultPromptInjection = Message<"proto.decide.v2.ResultPromptInjection"> & {
  /**
   * The conclusion for this rule (ALLOW or DENY).
   *
   * @generated from field: proto.decide.v2.GuardConclusion conclusion = 1;
   */
  conclusion: GuardConclusion;

  /**
   * Whether a prompt injection attempt was detected.
   *
   * @generated from field: bool detected = 2;
   */
  detected: boolean;
};

/**
 * Describes the message proto.decide.v2.ResultPromptInjection.
 * Use `create(ResultPromptInjectionSchema)` to create a new message.
 */
export declare const ResultPromptInjectionSchema: GenMessage<ResultPromptInjection>;

/**
 * ResultLocalSensitiveInfo contains result details for a sensitive information
 * detection evaluation.
 *
 * @generated from message proto.decide.v2.ResultLocalSensitiveInfo
 */
export declare type ResultLocalSensitiveInfo = Message<"proto.decide.v2.ResultLocalSensitiveInfo"> & {
  /**
   * The conclusion for this rule (ALLOW or DENY).
   *
   * @generated from field: proto.decide.v2.GuardConclusion conclusion = 1;
   */
  conclusion: GuardConclusion;

  /**
   * Whether sensitive information was detected.
   *
   * @generated from field: bool detected = 2;
   */
  detected: boolean;

  /**
   * The entity types that triggered detection (e.g. "EMAIL", "CREDIT_CARD_NUMBER").
   *
   * @generated from field: repeated string detected_entity_types = 3;
   */
  detectedEntityTypes: string[];
};

/**
 * Describes the message proto.decide.v2.ResultLocalSensitiveInfo.
 * Use `create(ResultLocalSensitiveInfoSchema)` to create a new message.
 */
export declare const ResultLocalSensitiveInfoSchema: GenMessage<ResultLocalSensitiveInfo>;

/**
 * ResultLocalCustom contains result details for a custom local rule evaluation.
 *
 * @generated from message proto.decide.v2.ResultLocalCustom
 */
export declare type ResultLocalCustom = Message<"proto.decide.v2.ResultLocalCustom"> & {
  /**
   * The conclusion for this rule (ALLOW or DENY).
   *
   * @generated from field: proto.decide.v2.GuardConclusion conclusion = 1;
   */
  conclusion: GuardConclusion;

  /**
   * Arbitrary key-value data returned by the custom rule function.
   *
   * @generated from field: map<string, string> data = 2;
   */
  data: { [key: string]: string };
};

/**
 * Describes the message proto.decide.v2.ResultLocalCustom.
 * Use `create(ResultLocalCustomSchema)` to create a new message.
 */
export declare const ResultLocalCustomSchema: GenMessage<ResultLocalCustom>;

/**
 * ResultNotRun is the result for a rule that was not evaluated (e.g. skipped
 * by the server).
 *
 * @generated from message proto.decide.v2.ResultNotRun
 */
export declare type ResultNotRun = Message<"proto.decide.v2.ResultNotRun"> & {
};

/**
 * Describes the message proto.decide.v2.ResultNotRun.
 * Use `create(ResultNotRunSchema)` to create a new message.
 */
export declare const ResultNotRunSchema: GenMessage<ResultNotRun>;

/**
 * ResultError is the result for a rule that encountered an error during
 * evaluation.
 *
 * @generated from message proto.decide.v2.ResultError
 */
export declare type ResultError = Message<"proto.decide.v2.ResultError"> & {
  /**
   * Human-readable error message.
   *
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * Machine-readable error code for programmatic handling (e.g. "EVALUATOR_NOT_FOUND").
   *
   * @generated from field: string code = 2;
   */
  code: string;
};

/**
 * Describes the message proto.decide.v2.ResultError.
 * Use `create(ResultErrorSchema)` to create a new message.
 */
export declare const ResultErrorSchema: GenMessage<ResultError>;

/**
 * GuardRuleResult contains the result of evaluating a single guard rule.
 *
 * Identity fields (1–9)
 *
 * @generated from message proto.decide.v2.GuardRuleResult
 */
export declare type GuardRuleResult = Message<"proto.decide.v2.GuardRuleResult"> & {
  /**
   * Server-generated unique identifier for this result (TypeID, prefix "gres").
   *
   * @generated from field: string result_id = 1;
   */
  resultId: string;

  /**
   * The config_id from the corresponding GuardRuleSubmission.
   *
   * @generated from field: string config_id = 2;
   */
  configId: string;

  /**
   * The input_id from the corresponding GuardRuleSubmission.
   *
   * @generated from field: string input_id = 3;
   */
  inputId: string;

  /**
   * The specific rule type that produced this result. Relevant because
   * ResultError and ResultNotRun can be produced by any rule type.
   *
   * @generated from field: proto.decide.v2.GuardRuleType type = 4;
   */
  type: GuardRuleType;

  /**
   * The typed result. The active variant determines the conclusion and
   * reason — evaluated results carry their own conclusion (ALLOW/DENY),
   * while error results default to ALLOW (fail open) and not_run
   * results are ALLOW.
   *
   * Server-evaluated rule results use fields 10–19, locally-evaluated
   * rule results use 20–29, cross-cutting results use 30–39.
   *
   * Server-evaluated rule results (10–19)
   *
   * @generated from oneof proto.decide.v2.GuardRuleResult.result
   */
  result: {
    /**
     * Token bucket rate limit result.
     *
     * @generated from field: proto.decide.v2.ResultTokenBucket token_bucket = 10;
     */
    value: ResultTokenBucket;
    case: "tokenBucket";
  } | {
    /**
     * Fixed window rate limit result.
     *
     * @generated from field: proto.decide.v2.ResultFixedWindow fixed_window = 11;
     */
    value: ResultFixedWindow;
    case: "fixedWindow";
  } | {
    /**
     * Sliding window rate limit result.
     *
     * @generated from field: proto.decide.v2.ResultSlidingWindow sliding_window = 12;
     */
    value: ResultSlidingWindow;
    case: "slidingWindow";
  } | {
    /**
     * Prompt injection detection result.
     *
     * @generated from field: proto.decide.v2.ResultPromptInjection prompt_injection = 13;
     */
    value: ResultPromptInjection;
    case: "promptInjection";
  } | {
    /**
     * Sensitive information detection result.
     *
     * @generated from field: proto.decide.v2.ResultLocalSensitiveInfo local_sensitive_info = 20;
     */
    value: ResultLocalSensitiveInfo;
    case: "localSensitiveInfo";
  } | {
    /**
     * Custom local rule result.
     *
     * @generated from field: proto.decide.v2.ResultLocalCustom local_custom = 21;
     */
    value: ResultLocalCustom;
    case: "localCustom";
  } | {
    /**
     * Error result — the rule failed to evaluate.
     *
     * @generated from field: proto.decide.v2.ResultError error = 30;
     */
    value: ResultError;
    case: "error";
  } | {
    /**
     * Not-run result — the rule was not evaluated.
     *
     * @generated from field: proto.decide.v2.ResultNotRun not_run = 31;
     */
    value: ResultNotRun;
    case: "notRun";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message proto.decide.v2.GuardRuleResult.
 * Use `create(GuardRuleResultSchema)` to create a new message.
 */
export declare const GuardRuleResultSchema: GenMessage<GuardRuleResult>;

/**
 * GuardDecision is the aggregate decision from evaluating all guard rules.
 *
 * Identity and conclusion (1–9)
 *
 * @generated from message proto.decide.v2.GuardDecision
 */
export declare type GuardDecision = Message<"proto.decide.v2.GuardDecision"> & {
  /**
   * Server-generated unique identifier for this decision (TypeID, prefix "gdec").
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The aggregate conclusion across all rules.
   *
   * @generated from field: proto.decide.v2.GuardConclusion conclusion = 2;
   */
  conclusion: GuardConclusion;

  /**
   * The broad reason for the conclusion (set when conclusion is DENY).
   *
   * @generated from field: proto.decide.v2.GuardReason reason = 3;
   */
  reason: GuardReason;

  /**
   * One result per submission, in submission order.
   *
   * @generated from field: repeated proto.decide.v2.GuardRuleResult rule_results = 10;
   */
  ruleResults: GuardRuleResult[];
};

/**
 * Describes the message proto.decide.v2.GuardDecision.
 * Use `create(GuardDecisionSchema)` to create a new message.
 */
export declare const GuardDecisionSchema: GenMessage<GuardDecision>;

/**
 * GuardRequest is a request to the Guard RPC.
 *
 * Observability fields (1–9)
 *
 * @generated from message proto.decide.v2.GuardRequest
 */
export declare type GuardRequest = Message<"proto.decide.v2.GuardRequest"> & {
  /**
   * The user-agent string identifying the SDK, runtime, and environment.
   * Follows user-agent conventions with product tokens and comments, e.g.
   * "arcjet-guard-js/0.1.0 (Node.js 24.0.0; next 15.2.0; linux arm64)".
   *
   * @generated from field: string user_agent = 1;
   */
  userAgent: string;

  /**
   * Total time from .guard() call to message serialization, in milliseconds.
   * Monotonic clock — no clock skew.
   * Optional so the server can distinguish "not measured" from 0 ms.
   *
   * @generated from field: optional uint64 local_eval_ms = 2;
   */
  localEvalMs?: bigint;

  /**
   * Client wall clock at message send time (Unix epoch, milliseconds).
   * Subject to clock skew but allows the server to estimate one-way
   * network latency as: server_receive_time - sent_at_ms - local_eval_ms.
   * Server should discard outliers where skew is clearly unreasonable.
   * Optional so the server can distinguish "not sent" from epoch 0.
   *
   * @generated from field: optional uint64 sent_at_ms = 3;
   */
  sentAtMs?: bigint;

  /**
   * A label identifying the protection boundary (e.g. "tools.weather").
   *
   * @generated from field: string label = 10;
   */
  label: string;

  /**
   * Arbitrary key-value metadata for customer correlation and analytics.
   * Passed through to the decision and available in logs/events.
   *
   * @generated from field: map<string, string> metadata = 11;
   */
  metadata: { [key: string]: string };

  /**
   * The rule submissions to evaluate.
   *
   * @generated from field: repeated proto.decide.v2.GuardRuleSubmission rule_submissions = 12;
   */
  ruleSubmissions: GuardRuleSubmission[];
};

/**
 * Describes the message proto.decide.v2.GuardRequest.
 * Use `create(GuardRequestSchema)` to create a new message.
 */
export declare const GuardRequestSchema: GenMessage<GuardRequest>;

/**
 * GuardResponse is the response from the Guard RPC.
 *
 * @generated from message proto.decide.v2.GuardResponse
 */
export declare type GuardResponse = Message<"proto.decide.v2.GuardResponse"> & {
  /**
   * The decision made by evaluating the guard rules.
   *
   * @generated from field: proto.decide.v2.GuardDecision decision = 1;
   */
  decision?: GuardDecision;
};

/**
 * Describes the message proto.decide.v2.GuardResponse.
 * Use `create(GuardResponseSchema)` to create a new message.
 */
export declare const GuardResponseSchema: GenMessage<GuardResponse>;

/**
 * GuardConclusion is the outcome of a guard decision — Arcjet's judgment.
 *
 * @generated from enum proto.decide.v2.GuardConclusion
 */
export enum GuardConclusion {
  /**
   * Unspecified conclusion — should not appear in practice.
   *
   * @generated from enum value: GUARD_CONCLUSION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The request is allowed.
   *
   * @generated from enum value: GUARD_CONCLUSION_ALLOW = 1;
   */
  ALLOW = 1,

  /**
   * The request is denied.
   *
   * @generated from enum value: GUARD_CONCLUSION_DENY = 2;
   */
  DENY = 2,
}

/**
 * Describes the enum proto.decide.v2.GuardConclusion.
 */
export declare const GuardConclusionSchema: GenEnum<GuardConclusion>;

/**
 * GuardReason is the broad reason category for a guard decision or rule result.
 *
 * @generated from enum proto.decide.v2.GuardReason
 */
export enum GuardReason {
  /**
   * Unspecified reason — no reason was set.
   *
   * @generated from enum value: GUARD_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The rule encountered an error during evaluation.
   *
   * @generated from enum value: GUARD_REASON_ERROR = 1;
   */
  ERROR = 1,

  /**
   * The rule was not evaluated (e.g. skipped by the server).
   *
   * @generated from enum value: GUARD_REASON_NOT_RUN = 2;
   */
  NOT_RUN = 2,

  /**
   * A custom user-defined rule produced this reason.
   *
   * @generated from enum value: GUARD_REASON_CUSTOM = 3;
   */
  CUSTOM = 3,

  /**
   * The conclusion was due to a rate limiting rule.
   *
   * @generated from enum value: GUARD_REASON_RATE_LIMIT = 10;
   */
  RATE_LIMIT = 10,

  /**
   * The conclusion was due to a prompt injection detection rule.
   *
   * @generated from enum value: GUARD_REASON_PROMPT_INJECTION = 11;
   */
  PROMPT_INJECTION = 11,

  /**
   * The conclusion was due to a sensitive information detection rule.
   *
   * @generated from enum value: GUARD_REASON_SENSITIVE_INFO = 12;
   */
  SENSITIVE_INFO = 12,
}

/**
 * Describes the enum proto.decide.v2.GuardReason.
 */
export declare const GuardReasonSchema: GenEnum<GuardReason>;

/**
 * GuardRuleType identifies the specific rule type that produced a result.
 *
 * @generated from enum proto.decide.v2.GuardRuleType
 */
export enum GuardRuleType {
  /**
   * Unspecified rule type — should not appear in practice.
   *
   * @generated from enum value: GUARD_RULE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * A custom user-defined rule.
   *
   * @generated from enum value: GUARD_RULE_TYPE_CUSTOM = 3;
   */
  CUSTOM = 3,

  /**
   * Token bucket rate limiting.
   *
   * @generated from enum value: GUARD_RULE_TYPE_TOKEN_BUCKET = 10;
   */
  TOKEN_BUCKET = 10,

  /**
   * Fixed window rate limiting.
   *
   * @generated from enum value: GUARD_RULE_TYPE_FIXED_WINDOW = 11;
   */
  FIXED_WINDOW = 11,

  /**
   * Sliding window rate limiting.
   *
   * @generated from enum value: GUARD_RULE_TYPE_SLIDING_WINDOW = 12;
   */
  SLIDING_WINDOW = 12,

  /**
   * Prompt injection detection.
   *
   * @generated from enum value: GUARD_RULE_TYPE_PROMPT_INJECTION = 13;
   */
  PROMPT_INJECTION = 13,

  /**
   * Sensitive information detection (evaluated locally by the SDK).
   *
   * @generated from enum value: GUARD_RULE_TYPE_LOCAL_SENSITIVE_INFO = 20;
   */
  LOCAL_SENSITIVE_INFO = 20,
}

/**
 * Describes the enum proto.decide.v2.GuardRuleType.
 */
export declare const GuardRuleTypeSchema: GenEnum<GuardRuleType>;

/**
 * GuardRuleMode is the evaluation mode for a rule submission.
 *
 * @generated from enum proto.decide.v2.GuardRuleMode
 */
export enum GuardRuleMode {
  /**
   * Unspecified mode — defaults to LIVE.
   *
   * @generated from enum value: GUARD_RULE_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Live mode: the rule is evaluated normally and contributes to the decision.
   *
   * @generated from enum value: GUARD_RULE_MODE_LIVE = 1;
   */
  LIVE = 1,

  /**
   * Dry-run mode: the rule is evaluated and produces a conclusion in its result,
   * but a DENY conclusion does not contribute to the aggregate decision.
   *
   * @generated from enum value: GUARD_RULE_MODE_DRY_RUN = 2;
   */
  DRY_RUN = 2,
}

/**
 * Describes the enum proto.decide.v2.GuardRuleMode.
 */
export declare const GuardRuleModeSchema: GenEnum<GuardRuleMode>;

/**
 * DecideService evaluates guard rules into a single decision.
 * Guard lives on DecideService to share infrastructure (auth, billing,
 * interceptors) with the existing Decide and Report RPCs.
 *
 * @generated from service proto.decide.v2.DecideService
 */
export declare const DecideService: GenService<{
  /**
   * Evaluate a set of guard rules and return a decision.
   *
   * @generated from rpc proto.decide.v2.DecideService.Guard
   */
  guard: {
    methodKind: "unary";
    input: typeof GuardRequestSchema;
    output: typeof GuardResponseSchema;
  },
}>;

