name: Push

on:
  push:
    # Only ever run `push` events against protected branches, likely just `main`
    branches:
      - main
      - release-please--branches--main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/reusable-test.yml
    permissions:
      contents: read

  examples:
    name: Build examples
    uses: ./.github/workflows/reusable-examples.yml
    permissions:
      contents: read

  release:
    runs-on: ubuntu-latest
    # Release Please is very fast, so we set a tiny timeout
    timeout-minutes: 2
    # The GitHub App token handles write permissions for contents and
    # pull-requests, so this job only needs minimal GITHUB_TOKEN permissions.
    permissions:
      contents: read
    steps:
      # Environment security
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          disable-sudo-and-containers: true
          egress-policy: audit

      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_PLEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_APP_PRIVATE_KEY }}

      - name: Release Please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
