name: Reusable examples workflow

on:
  workflow_call: {}

env:
  DO_NOT_TRACK: "1"

jobs:
  node-examples:
    name: ${{ matrix.folder }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
            release-assets.githubusercontent.com:443
          disable-sudo-and-containers: true
          egress-policy: block
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.node-version || '22' }}
      - name: Pin npm
        uses: ./.github/actions/pin-npm
      - run: npm ci && npm run build
      - run: npm ci
        working-directory: "examples/${{ matrix.folder }}"
      - env:
          ARCJET_KEY: ajkey_dummy
        run: npm run typecheck
        working-directory: "examples/${{ matrix.folder }}"
    strategy:
      matrix:
        folder:
          - mastra-agent
        include:
          - folder: mastra-agent
            node-version: 22
